dynatrace-oss/barista

- .github/ISSUE_TEMPLATE/bug.md
Create a better bug report issue template to have less work on filing a bug.
Furthermore, sections like steps to reproduce and context (environment) are more important to a bug
> docs: Improve bug issue template.

- .github/ISSUE_TEMPLATE/feature.md
Improve the feature request template and move our informational text into comments
> Improve the feature issue template.

- angular.json
- package-lock.json
- package.json
- tools/builders/builders.json
- tools/builders/index.ts
- tools/builders/package.json
- tools/builders/stylelint/index.ts
- tools/builders/stylelint/junit-formatter/existing-result.interface.ts
- tools/builders/stylelint/junit-formatter/index.ts
- tools/builders/stylelint/junit-formatter/junit-formatter.ts
- tools/builders/stylelint/junit-formatter/parse-exisiting-suite.ts
- tools/builders/stylelint/junit-formatter/parse-suite.ts
- tools/builders/stylelint/junit-formatter/parsed-suite.interface.ts
- tools/builders/stylelint/read-files.ts
- tools/builders/stylelint/schema.json
- tools/builders/stylelint/stylelint-builder-options.ts
- tools/builders/tsconfig.json
Create own stylelint builder to get reports and to hook custom lint rules in, later on.
> Create own stylelint builder

- README.md
> chore: Add browserstack to the README

- CONTRIBUTING.md
- README.md
- RELEASE.md
- components/package.json
- tools/builders/package.json
Changes the organization to dynatrace-oss
> Change the organization to the dynatrace-oss.

- components/alert/README.md
- components/button-group/README.md
- components/button/README.md
- components/card/README.md
- components/chart/README.md
- components/context-dialog/README.md
- components/copy-to-clipboard/README.md
- components/empty-state/README.md
- components/expandable-section/README.md
- components/filter-field/README.md
- components/form-field/README.md
- components/formatters/README.md
- components/icon/README.md
- components/info-group/README.md
- components/input/README.md
- components/loading-distractor/README.md
- components/menu/README.md
- components/micro-chart/README.md
- components/overlay/README.md
- components/pagination/README.md
- components/progress-bar/README.md
- components/show-more/README.md
- components/table/README.md
> barista: Replaced link-to-id helper with URLs

- .circleci/config.yml
- sonar-project.properties
> ci: Add sonar cloud to circle ci

- .circleci/config.yml
> ci: Add snyk integration

- angular.json
- apps/barista/src/main.scss
- apps/barista/src/styles/global/_fonts.scss
> barista(fonts): Added fonts to Barista styles.

- apps/barista/src/layout/toc/toc.ts
- apps/barista/src/pages/single-page/single-page.ts
> barista(toc): Update url when clicking on toc items.

- apps/dev/src/chart/chart-demo.component.html
- components/chart/src/chart.spec.ts
- components/chart/src/chart.ts
- components/chart/src/heatfield/chart-heatfield.html
- components/chart/src/heatfield/chart-heatfield.spec.ts
- components/chart/src/heatfield/chart-heatfield.ts
- components/chart/src/tooltip/chart-tooltip.ts
- components/chart/src/utils.ts
Removes the circular dependency of the chart
> Removes the circular dependency of the chart heatfield.

- .github/CODEOWNERS
Add @lukasholzer to root owners
> chore: Update codeowners.

- apps/barista/src/pages/single-page/single-page.ts
- apps/barista/src/styles/global/_base.scss
- apps/barista/src/styles/global/_variables.scss
- apps/barista/src/utils/fillTableData.ts
> barista(styling): render table correctly

- components/confirmation-dialog/src/confirmation-dialog.spec.ts
- components/confirmation-dialog/src/confirmation-dialog.ts
> fix(confirmation-dialog): Set activeDialog to null if dialog dismissed.

- .circleci/config.yml
> ci: Remove sonar context.

- angular.json
> fix: Added barista-fonts import in dev-app.

- .github/pull_request_template.md
<hr>
guidelines.
- Other (if none of the above apply)
> chore: Update pr template

- apps/dev/src/form-field/form-field-demo.component.html
- components/form-field/src/_form-field-theme.scss
- components/form-field/src/form-field.scss
> fix(form-field): Fixes an issue with the label color in a dark theme.

- .circleci/config.yml
> ci: Add snyk org

- apps/barista-examples/src/side-nav.component.scss
- apps/dev/src/devapp.component.scss
- components/chart/src/chart-options.ts
- components/style/README.md
> fix(chart): Fixes an issue where the chart did not use fallback font

- apps/demos/src/side-nav.component.scss
- apps/dev/src/devapp.component.scss
- components/chart/src/chart-options.ts
- components/style/README.md
@tomheller thats strange i clicked on merge on your pull request and it created a new pull request with me as co author?
> Fix barista fonts

- angular.json
> barista(font): Adjust fonts output path and styles imports.

- apps/barista/src/layout/tile/tile.html
- apps/barista/src/layout/tile/tile.ts
- apps/barista/src/pages/overview-page/overview-page.ts
- apps/barista/src/shared/page-contents.ts
- libs/shared/barista-definitions/src/lib/barista-definitions.ts
- tools/barista/src/builder/components.ts
- tools/barista/src/builder/overview.ts
- tools/barista/src/main.ts
>  barista(overview-pages): Created overview page json output.

- tools/barista/src/builder/components.ts
> barista(component-pages): Generate json output for all component pages.

- apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
<hr>
guidelines.
Relates to #244
> chore: Skip flaky selection area e2e tests for now.

- apps/barista/src/app.html
- apps/barista/src/app.module.ts
- apps/barista/src/app.ts
> feat/Barista Breadcrumbs

- tools/barista/src/builder/components.ts
- tools/barista/src/builder/overview.ts
> barista: Update nav groups and section headlines on overview pages.

- apps/barista/src/index.html
> barista: Add favicon.

- apps/barista/src/pages/single-page/single-page.html
- apps/barista/src/pages/single-page/single-page.ts
- tools/barista/src/builder/icons.ts
> barista: Show TOC by default.

- apps/barista/src/components/icon-color-wheel/icon-color-wheel.ts
> barista(icon-color-wheel): Set fill color before download.

- components/core/src/indicator/barista.json
- components/core/src/viewport/barista.json
- components/schematics/barista.json
- components/style/barista.json
- libs/shared/barista-definitions/src/lib/barista-definitions.ts
- tools/barista/src/builder/components.ts
- tools/barista/src/builder/icons.ts
- tools/barista/src/builder/overview.ts
> barista: Rename nav-group property.

- .github/CODEOWNERS
> chore: Fix user syntax error in codeowners and remove unused paths

- components/event-chart/src/event-chart-legend.scss
> fix(event-chart): Fixes an issue where colors did not match up

- apps/barista/src/pages/single-page/single-page.html
> barista: Remove sidenav temporarily.

- components/breadcrumbs/README.md
- components/chart/README.md
- components/filter-field/README.md
- components/micro-chart/README.md
- components/table/README.md
- components/tabs/README.md
- components/toggle-button-group/README.md
> docs: Remove handlebars syntax from readme files.

- apps/barista/src/app.html
- apps/barista/src/app.ts
> fix(barista-breadcrumbs): Better breadcrumb-item text

- apps/barista/src/pages/icon-overview-page/icon-overview-page.html
> barista: Remove sidenav on icon-overview temporarily.

- apps/barista/src/styles/global/_base.scss
- package-lock.json
- package.json
- tools/barista/Dockerfile
- tools/barista/src/transform.ts
> barista: Added markdown-it dl plugin and dl styles.

- tools/barista/src/builder/homepage.ts
> barista: Fix links on most-ordered-tiles on homepage.

- components/theming/src/colors.ts
> fix(theming): Fixed yellow-700 color value.

- apps/barista/src/app.html
- apps/barista/src/app.scss
- apps/barista/src/app.ts
> barista: Make the footer stick to the bottom on pages with less content.

- tools/barista/src/builder/components.ts
- tools/barista/src/builder/strapi.ts
- tools/barista/src/transform.ts
> barista: Added headline id transformer.

- apps/barista/src/styles/items/_items-dir.scss
- apps/barista/src/styles/items/_link.scss
- tools/barista/README.md
- tools/barista/src/builder/components.ts
- tools/barista/src/builder/strapi.ts
- tools/barista/src/transform.ts
> barista: Remove internal links from public content.

- apps/barista/src/app.html
- apps/barista/src/app.module.ts
- apps/barista/src/app.scss
- apps/barista/src/app.ts
- apps/barista/src/layout/footer/footer.html
- apps/barista/src/layout/smalltile/smalltile.html
- apps/barista/src/layout/smalltile/smalltile.scss
- apps/barista/src/layout/smalltile/smalltile.ts
- apps/barista/src/layout/tile/tile.scss
- apps/barista/src/pages/index-page/index-page.scss
- apps/barista/src/styles/global/_base.scss
- apps/barista/src/styles/global/_global-dir.scss
- apps/barista/src/styles/global/_theme.scss
- apps/barista/src/styles/items/_button.scss
- apps/barista/src/styles/items/_list.scss
> barista: Add/fix theming of categories.

- apps/barista/src/layout/sidenav/sidenav.html
- apps/barista/src/layout/tile/tile.ts
- apps/barista/src/pages/icon-overview-page/icon-overview-page.html
- apps/barista/src/pages/overview-page/overview-page.ts
- apps/barista/src/pages/single-page/single-page.html
- libs/shared/barista-definitions/src/lib/barista-definitions.ts
- tools/barista/src/generators/category-navigation.ts
- tools/barista/src/main.ts
> barista(sidenav): generate sidenav json output

- apps/barista/src/layout/sidenav/sidenav.scss
> barista: Hide sidenav on small screens and fix line-height.

- tools/barista/src/main.ts
> barista: Call overview page builder in build pages main function.

- package.json
- tools/barista/src/generators/category-navigation.ts
- tools/barista/src/main.ts
> barista: Fixes broken Barista build script.

- .circleci/config.yml
> ci: Switch to restricted context

- apps/barista/src/components/lazy-icon/lazy-icon.html
- apps/barista/src/components/lazy-icon/lazy-icon.scss
- apps/barista/src/pages/icon-overview-page/icon-overview-page.html
- apps/barista/src/pages/icon-overview-page/icon-overview-page.scss
- apps/barista/src/pages/icon-overview-page/icon-overview-page.ts
> barista: Improve iconfilter.

- .circleci/config.yml
- README.md
- jest.config.js
- package-lock.json
- package.json
> ci: Add codecov upload for the e2e test results

- .circleci/config.yml
- nx.json
> ci: Fix building tools twice

- apps/universal/src/app/kitchen-sink/kitchen-sink.html
- components/event-chart/src/event-chart.ts
> fix(event-chart): Fixes an issue with universal rendering.

- apps/barista/src/app.ts
- apps/barista/src/environments/environment.prod.ts
- apps/barista/src/environments/environment.ts
- apps/barista/src/layout/nav/nav.html
- apps/barista/src/layout/nav/nav.scss
- apps/barista/src/layout/nav/nav.ts
- apps/barista/src/shared/page.service.ts
- libs/shared/barista-definitions/src/lib/barista-definitions.ts
- tools/barista/src/generators/category-navigation.ts
> barista(nav): Generate nav json.

- tools/barista/Dockerfile
> barista: Update dockerfile to be able to build examples and tools.

- libs/shared/barista-definitions/src/lib/barista-definitions.ts
- tools/barista/src/builder/homepage.ts
- tools/barista/src/builder/strapi.ts
- tools/barista/src/utils/fetch-strapi-content.ts
> barista: Handle public and draft flag when fetching content from Strapi.

- tools/barista/src/generators/category-navigation.ts
> barista(overview-pages): Order tiles on overview pages by title.

- .github/workflows/pull-request-labeler.yml
- tools/pull-request-labeler/.dockerignore
- tools/pull-request-labeler/.gitignore
- tools/pull-request-labeler/Dockerfile
- tools/pull-request-labeler/entrypoint.sh
- tools/pull-request-labeler/package-lock.json
- tools/pull-request-labeler/package.json
- tools/pull-request-labeler/src/interfaces/commit-message.ts
- tools/pull-request-labeler/src/main.ts
- tools/pull-request-labeler/src/utils/add-rebase-label.ts
- tools/pull-request-labeler/src/utils/get-commit-messages-in-pull-request.ts
- tools/pull-request-labeler/src/utils/get-pull-request-details.ts
- tools/pull-request-labeler/src/utils/has-lgtm-label.ts
- tools/pull-request-labeler/src/utils/is-master-target.ts
- tools/pull-request-labeler/src/utils/process-commit-messages.ts
- tools/pull-request-labeler/src/utils/split-message-into-components.ts
- tools/pull-request-labeler/src/utils/update-target-labels.ts
- tools/pull-request-labeler/tsconfig.json
- tools/pull-request-labeler/tslint.json
> chore(tools): Added an action to target label pull requests.

- apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
- apps/components-e2e/src/components/filter-field/filter-field.html
- apps/components-e2e/src/components/filter-field/filter-field.po.ts
- apps/components-e2e/src/components/filter-field/filter-field.ts
- components/filter-field/src/filter-field.html
- components/filter-field/src/filter-field.ts
fix(filter-field): Fixes and issue where filters are not immediately removed when clicking the clear all button
Fixes #176
> fix(filter-field): Fixes and issue where filters are not immediately removed when clicking the clear all button

- apps/barista/src/components/live-example/live-example.html
- apps/barista/src/components/live-example/live-example.ts
- apps/barista/src/utils/create-component.ts
- libs/examples/src/alert/alert-dark-error-example/alert-dark-error-example.html
- libs/examples/src/alert/alert-examples.module.ts
- libs/examples/src/breadcrumbs/breadcrumbs-examples.module.ts
- libs/examples/src/context-dialog/context-dialog-examples.module.ts
- libs/examples/src/copy-to-clipboard/copy-to-clipboard-examples.module.ts
- libs/examples/src/input/input-examples.module.ts
- libs/examples/src/show-more/show-more-examples.module.ts
- tools/barista/src/transform.ts
> barista: Fixed examples.

- apps/barista/src/layout/nav/nav.html
- apps/barista/src/layout/nav/nav.ts
> barista(nav): Make the nav responsive.

- tools/barista/Dockerfile
> barista: Added axios to npm dependencies in Dockerfile.

- components/filter-field/src/filter-field-data-source.ts
- components/filter-field/src/filter-field-default-data-source.ts
- components/filter-field/src/filter-field-util.ts
- components/filter-field/src/index.ts
To be more flexible when developing custom data-sources or adding new functionallity to the filter-field new abstract methods have been added.
BREAKING CHANGE: Added new methods that have to be implemented when creating a custom data-source
Breaking change (fix or change that would cause existing functionality to not work as expected)
> feat(filter-field): Added new methods to abstract data-source class for more flexibility.

- apps/barista/src/layout/nav/nav.scss
> barista: Align brand logo and breadcrumbs.

- tools/barista/src/builder/components.ts
> barista: Transform documentation file names to lower case.

- apps/barista/src/pages/index-page/index-page.html
> barista(index-page): Remove search from index page.

- apps/barista/src/pages/overview-page/overview-page.scss
> barista(overview-page): Fix button margin in safari.

- components/chart/README.md
- components/chart/src/range/range.spec.ts
- components/chart/src/range/range.ts
- package-lock.json
Added close method to the `DtChartRange`
> feat(chart-range): Add possibility to close chart-range programmatically.

- CONTRIBUTING.md
> docs: Remove CLA note.

- .circleci/config.yml
- README.md
> build: Remove codecov since it is confusing

- apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
- apps/components-e2e/src/components/filter-field/filter-field.html
> chore(filter-field): Make e2e clear all more stable

- apps/barista/src/app.html
- apps/barista/src/app.module.ts
- apps/barista/src/layout/scroll-to-top/scroll-to-top.html
- apps/barista/src/layout/scroll-to-top/scroll-to-top.scss
- apps/barista/src/layout/scroll-to-top/scroll-to-top.ts
- apps/barista/src/pages/single-page/single-page.ts
> barista(scroll-top-button): Added scroll to top button.

- apps/barista/src/layout/toc/toc.ts
- apps/barista/src/shared/toc.service.ts
- tools/barista/src/transform.ts
> barista: Fix duplicate headline ids and wrong headlines in TOC.

- components/drawer/src/sidenav.scss
> fix(sidenav): Fixes scrolling behavior of the sidenav component

- apps/barista/src/app.ts
> barista: Added document title to each page.

- components/pagination/README.md
> docs(pagination): Remove page output from the documentation.

- components/chart/README.md
- components/chart/src/timestamp/timestamp.spec.ts
- components/chart/src/timestamp/timestamp.ts
> feat(chart-timestamp): Add possibility to close chart-timestamp programmatically

- angular.json
Fixes an issue where the components build was not running in case of a missing production configuration.
> build: Fix not running components build.

- components/index.ts
- components/package.json
- documentation/getting-started.md
> chore(build): Remove root package

- angular.json
- components/package.json
- tools/builders/packager/build.ts
- tools/builders/packager/schema.json
- tools/builders/packager/schema.ts
- tools/builders/packager/sync-version.ts
- tools/builders/util/json-utils.ts
Adds the tooling for syncing the barista-components version in the root `package.json` to the `package.json` provided in the build artifact.
Other (if none of the above apply): Build
> build: Added syncing the barista-component version to the artifacts package.json

- apps/barista/src/app.module.ts
- apps/barista/src/components/components.module.ts
- apps/barista/src/components/headline-link/headline-link.html
- apps/barista/src/components/headline-link/headline-link.ts
- apps/barista/src/styles/items/_headlines.scss
- apps/barista/src/styles/items/_items-dir.scss
- tools/barista/src/builder/components.ts
- tools/barista/src/builder/strapi.ts
- tools/barista/src/transform.ts
> barista(copy-headlines): Copy the headlines to clipboard.

- tools/barista/src/builder/icons.ts
> barista: Generate IDs for headlines on icon-related pages.

- libs/examples/src/table/table-favorite-column-no-header-example/table-favorite-column-no-header-example.html
Fixes the broken build on master for the examples / barista
> chore: Fix broken method call in production config

- libs/examples/src/chart/chart-behavior-switch-example/chart-behavior-switch-example.html
- libs/examples/src/chart/chart-behavior-switch-example/chart-behavior-switch-example.ts
> barista: Fix chart behavior switch example.

- .circleci/config.yml
> chore: Remove xlarge resource from circle.yml again. Trial has ended

- CHANGELOG.md
- apps/components-e2e/src/components/filter-field/filter-field.ts
- components/chart/index.ts
- components/filter-field/src/filter-field-default-data-source.ts
- components/filter-field/src/filter-field.spec.ts
- components/show-more/README.md
- components/show-more/src/show-more.spec.ts
- components/show-more/src/show-more.ts
- components/style/theming.scss
- libs/examples/src/filter-field/filter-field-async-example/filter-field-async-example.ts
- libs/examples/src/filter-field/filter-field-clearall-example/filter-field-clearall-example.ts
- libs/examples/src/filter-field/filter-field-default-example/filter-field-default-example.ts
- libs/examples/src/filter-field/filter-field-distinct-example/filter-field-distinct-example.ts
- libs/examples/src/filter-field/filter-field-programmatic-filters-example/filter-field-programmatic-filters-example.ts
- libs/examples/src/filter-field/filter-field-readonly-non-editable-tags-example/filter-field-readonly-non-editable-tags-example.ts
- libs/examples/src/filter-field/filter-field-unique-example/filter-field-unique-example.ts
- package-lock.json
Changes relevant to findings in the rc.0 release
> Rc findings

- libs/examples/src/filter-field/filter-field-programmatic-filters-example/filter-field-programmatic-filters-example.ts
- tools/release/src/stage-release-cli.ts
- tools/release/src/stage-release/stage-release.ts
> Minor fixes

- CHANGELOG.md
- package.json
> chore: Bump version to 5.0.0-rc.1 w/ changelog

- tools/release/src/stage-release/stage-release.ts
> chore: Comment github api call - it needs authentication

- apps/components-e2e/src/components/drawer/drawer.e2e.ts
- tools/release/src/stage-release/stage-release.ts
FYI @peter-affenzeller 
Fixes a flaky e2e test for the drawer
> Fix flaky e2e drawer test

- .github/CODEOWNERS
> Update Codeowners for releasing.

- components/filter-field/src/filter-field-default-data-source.ts
- components/filter-field/src/filter-field.spec.ts
Improves typing for the data structures the default-data-source takes.
Breaking change (fix or change that would cause existing functionality to not work as expected)
> feat(filter-field): Improves typing for the data structures the default-data-source takes.

- CHANGELOG.md
- package-lock.json
- package.json
<hr>
guidelines.
Release Version 5.0.0
> chore: Bump version to 5.0.0 w/ changelog

- .github/workflows/cherry-picker.yml
- tools/cherry-picker/.dockerignore
- tools/cherry-picker/.gitignore
- tools/cherry-picker/Dockerfile
- tools/cherry-picker/entrypoint.sh
- tools/cherry-picker/package-lock.json
- tools/cherry-picker/package.json
- tools/cherry-picker/src/main.ts
- tools/cherry-picker/src/utils/find-merged-commits-on-master.ts
- tools/cherry-picker/src/utils/get-current-minor-and-patch-branches.ts
- tools/cherry-picker/src/utils/get-pull-request-details.ts
- tools/cherry-picker/src/utils/is-master-target.ts
- tools/cherry-picker/src/utils/pull-request-add-comment.ts
- tools/cherry-picker/src/utils/pull-request-has-label.ts
- tools/cherry-picker/tsconfig.json
- tools/cherry-picker/tslint.json
> chore(tools): Add the auto cherry-picker back to the repository

- angular.json
- apps/components-e2e/jest.config.js
- apps/components-e2e/src/components/drawer/drawer.e2e.ts
- apps/components-e2e/src/test-setup.ts
- apps/components-e2e/src/utils/is-close-to.spec.ts
- apps/components-e2e/tsconfig.json
- apps/components-e2e/tsconfig.spec.json
isCloseTo util function that was used in the e2e tests was delivering
false negatives. The function has been refactored and now has unit tests
to make sure the expectations are correct.
Fixes #445
> chore(drawer): Refactor and test isCloseTo util.

- components/tag/src/tag-add/tag-add.html
- components/tag/src/tag-add/tag-add.scss
> fix(tag-add): Improved styling of button textcontent

- components/tag/src/tag-list/tag-list.scss
- components/tag/src/tag-list/tag-list.ts
> fix(tag-list): Fixes rendering of Tag-List when loading a page

- package-lock.json
Updated the outdated browserlist dependency
Other
> chore: Updated caniuse-lite browserlist

- components/schematics/src/ng-update/tests/__snapshots__/root-imports.spec.ts.snap
- components/schematics/src/ng-update/tests/root-imports.spec.ts
Adds a test to migration, to check root import migration on specfiles.
> feat(ng-update): Added test for .spec file

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 5.0.1 w/ changelog

- angular.json
Currently, our e2e tests are sometimes failing with: All parallel tests are currently in use, including the queued tests. When we only use 4 we should always have a slot free for that.
```
Error: API error 13: 
All parallel tests are currently in use, including the queued tests. Please wait to finish or upgrade your plan to add more sessions.
at /home/circleci/barista/node_modules/testcafe-browser-provider-browserstack/lib/backends/automate.js:138:19
at invokeCallback (/home/circleci/barista/node_modules/pinkie/index.js:60:12)
at Array.forEach (<anonymous>)
at publish (/home/circleci/barista/node_modules/pinkie/index.js:147:32)
at Array.publishFulfillment (/home/circleci/barista/node_modules/pinkie/index.js:152:2)
at Immediate.asyncFlush …
```
> Only run 4 e2e tests in parallel to leave space in the queue.

- libs/examples/src/filter-field/filter-field-async-example/filter-field-async-example.ts
- libs/examples/src/filter-field/filter-field-clearall-example/filter-field-clearall-example.ts
- libs/examples/src/filter-field/filter-field-default-example/filter-field-default-example.ts
- libs/examples/src/filter-field/filter-field-distinct-example/filter-field-distinct-example.ts
- libs/examples/src/filter-field/filter-field-programmatic-filters-example/filter-field-programmatic-filters-example.ts
- libs/examples/src/filter-field/filter-field-readonly-non-editable-tags-example/filter-field-readonly-non-editable-tags-example.ts
Fixes invalid example data.
We should add checks that prevents broken examples to be committed.
> chore(filter-field): Fixes invalid example data.

- apps/components-e2e/src/app/app.routing.module.ts
- apps/components-e2e/src/components/chart/selection-area/selection-area.ts
- apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.e2e.ts
- apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.html
- apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.module.ts
- apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.po.ts
- apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.ts
- apps/components-e2e/src/components/drawer/drawer.ts
- apps/components-e2e/src/components/highlight/highlight.e2e.ts
- apps/components-e2e/src/components/highlight/highlight.html
- apps/components-e2e/src/components/highlight/highlight.module.ts
- apps/components-e2e/src/components/highlight/highlight.po.ts
- apps/components-e2e/src/components/highlight/highlight.ts
Newly added e2e tests for `highlight` and `confirmation-dialog`.
Other (Added e2e tests for highlight and confirmation-dialog)
> test: Added e2e tests for confirmation-dialog and highlight

- apps/barista/src/app.module.ts
Added a configuration to the router module in Barista to fix the issue that parts of the URL get removed (because the location service and the router don't work together very well).
Thanks @thomaspink 
Barista fix
> barista: Add router config to not interfere with the location service.

- .github/CODEOWNERS
Adjusts codeowners to better fit the team structure and roles.
> chore: Updated codeowners to better fit the team structure and roles.

- tools/barista/src/builder/components.ts
- tools/barista/src/utils/fetch-strapi-content.ts
Updated the endpoint as we just moved Strapi to its final location 🎉 
Barista update
> barista: Update Strapi endpoint.

- .snyk
- package-lock.json
- package.json
Currently, our security gate fails because we have a vulnerability in a transitive dependency. Therefore it is only used for changelog generation it is not that critical.
Nevertheless, I filed an issue at the conventional changelog and ignored the vulnerability for 30days.
https://github.com/conventional-changelog/conventional-changelog/issues/592
<hr> …
> Add snyk policy file for known vulnerability.

- components/filter-field/src/filter-field-module.ts
- components/filter-field/src/filter-field.html
> feat(filter-field): Added highlighting of the currend input value to the options.

- .github/workflows/barista-preview.yml
Creates the GitHub action for generating the a preview version of the barista app for each PR
> Create barista preview

- CONTRIBUTING.md
> docs: Added new pr workflow to contributing documentation.

- angular.json
To keep the build logs on the ci shorter and more human readable disable the progress logging of the angular build.
<hr>
guidelines. …
> build: Disable logging the build progress.

- components/legend/src/legend-item.ts
> fix(legend): Fixes issue whether the legend item does not work with the new ivy engine.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 5.1.0 w/ changelog

- components/autocomplete/src/autocomplete-trigger.ts
perf(autocomplete): Fixes an issue when toggling multiple times a subscription is not cleaned up.
> perf(autocomplete): Fixes an issue when toggling multiple times a subscription is not cleaned up.

- apps/barista/src/app.ts
- apps/barista/src/shared/location.service.ts
Description: this pr solves an issue where barista cannot be built on a Windows machine. It seems additional type annotation is needed for rxjs on Windows.
<hr>
guidelines. …
> barista: Added typings for Observables in barista app.

- components/autocomplete/src/autocomplete-trigger.ts
- components/filter-field/src/filter-field-range/filter-field-range-trigger.ts
Switched the autocomplete and filterfield overlay to use the
DtFlexibleConnectedPositionStrategy instead of the CDK
FlexibleConnectedPositionStrategy. The Dt version can deal with the
clusters page-ribbon component and in general deals with better with
overlaying elements.
Fixes #451
@thomaspink @ffriedl89 As we have to change the constructor signature here, should we consider this a breaking change?
> fix(autocomplete, filter-field): Fixes an issue with overlay positioning.

- .circleci/config.yml
- angular.json
- apps/demos/src/barista-examples.a11y.ts
- apps/demos/src/nav-items.template
- apps/demos/tsconfig.a11y.json
Run axe-a11y tests on ci and check for console errors in example.
<hr>
guidelines.
> Run a11y tests on our ci.

- .circleci/config.yml
- package.json
Try to speed up our ci resources with parallelization and beeing wasteful with our credits 💯
> ci: Speedup ci with parallel and xlarge resource.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 5.1.1 w/ changelog

- apps/components-e2e/src/components/filter-field/filter-field.po.ts
- apps/dev/src/filter-field/testdata.ts
- components/filter-field/src/filter-field.spec.ts
- components/filter-field/src/filter-field.ts
Fixes an issue where options set on an async autocomplete are shown.
> fix(filter-field): Fixes an issue where options set on an async autocomplete are shown.

- CONTRIBUTING.md
Fixed broken link.
Documentation
> docs: Fixed links to new issue templates.

- tools/environments/barista-environment.interface.ts
- tools/environments/barista-environment.prod.ts
- tools/environments/barista-environment.ts
To avoid problems during the angular environment replacements, we have
extracted the interface to its own file.
Fixes #569
Other
> barista: Extract shared interface from environment files.

- components/confirmation-dialog/README.md
Added a snippet for UX.
fyi @ursula-wieshofer
Barista
> docs(confirmation-dialog): Added UX snippet for animation section.

- apps/dev/src/filter-field/filter-field-demo.component.html
- apps/dev/src/filter-field/filter-field-demo.component.ts
- components/filter-field/README.md
- components/filter-field/src/filter-field-tag/filter-field-tag.ts
- components/filter-field/src/filter-field.html
- components/filter-field/src/filter-field.scss
- components/filter-field/src/filter-field.spec.ts
- components/filter-field/src/filter-field.ts
- libs/examples/src/filter-field/filter-field-disabled-example/filter-field-disabled-example.html
- libs/examples/src/filter-field/filter-field-disabled-example/filter-field-disabled-example.ts
- libs/examples/src/filter-field/filter-field-examples.module.ts
> feat(filter-field): Add input to disable the whole filter field

- components/legend/README.md
- components/legend/src/legend.scss
> fix(legend): Fixes an issue with small spaces between legends.

- apps/barista/src/shared/scroll-spy.service.ts
- components/core/src/util/compare-util.spec.ts
- components/micro-chart/src/micro-chart.spec.ts
- components/tag/src/tag.scss
- components/theming/src/theme.ts
- libs/examples/src/cta-card/cta-card-closable-example/cta-card-closable-example.html
- libs/examples/src/drawer/drawer-nested-example/drawer-nested-example.html
- libs/examples/src/icon/icon-all-example/icon-all-example.scss
- libs/examples/src/select/select-complex-value-example/select-complex-value-example.html
- libs/examples/src/select/select-forms-example/select-forms-example.html
- libs/examples/src/select/select-value-example/select-value-example.html
- libs/examples/src/table/table-sorting-example/table-sorting-example.ts
- tools/barista/src/generators/category-navigation.ts
This PR fixes all currently open sonar bugs - https://sonarcloud.io/dashboard?id=dynatrace-oss_barista
> chore: Cleanup sonar bugs

- apps/components-e2e/src/components/chart/chart/chart.e2e.ts
- apps/components-e2e/src/components/chart/highcharts/chart-highcharts.e2e.ts
- apps/components-e2e/src/components/chart/pie-chart/pie-chart.e2e.ts
- apps/components-e2e/src/components/chart/selection-area/range/range.e2e.ts
- apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
- apps/components-e2e/src/components/chart/selection-area/timestamp/timestamp.e2e.ts
- apps/components-e2e/src/components/checkbox/checkbox.e2e.ts
- apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.e2e.ts
- apps/components-e2e/src/components/consumption/consumption.e2e.ts
- apps/components-e2e/src/components/drawer/drawer.e2e.ts
- apps/components-e2e/src/components/event-chart/event-chart.e2e.ts
- apps/components-e2e/src/components/expandable-panel/expandable-panel.e2e.ts
- apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
- apps/components-e2e/src/components/filter-field/filter-field.po.ts
- apps/components-e2e/src/components/highlight/highlight.e2e.ts
- apps/components-e2e/src/components/key-value-list/key-value-list.e2e.ts
- apps/components-e2e/src/components/overlay/overlay.e2e.ts
- apps/components-e2e/src/components/pagination/pagination.e2e.ts
- apps/components-e2e/src/components/progress-bar/progress-bar.e2e.ts
- apps/components-e2e/src/components/radio/radio.e2e.ts
- apps/components-e2e/src/components/show-more/show-more.e2e.ts
- apps/components-e2e/src/components/switch/switch.e2e.ts
- apps/components-e2e/src/components/tabs/tabs.e2e.ts
- apps/components-e2e/src/components/tree-table/tree-table.e2e.ts
- apps/components-e2e/src/utils/index.ts
- apps/components-e2e/src/utils/reset-window-to-default-size.ts
> test(filter-field): Fixes flaky e2e test by giving it more time to process.

- apps/barista/src/components/color-grid/color-grid.ts
<hr>
Added another input to the color-grid component, to be able to use this component in the cms.
> barista(color-grid): Added colorlist input to the color-grid.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 5.2.0 w/ changelog

- apps/barista/src/components/live-example/live-example.ts
Hupsi, was a little too eager with barista everywhere. it's still in the dynatrace-oss space 😄 
Other
> barista: Fix typo in stackblitz link

- .github/workflows/barista-preview.yml
- now-preview.json
I have added a now.json configuration to enable deep linking within the deployed previews. 
Other.
> chore: Fixes deep link routing in barista-previews.

- README.md
> Add contributors shield to our README.md.

- .github/workflows/barista-preview.yml
Fix zeit preview deployment, as it waited for an input that it never got.
Build chore
> chore: Confirm default options for preview deployment in interactive mode.

- components/chart/src/chart.scss
Only shows the crosshair cursor over the actual plot background and not
across the whole chart.
Fixes #609
Feature / Styling
> feat(chart): Show crosshair for selection area only over plot background.

- components/table/src/expandable/expandable-cell.scss
- libs/examples/src/table/table-expandable-rows-example/table-expandable-rows-example.html
- libs/examples/src/table/table-responsive-example/table-responsive-example.html
See the discussion in #540 for details on this one. We primarily move the details column in the examples to the left hand side of the table. 
Documentation
> chore(expandable-table): Move expandable cell to the left.

- components/event-chart/index.ts
- components/event-chart/src/event-chart.spec.ts
- components/event-chart/src/event-chart.ts
> fix(event-chart): Round time labels in x-axis

- apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
- apps/components-e2e/src/components/chart/selection-area/selection-area.html
- apps/components-e2e/src/components/chart/selection-area/selection-area.po.ts
- apps/components-e2e/src/components/chart/selection-area/selection-area.ts
- apps/dev/src/chart/chart-demo.component.html
- apps/dev/src/chart/chart-demo.component.ts
- components/chart/src/selection-area/selection-area.ts
> fix(chart): Fixes an issue with the overlay of the selection area not updating.

- components/event-chart/src/_event-chart-constants.scss
- components/event-chart/src/event-chart-legend.scss
- components/event-chart/src/event-chart.scss
- libs/examples/src/event-chart/event-chart-legend-example/event-chart-legend-example.html
Also change hover and selection colors
Closes #624
> fix(event-chart): Add legend color and pattern for filtered.

- apps/components-e2e/src/components/context-dialog/context-dialog.e2e.ts
- components/context-dialog/README.md
- components/context-dialog/src/context-dialog-module.ts
- components/context-dialog/src/context-dialog.html
- components/context-dialog/src/context-dialog.scss
- components/context-dialog/src/context-dialog.spec.ts
- components/context-dialog/src/context-dialog.ts
- components/context-dialog/src/footer/context-dialog-footer.html
- components/context-dialog/src/footer/context-dialog-footer.scss
- components/context-dialog/src/footer/context-dialog-footer.ts
- components/context-dialog/src/header/context-dialog-header.scss
- libs/examples/src/context-dialog/context-dialog-examples.module.ts
- libs/examples/src/context-dialog/context-dialog-footer-example/context-dialog-footer-example.html
- libs/examples/src/context-dialog/context-dialog-footer-example/context-dialog-footer-example.scss
- libs/examples/src/context-dialog/context-dialog-footer-example/context-dialog-footer-example.ts
Added a sticky footer for the context dialog, changed the content to be scrollable and reimplemented the closing button. Additionally added the possibility to provide an injection token, to overwrite certain configuration of the context dialog.
closes #322 
<hr>
> feat(context-dialog): Added footer to context dialog.

- documentation/getting-started.md
Updated the example-import and added the "old" manual installation guide again to have both options described.
Documentation update
> docs(getting-started): Add manual installation guide again.

- tools/barista/Dockerfile
> barista: Add missing dependencies to page builder

- apps/components-e2e/src/components/drawer/drawer.e2e.ts
- apps/components-e2e/src/components/drawer/drawer.html
- apps/components-e2e/src/components/drawer/drawer.scss
- apps/components-e2e/src/components/drawer/drawer.ts
- components/drawer/src/drawer-container.scss
- components/drawer/src/drawer.scss
Fixes #91 and a regression that was introduced by #605.
<hr>
guidelines.
> fix(drawer): Fixes an issue where drawer backdrop was overlaying the drawer body

- tools/release/src/stage-release/stage-release.ts
> chore(release): Fixes a wrong import in our stage relase script.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 6.0.0-rc.0 w/ changelog

- tools/linting/tsconfig.json
- tools/linting/tslint.json
> Fixes a regression where the lintrules where missing in the bundle

- CHANGELOG.md
- components/radial-chart/jest.config.js
- package-lock.json
- package.json
> chore: Bump version to 5.3.0 w/ changelog

- components/radial-chart/jest.config.js
> Fixes a regression in the jest config that was introduced with 5.3.0

- apps/components-e2e/src/components/radial-chart/radial-chart.e2e.ts
> Fixed flaky e2e tests for the radial chart.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 5.3.1 w/ changelog

- .github/CODEOWNERS
This PR updates the owners file with the new structure in the repository
> chore(owners): Updated code owners to new structure

- .circleci/config.yml
> ci: Fix the path of the store build artifacts.

- libs/tools/shareable-examples/src/templates/app.component.scss.template
- libs/tools/shareable-examples/src/templates/styles.scss.template
- libs/tools/shareable-examples/src/utils/get-template-and-style-files-from-component-source-file.ts
Detection of styleUrls and templateUrl in the decorators did not work correctly and are fixed with this change.
Documentation
> chore: Fixed the template and styleUrls detection for shareable-examples.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 6.0.0-rc.2 w/ changelog

- apps/barista-design-system/src/styles/layout/_page.scss
The page layout is currently a bit broken in Firefox. This PR should fix it.
Barista
> barista: Fix page layout template rows to also work in Firefox.

- libs/barista-components/radial-chart/README.md
- libs/barista-components/radial-chart/barista.json
Used the wrong closing tags which results into the page not being rendered correctly.
Barista
> barista: Fix radial chart readme examples.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 6.0.0 w/ changelog

- package-lock.json
- package.json
> chore: Remove unused nest dependencies.

- libs/barista-components/core/src/style/_colors.scss
- libs/barista-components/theming/src/colors.ts
> feat(colors): Add flat white to colors list

- apps/barista-design-system/src/components/live-example/live-example.html
- apps/barista-design-system/src/components/live-example/live-example.ts
> Improve stackblitz button and remove hide source to reduce noise

- environments/barista-environment.prod.ts
- environments/barista-environment.ts
Fixed the path to the shareable lib tooling. 
Chore
> chore: Fix path to shareable examples lib

- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
> fix(filter-field): Fixes same character filtering issue

- apps/components-e2e/src/app/app.routing.module.ts
- apps/components-e2e/src/components/empty-state/empty-state.e2e.ts
- apps/components-e2e/src/components/empty-state/empty-state.html
- apps/components-e2e/src/components/empty-state/empty-state.module.ts
- apps/components-e2e/src/components/empty-state/empty-state.po.ts
- apps/components-e2e/src/components/empty-state/empty-state.ts
- libs/barista-components/empty-state/src/empty-state.ts
- libs/barista-components/table/src/table.ts
- typings.d.ts
Uses the ResizeObserver to actively match the width of the emptyState component and adjust the layout accordingly. 
Feature
> feat(empty-state): Progressive enhancements for relayout based on ResizeObserver

- libs/barista-components/select/README.md
Added a ux snippet for our cms to provide a short introduction when to use the select component.
> docs: added ux snippet for select intro

- libs/tools/barista/src/transform.ts
> barista: Fix the match selector.

- libs/barista-components/schematics/jest.config.js
- package-lock.json
- package.json
- tsconfig.json
- Fix type inference issues by setting declaration to false in tsconfig
- Fix path serialization issues on windows by adding jest-serializer-path
Fixes #699
> build(windows): Fix Windows Build & Test issues

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/6.0.1

- apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
This should stabilize a flaky e2e test in the filter field
> chore(e2e): Fixes a flaky e2e test for the filter field.

- libs/examples/src/form-field/form-field-examples.module.ts
- libs/examples/src/form-field/form-field-server-validation/form-field-server-validation-example.html
- libs/examples/src/form-field/form-field-server-validation/form-field-server-validation-example.scss
- libs/examples/src/form-field/form-field-server-validation/form-field-server-validation-example.ts
- libs/examples/src/index.ts
> docs(form-field): Added server side form field validation example.

- libs/examples/src/cta-card/cta-card-closable-example/cta-card-closable-example.html
- libs/examples/src/cta-card/cta-card-default-example/cta-card-default-example.html
- libs/examples/src/empty-state/empty-state-default-example/empty-state-default-example.html
- libs/examples/src/empty-state/empty-state-in-card-example/empty-state-in-card-example.html
- libs/examples/src/empty-state/empty-state-multiple-items-example/empty-state-multiple-items-example.html
- libs/examples/src/empty-state/empty-state-multiple-items-in-card-example/empty-state-multiple-items-in-card-example.html
- libs/examples/src/icon/async-icon.ts
- libs/examples/src/icon/icon-all-example/async-icon.html
- libs/examples/src/icon/icon-all-example/async-icon.scss
- libs/examples/src/icon/icon-examples.module.ts
- libs/tools/shareable-examples/jest.config.js
- libs/tools/shareable-examples/src/generate-project.ts
- libs/tools/shareable-examples/src/templates/package-shareable-example.json.template
- libs/tools/shareable-examples/src/utils/get-relative-imports-from-source-file.ts
Fixed some issues with the generation of stackblitz examples and parts of the generation.
Chore
> chore: Fixes the generation of stackblitz examples after the angular 9 upgrade

- libs/barista-components/event-chart/src/event-chart.scss
> barista: Modifying overlay rule for avoiding conflicts with CDK's.

- .github/CODEOWNERS
To speed up the process of approving PRs I added myself back to the root code owners file
> chore: Add ffriedl89 to root code owners.

- apps/dev/src/formatters/formatters-demo.component.html
- libs/barista-components/formatters/README.md
- libs/barista-components/formatters/index.ts
- libs/barista-components/formatters/src/duration/duration-formatter-constants.ts
- libs/barista-components/formatters/src/duration/duration-formatter-utils/convert-to-milliseconds.ts
- libs/barista-components/formatters/src/duration/duration-formatter-utils/index.ts
- libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result-precise.ts
- libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result.ts
- libs/barista-components/formatters/src/duration/duration-formatter.ts
- libs/barista-components/formatters/src/duration/duration-functions-tests/convert-to-milliseconds.spec.ts
- libs/barista-components/formatters/src/duration/duration-functions-tests/transform-result-precise.spec.ts
- libs/barista-components/formatters/src/duration/duration-functions-tests/transform-result.spec.ts
- libs/barista-components/formatters/src/duration/duration.spec.ts
- libs/barista-components/formatters/src/duration/duration.ts
- libs/barista-components/formatters/src/formatted-value.ts
- libs/barista-components/formatters/src/formatters-module.ts
- libs/barista-components/formatters/src/rate/rate-formatter.ts
- libs/examples/src/formatters/formatters-duration-example/formatters-duration-example.html
- libs/examples/src/formatters/formatters-duration-example/formatters-duration-example.ts
- libs/examples/src/formatters/formatters-examples.module.ts
Adds the duration formatter.
See https://github.com/dynatrace-oss/barista/issues/444 for the feature list.
> feat(duration-formatter): Adds dtDuration pipe to format time durations

- apps/barista-design-system/src/app/components/footer/footer.html
This fixes an outdated link in the footer - thx @danielkhan for mentioning it.
> barista: Fixes an outdated link in the footer

- .github/CODEOWNERS
- libs/barista-components/alert/barista.json
- libs/barista-components/card/barista.json
- libs/barista-components/expandable-panel/barista.json
- libs/barista-components/expandable-section/barista.json
- libs/barista-components/info-group/barista.json
- libs/barista-components/radial-chart/barista.json
- libs/barista-components/show-more/barista.json
- libs/barista-components/switch/barista.json
- libs/barista-components/table/barista.json
- libs/barista-components/tile/barista.json
Removed and replaced my code ownership for components and Barista. In some cases I also aligned the owners-file with the metadata for the pages in the design system.
Please check if you agree with the changes. If not I'm open for any suggestions.
> chore: Removed my code ownership.

- libs/examples/src/index.ts
- libs/examples/src/input/index.ts
- libs/examples/src/input/input-examples.module.ts
- libs/examples/src/input/input-optional-example/input-optional-example.html
- libs/examples/src/input/input-optional-example/input-optional-example.ts
Added an component-example for the optional watermark in our inputs combine with an input example.
> docs(input): Added example for optional input.

- .github/CODEOWNERS
- libs/barista-components/alert/barista.json
Another small code ownership update, because Nina shouldn't be the only code owner for any component.
> chore: Update code owners for alert component.

- libs/barista-components/top-bar-navigation/src/top-bar-navigation.scss
- libs/barista-components/top-bar-navigation/src/top-bar-navigation.spec.ts
- libs/barista-components/top-bar-navigation/src/top-bar-navigation.ts
> fix(top-bar-navigation): Highlight top bar actions with keyboard focus.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 6.1.0 w/ changelog

- package.json
Adjusts browserslist in package json to correct values 
Closes #774
> chore: browserslist update

- angular.json
- apps/barista-design-system/src/app/app.module.ts
- apps/barista-design-system/src/app/components/nav/nav.html
- apps/barista-design-system/src/app/components/nav/nav.scss
- apps/barista-design-system/src/app/components/nav/nav.ts
- apps/barista-design-system/src/app/components/search/index.ts
- apps/barista-design-system/src/app/components/search/search.html
- apps/barista-design-system/src/app/components/search/search.scss
- apps/barista-design-system/src/app/components/search/search.ts
- apps/barista-design-system/src/environments/environment.internal.ts
- apps/barista-design-system/src/environments/environment.public.ts
- apps/barista-design-system/src/environments/environment.ts
- apps/barista-design-system/src/shared/services/search.service.ts
Adds frontend service for internal search engine in barista.
Fixes #680
Documentation
> barista: Add internal search to barista.

- .github/workflows/slack-release-notifier.yml
- tools/slack-release-notifier/.dockerignore
- tools/slack-release-notifier/.gitignore
- tools/slack-release-notifier/Dockerfile
- tools/slack-release-notifier/entrypoint.sh
- tools/slack-release-notifier/package-lock.json
- tools/slack-release-notifier/package.json
- tools/slack-release-notifier/src/main.ts
- tools/slack-release-notifier/src/utils/convert-to-mrkdwn.ts
- tools/slack-release-notifier/src/utils/fancify-text.ts
- tools/slack-release-notifier/src/utils/release-type.ts
- tools/slack-release-notifier/tsconfig.json
- tools/slack-release-notifier/tslint.json
Adds a GitHub Action for automatically sending Slack messages when a new release is published (closes #785)
> ci(slack-release-notifier): Send automatic Slack notifications on release

- .deployment/k8s-barista-builder/Dockerfile
- .deployment/k8s-barista-builder/Jenkinsfile
Build the k8s-barista-builder Docker image that is used as Jenkins agent for the barista design system build.
The job will be triggered periodically on the Jenkins. It will fetch the latest version of the workspace-base that is built on our circleci.
> ci: Build the k8s-barista-builder on the internal jenkins.

- angular.json
> barista: Fix recursion in production internal build target.

- documentation/getting-started.md
> docs(getting-started): Add a prototype section

- CHANGELOG.md
- package-lock.json
- package.json
Bump version to 6.2 incl changelog
> Release stage/6.2.0

- .github/workflows/slack-barista-production-promotion.yml
> ci: Make gorilla more chill

- libs/tools/barista/src/builder/homepage.ts
- libs/tools/barista/src/main.ts
> barista: Fixes an issue where the overview pages where not built.

- .deployment/entrypoint.sh
- .github/workflows/barista-preview.yml
The sha1sum built in compare function was behaving odd on the github action so we replaced it with a good old string compare.
<hr>
guidelines.
Please choose the type appropriate …
> ci: Use string compare instead of the built in sha1sum compare.

- libs/examples/src/index.ts
Updated generated module and index barrel file for the examples, as they were out of sync. 
Other
> chore: Update generated examples files to include all expamples

- libs/barista-components/filter-field/src/filter-field.ts
To ensure that only one filterfield flap is open at the same time, we need to store
the instance of the open flap in a global / module scope. If another filter field is focussed,
it should close the panels of the currently opened one and then reassign itself into the
open position.
Fixes #840
Bugfix
> fix(filter-field): Fixes an issue where two filterfield flaps were open at the same time.

- apps/barista-design-system/src/components/live-example/live-example.html
barista: Fix sonar violation for link rel not containing noreferrer
> barista: Fix sonar violation for link rel not containing noreferrer

- concepts/design-tokens/README.md
- concepts/web-components/README.md
This pull request should be considered the start of the discussion about the introduction of design-tokens and web-components into barista. Please feel free to comment, contribute and discuss here. 
This is the beginning of this conversation.
> chore: Added concepts for design tokens and web components.

- libs/barista-components/filter-field/src/filter-field.spec.ts
Grouped the zone calls into a single function and simplified the click a specific option
call.
Fixes #838
Refactor
> refactor(filter-field): Refactored the tests to contain less repitition.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 6.3.0 w/ changelog

- libs/shared/design-tokens/generated/global/palette.scss
- libs/shared/design-tokens/generated/global/spacing.scss
- libs/shared/design-tokens/generated/index.ts
- libs/shared/design-tokens/generated/patterns/button.scss
- libs/workspace/src/builders/design-tokens/build/build.ts
- libs/workspace/src/builders/design-tokens/build/token-converters/ts-barrel-file-template.ts
Adds generation of a barrel file for design tokens, required for import with the alias in `tsconfig.json`
Other
> chore: Add barrel file generation to design tokens build

- libs/barista-components/slider/src/slider.ts
Add the necessary preventDefault.
> fix(slider): Prevent default behavior of keyboard events associated with the slider.

- .deployment/barista/Jenkinsfile
- .deployment/k8s-barista-builder/Dockerfile
- .github/workflows/barista-preview.yml
- .gitignore
- environments/barista-environment.ci.ts
- now.json
Fixes #877
Added the public deployment on our Jenkins as well and reuse the configuration for the zeit deployment of the preview builds.
<hr>
guidelines.
Please choose the type …
> ci: Add public deployment of barista on Jenkins.

- angular.json
- apps/barista-design-system/src/app/app.routing.module.ts
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node-navigation/ba-decision-graph-node-navigation.html
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node-navigation/ba-decision-graph-node-navigation.scss
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node-navigation/ba-decision-graph-node-navigation.ts
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.html
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.scss
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.ts
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-start-node/ba-decision-graph-start-node.html
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph-start-node/ba-decision-graph-start-node.scss
- apps/barista-design-system/src/components/ba-decision-graph/ba-decision-graph.scss
- apps/barista-design-system/src/pages/decision-graph-page/decision-graph-page.html
- apps/barista-design-system/src/pages/decision-graph-page/decision-graph-page.module.ts
- apps/barista-design-system/src/pages/decision-graph-page/decision-graph-page.scss
- apps/barista-design-system/src/pages/decision-graph-page/decision-graph-page.ts
- apps/barista-design-system/src/pages/decision-graph-page/page-content.ts
Version 1 of **styles** for the UX Decision graph
logic: #875
> UX Decision-Graph (styling)

- libs/tools/barista/src/utils/fetch-strapi-content.ts
Fixes a limit in the strapi query, which resulted in missing snippets.
Documentation
> barista: Fixes the limit for strapi list queries.

- libs/workspace/src/scripts/affected-args.spec.ts
- libs/workspace/src/scripts/affected-args.ts
Due to a regression that was introduced with updating octokit rest the scripts failed due to lacking test coverage.
<hr>
guidelines. …
> ci: Add tests for workspace scripts.

- angular.json
- apps/dev/src/app.module.ts
- apps/dev/src/devapp-routing.module.ts
- apps/dev/src/devapp.component.ts
- apps/dev/src/drawer-table/drawer-table-demo.component.html
- apps/dev/src/drawer-table/drawer-table-demo.component.ts
- apps/dev/src/dt-components.module.ts
- libs/barista-components/experimental/drawer-table/README.md
- libs/barista-components/experimental/drawer-table/barista.json
- libs/barista-components/experimental/drawer-table/index.ts
- libs/barista-components/experimental/drawer-table/jest.config.js
- libs/barista-components/experimental/drawer-table/package.json
- libs/barista-components/experimental/drawer-table/src/drawer-table-module.ts
- libs/barista-components/experimental/drawer-table/src/drawer-table.html
- libs/barista-components/experimental/drawer-table/src/drawer-table.scss
- libs/barista-components/experimental/drawer-table/src/drawer-table.spec.ts
- libs/barista-components/experimental/drawer-table/src/drawer-table.ts
- libs/barista-components/experimental/drawer-table/src/test-setup.ts
- libs/barista-components/experimental/drawer-table/tsconfig.json
- libs/barista-components/experimental/drawer-table/tsconfig.lib.json
- libs/barista-components/experimental/drawer-table/tsconfig.spec.json
- libs/barista-components/experimental/drawer-table/tslint.json
- libs/examples/src/drawer-table/drawer-table-default-example/drawer-table-default-example.html
- libs/examples/src/drawer-table/drawer-table-default-example/drawer-table-default-example.ts
- libs/examples/src/drawer-table/drawer-table-examples.module.ts
- libs/examples/src/drawer-table/index.ts
- libs/examples/src/examples.module.ts
- libs/examples/src/index.ts
- nx.json
- tsconfig.json
Closes #587
<hr>
The README of this component is not created yet. The pull request was marked as draft to get early feedback on this component
Closes #587 
> feat(drawer-table): Added drawer-table component and example demo page

- .snyk
Add ignore rule for lodash right now since it only affects lodash used on nodejs server environments.
> chore: Add snyk ignore for lodash

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 6.4.0 w/ changelog

- apps/demos/src/main.scss
- apps/dev/src/main.scss
Fixes an issue where scroll blocking did not work when the body was not expandable and had a fixed height set. 
Related #926 
Chore
> chore: The body should be expandable for scrollblocking to actually work

- libs/barista-components/context-dialog/README.md
> Fix confirmation-dialog openChanged typo to openChange in its readme

- CONTRIBUTING.md
Added a fork instruction to contributing.
> chore: Add fork instruction to contributing guide

- libs/barista-components/empty-state/src/empty-state.ts
Fixed an issue that ssr was broken for the empty state
> fix(empty-state): Fixed ssr-rendering for the empty-state component.

- .circleci/config.yml
- angular.json
- libs/barista-components/empty-state/src/empty-state.ts
- libs/examples/src/index.ts
- libs/workspace/src/scripts/run-parallel.ts
- libs/workspace/src/scripts/util/get-affected-projects.ts
- libs/workspace/src/scripts/util/group-by-dependencies.ts
- libs/workspace/src/scripts/util/index.ts
- libs/workspace/src/scripts/util/split-array-into-chunks.ts
- libs/workspace/tsconfig.spec.json
- libs/workspace/webpack.config.js
- nx.json
- package-lock.json
- package.json
> CI add parallelisation of jobs to reduce build time.

- libs/barista-components/package.json
Upgrade of the barista-icons peer dependency in the shipped library to a version above 5.0.0
Breaking change - consumers will need to upgrade their peer dependency of barista-icons package.
> chore: Update peer dependency of barista-icons to >5.0.0

- libs/barista-components/button/src/_button-theme.scss
- libs/barista-components/button/src/button.scss
- libs/barista-components/style/main.scss
- libs/barista-components/style/themes.scss
<hr>
Changes the theming of the button component so it works with custom properties.
This PR is part of #739  
> feat(button): Changed button theming to custom properties

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/6.5.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.0.0-rc.0 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/6.5.1

- CHANGELOG.md
- package-lock.json
- package.json
This bumps to the next rc version for 7.0.0
> chore: Bump version to 7.0.0-rc.1 w/ changelog

- libs/barista-components/radial-chart/src/radial-chart.html
- libs/barista-components/radial-chart/src/radial-chart.ts
- libs/barista-components/sunburst-chart/README.md
- libs/barista-components/sunburst-chart/src/sunburst-chart.html
- libs/barista-components/sunburst-chart/src/sunburst-chart.scss
- libs/barista-components/sunburst-chart/src/sunburst-chart.ts
- libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts
> fix(sunburst-chart,radial-chart): Fix css custom properties on template

- BUILD.bazel
- WORKSPACE
- libs/shared/node/BUILD.bazel
- libs/workspace/BUILD.bazel
- package-lock.json
- package.json
Use the officialy supported formatter and linter. Can be invoked via a Bazel target and is executed as a pre-commit hook
Fixes: #1003
<hr>
guidelines.
Please choose the type …
> chore(workspace): Add buildifier

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.0.0-rc.2 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 6.5.2 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.0.0-rc.3 w/ changelog

- .deployment/barista/barista-internal.Dockerfile
- libs/workspace/src/builders/barista-build/builder.spec.ts
- libs/workspace/src/builders/barista-build/builder.ts
- libs/workspace/src/builders/barista-build/renderer.spec.ts
- libs/workspace/src/builders/barista-build/renderer.ts
- libs/workspace/src/test-setup.ts
- package-lock.json
- package.json
Fixes #905
Fixes a problem where the index file was not generated propperly and therefore the server crashed on the healthcheck.
Added further tests to test the file renaming and rendering.
<hr>
guidelines.
- Docs have been added / …
> barista(builder): Fixes an issue with the index file generation.

- libs/workspace/src/builders/stylelint/read-files.ts
Co-authored-by: Thomas Heller <thomas.heller@dynatrace.com>
Fixes: https://github.com/dynatrace-oss/barista/issues/1024
> build(workspace): Fix affected linting on windows.

- angular.json
Fixes server ip binding for windows in accessibility tests. Thanks to @christian-fischer for the detailed investigation in #1038 
Fixes #1038
Other
> build(a11y): Fixes an issue with running accessibility tests on windows.

- libs/workspace/src/builders/barista-build/renderer.ts
> chore: Remove unused readFile reference

- libs/barista-components/card/src/_card-theme.scss
- libs/barista-components/card/src/card.scss
Adds custom properties to the breadcrumb component.
Fixes: #970
> feat(card): Changes styling to use custom properties

- libs/barista-components/bar-indicator/src/_bar-indicator-theme.scss
- libs/barista-components/bar-indicator/src/bar-indicator.scss
Changes bar indicator to use custom properties.
Fixes: #957
> feat(bar-indicator): Changes styling to use custom properties

- libs/barista-components/checkbox/src/_checkbox-theme.scss
- libs/barista-components/checkbox/src/checkbox.scss
Adds custom properties to the breadcrumb component.
Fixes: #971
> feat(checkbox): Changes styling to use custom properties

- libs/barista-components/filter-field/src/filter-field-default-data-source.ts
Fixes an issue, where the initial dataset was required by the newly enhanced typing changes.
Other
> chore(filter-field): Make initial datasource set optional again.

- apps/demos/src/barista-examples.a11y.ts
- libs/barista-components/filter-field/README.md
- libs/examples/src/filter-field/filter-field-examples.module.ts
- libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.html
- libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.ts
- libs/examples/src/filter-field/index.ts
- libs/examples/src/index.ts
I added a filter field example to the README which shows a validator use-case.
Fixes: #858
> barista docs - Filter Field validator example

- angular.json
- libs/workspace/builders.json
- libs/workspace/src/builders/design-tokens/dependency-tree/__snapshots__/dependency-graph.spec.ts.snap
- libs/workspace/src/builders/design-tokens/dependency-tree/add-component-dependencies.spec.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/add-component-dependencies.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/add-tokens-to-alias-dependencies.spec.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/add-tokens-to-alias-dependencies.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/build.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/dependency-graph.spec.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/dependency-graph.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/find-source-files.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/index.ts
- libs/workspace/src/builders/design-tokens/dependency-tree/schema.json
- libs/workspace/src/builders/design-tokens/dependency-tree/schema.ts
- libs/workspace/webpack.config.js
- package.json
Creates an initial set of dependency analysis for the design tokens.
Other
> build(design-tokens): Added dependency-tree analyzer and builder for design tokens.

- libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.ts
Changes only affect a fix for version 7+, do not cherry pick back
> chore(filter-field): Fix datasource in example is no longer generic

- libs/barista-components/package.json
Extend support for barista-icons up to version 7
Other
> chore: Extend support for barista-icons up to version 7

- apps/demos/src/barista-examples.a11y.ts
- apps/dev/src/filter-field/filter-field-demo.component.html
- apps/dev/src/filter-field/filter-field-demo.component.ts
- apps/dev/src/filter-field/testdata.ts
- libs/barista-components/experimental/quick-filter/src/quick-filter-default-data-source.ts
- libs/barista-components/experimental/quick-filter/src/state/reducer.spec.ts
- libs/barista-components/filter-field/README.md
- libs/barista-components/filter-field/src/filter-field-default-data-source.ts
- libs/barista-components/filter-field/src/filter-field-util.spec.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/types.ts
- libs/examples/src/filter-field/filter-field-examples.module.ts
- libs/examples/src/filter-field/filter-field-partial-example/filter-field-partial-example.html
- libs/examples/src/filter-field/filter-field-partial-example/filter-field-partial-example.ts
- libs/examples/src/filter-field/index.ts
- libs/examples/src/index.ts
> barista(filter-field): Add partial option.

- .prettierignore
- angular.json
- libs/barista-components/schematics/src/testing/workspace.ts
- libs/workspace/collection.json
- libs/workspace/src/schematics/dt-component-e2e/README.md
- libs/workspace/src/schematics/dt-component-e2e/__snapshots__/index.spec.ts.snap
- libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.e2e.ts
- libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.html
- libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.module.ts
- libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.po.ts
- libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.ts
- libs/workspace/src/schematics/dt-component-e2e/fixtures/alert.fixture.ts
- libs/workspace/src/schematics/dt-component-e2e/fixtures/app.routing.module.ts.fixture.ts
- libs/workspace/src/schematics/dt-component-e2e/index.spec.ts
- libs/workspace/src/schematics/dt-component-e2e/index.ts
- libs/workspace/src/schematics/dt-component-e2e/schema.json
- libs/workspace/src/schematics/dt-component-e2e/schema.ts
- libs/workspace/src/schematics/utils/ast-utils.ts
- libs/workspace/src/schematics/utils/change.ts
- libs/workspace/tsconfig.json
- libs/workspace/tsconfig.lib.json
- libs/workspace/webpack.config.js
- tools/schematics/utils/ast-utils.ts
Adding schematics to generate e2e components.
> chore(schematics): Dt e2e schematic

- apps/components-e2e/src/components/table-order/table.po.ts
Fix table drag e2e tests for edge.
Test
> test(table): Fixes an issue where drag table e2e tests did not work in edge.

- libs/barista-components/button/src/_button-theme.scss
that conflicted with visited link overrides.
> fix(button): Increases specificity for anchor button selectors

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.0.0 w/ changelog

- libs/tools/barista/src/generators/ux-decision-graph.ts
- libs/tools/barista/src/types.ts
Fix a problem with data access in the uxd graph.
Other
> chore: Fixes data accessor for ux decisiongraph nodes

- apps/barista-design-system/src/app/app.routing.module.ts
Fixes prerendering of the barista homepage
> barista: Fix prerendering for index page content.

- documentation/getting-started.md
> docs: fix typo in getting started code example

- libs/barista-components/info-group/README.md
> docs(info-group): Removes outdated `dt-info-group-content`

- apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.ts
- apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph.ts
- apps/design-tokens-ui/src/services/palette/palette-source.service.ts
- apps/dev/src/micro-chart/micro-chart-demo.component.ts
- libs/tools/linting/tslint-self.json
- libs/workspace/tslint.json
- tslint.json
Removes lodash imports and adds 'lodash' to banned imports
> chore: Remove lodash imports.

- libs/barista-components/button-group/src/_button-group-item-theme.scss
- libs/barista-components/button-group/src/button-group-item.scss
Changed the styling of the button-group component to work with custom properties. part of #1076
<hr>
> feat(button-group): Changed styling to custom properties.

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/7.0.1

- libs/workspace/collection.json
- libs/workspace/src/schematics/dt-component-dev/README.md
- libs/workspace/src/schematics/dt-component-dev/__snapshots__/index.spec.ts.snap
- libs/workspace/src/schematics/dt-component-dev/files/apps/dev/src/__name@dasherize__/__name@dasherize__-demo.component.html
- libs/workspace/src/schematics/dt-component-dev/files/apps/dev/src/__name@dasherize__/__name@dasherize__-demo.component.ts
- libs/workspace/src/schematics/dt-component-dev/fixtures/alert-demo.component.fixture
- libs/workspace/src/schematics/dt-component-dev/fixtures/app.module.ts.fixture
- libs/workspace/src/schematics/dt-component-dev/fixtures/devapp-routing.module.fixture
- libs/workspace/src/schematics/dt-component-dev/fixtures/devapp.component.ts.fixture
- libs/workspace/src/schematics/dt-component-dev/index.spec.ts
- libs/workspace/src/schematics/dt-component-dev/index.ts
- libs/workspace/src/schematics/dt-component-dev/schema.json
- libs/workspace/src/schematics/dt-component-dev/schema.ts
- libs/workspace/src/schematics/dt-component-e2e/README.md
- libs/workspace/src/schematics/dt-component-e2e/index.ts
- libs/workspace/src/schematics/utils/schematics-utils.ts
- libs/workspace/src/schematics/utils/test-utils.ts
- libs/workspace/webpack.config.js
Schematics to generate dev components.
Closes: https://github.com/dynatrace-oss/barista/issues/966
> feat(schematics): Add dev component creation.

- libs/barista-components/schematics/src/ng-add/__snapshots__/ng-add.spec.ts.snap
- libs/barista-components/schematics/src/ng-add/rules/update-ng-module-rule.ts
> chore: Add HttpClientModule when running ng-add schematic.

- .circleci/config.yml
> build: Add cache version environment variable to the cache

- libs/barista-components/formatters/src/formatted-value.ts
Enhance DtFormattedValue with formatted display unit, proposed in #1126
Feature
> feat(formatters): Exposed formatted display unit in DtFormattedValue.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.1.0 w/ changelog

- angular.json
- libs/shared/design-tokens/generated/aliases/base-color.alias.json
- libs/shared/design-tokens/generated/aliases/font.alias.json
- libs/shared/design-tokens/generated/aliases/palette.alias.json
- libs/shared/design-tokens/generated/aliases/spacing.alias.json
- libs/shared/design-tokens/generated/aliases/typography.alias.json
- libs/workspace/src/builders/design-tokens/build/build.ts
- libs/workspace/src/builders/design-tokens/build/schema.json
- libs/workspace/src/builders/design-tokens/build/schema.ts
Changes the design tokens builder to build JSON files for alias files instead of hardcoding `palette-source.alias.yml`
> chore(design-tokens): Build additional metadata for consumption by the Design Tokens UI.

- apps/dev/src/radio/radio-demo.component.html
- libs/barista-components/radio/src/radio-group.ts
- libs/barista-components/radio/src/radio.html
- libs/barista-components/radio/src/radio.ts
Blocked until #1133 is merged
Fixes #1121
> radio: Added support for form-field

- libs/barista-components/package.json
> chore: Bump compatibility of barista-icons pack

- libs/barista-components/alert/src/_alert-theme.scss
- libs/barista-components/alert/src/alert.scss
Changed the styling of the alert component to work with custom properties. closes #956.
<hr>
> feat(alert): Changes styling to use custom properties.

- libs/barista-components/form-field/README.md
- libs/examples/src/form-field/form-field-examples.module.ts
- libs/examples/src/form-field/form-field-non-box-control-example/form-field-non-box-control-example.html
- libs/examples/src/form-field/form-field-non-box-control-example/form-field-non-box-control-example.ts
- libs/examples/src/form-field/index.ts
- libs/examples/src/index.ts
Added Sections for supported barista and custom controls.
> docs(form-field): Added Sections for supported barista and custom controls.

- angular.json
Angular CLI does not follow symlinks when resolving styles by default, with this flag it does.
Closes #1055 
Documentation
> barista: Fixes an issue with code highlighting in examples.

- libs/shared/design-tokens/generated/global/spacing.css
- libs/shared/design-tokens/generated/global/spacing.json
- libs/shared/design-tokens/generated/global/typography.css
- libs/shared/design-tokens/generated/global/typography.json
- libs/shared/design-tokens/generated/global/typography.scss
- libs/shared/design-tokens/src/lib/global/spacing.yml
- libs/shared/design-tokens/src/lib/global/typography.yml
- libs/workspace/src/builders/design-tokens/build/build.ts
- libs/workspace/src/builders/design-tokens/build/token-converters/dt-css-spacing.ts
- libs/workspace/src/builders/design-tokens/build/token-converters/index.ts
Added an css outlet for the spacing tokens, as described in #1057 
Other
> chore: Added spacing css outlet for design tokens

- .circleci/config.yml
- libs/tools/release/src/publish-release/publish-release.spec.ts
- libs/tools/release/src/utils/publish-package.spec.ts
- libs/workspace/src/builders/barista-build/renderer.spec.ts
- libs/workspace/src/builders/barista-build/utils/start-server.spec.ts
- libs/workspace/src/builders/typescript/index.ts
- libs/workspace/src/scripts/run-parallel.ts
As our contributions grow, we should at least make sure that our repo is installable, buildable and runnable on windows machines. 
Relates to #1043 
Other: build
> build: Add windows install, build and test checks

- .deployment/publish-next-packages/Jenkinsfile
- angular.json
- libs/tools/release/src/publish-release-next-cli.ts
- libs/tools/release/src/publish-release-next/index.ts
- libs/tools/release/src/publish-release-next/publish-release-next.ts
- libs/tools/release/src/utils/publish-package.ts
- libs/workspace/src/builders/design-tokens/package/build.ts
- libs/workspace/src/builders/design-tokens/package/schema.json
- libs/workspace/src/builders/design-tokens/package/schema.ts
- libs/workspace/src/builders/elements/build.ts
- libs/workspace/src/builders/elements/schema.json
- libs/workspace/src/utils/copy-root-package-json.ts
- package.json
Release script and pipeline for next parts in alpha mode.
Other
> build: Add jenkinsfile for next release

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/7.2.0

- apps/demos/src/barista-examples.a11y.ts
- libs/fluid-elements/jest.config.js
- libs/testing/custom-element/jest.config.js
- libs/workspace/src/scripts/run-parallel.ts
> chore: Rename list variables

- angular.json
- libs/workspace/builders.json
- libs/workspace/src/builders/design-tokens/package/build.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/build.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/index.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/schema.json
- libs/workspace/src/builders/design-tokens/tailwindcss/schema.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-color-group-config.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-font-config.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-spacing-config.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-tailwind-config.ts
- libs/workspace/webpack.config.js
- package-lock.json
- package.json
Added an additional output to the design-tokens output. It sources what we currently have in the
alias definitions and patches it into a tailwindcss configuration, which is then passed to the
tailwind generator.
It ouputs a css file that will be shipped with the design-tokens package and can be used standalone
without tailwindcss or postcss.
Fixes #1182
Other
> chore: Added tailwind output to design tokens generation.

- README.md
Fixes an outdated link in the readme
> chore(README): Fixes an outdated link

- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-color-group-config.spec.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-color-group-config.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-font-config.spec.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-font-config.ts
- libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-spacing-config.spec.ts
Some colors were including too many dashes.
Font-size and line-height base values were not correctly configured.
Other
> chore: Fixes an issue with the tailwind config generation.

- CONTRIBUTING.md
- tools/pull-request-labeler/src/interfaces/commit-message.ts
- tools/pull-request-labeler/src/utils/process-commit-messages.spec.ts
> chore: Add ds commit type for the design system

- .deployment/barista/Jenkinsfile
- .deployment/barista/nginx/sites-available/barista-internal.conf
> barista: Fixes an issue in the publish script.

- libs/workspace/collection.json
- libs/workspace/src/schematics/dt-component-example/README.md
- libs/workspace/src/schematics/dt-component-example/__snapshots__/index.spec.ts.snap
- libs/workspace/src/schematics/dt-component-example/files/__component@dasherize__-__name@dasherize__-example.html
- libs/workspace/src/schematics/dt-component-example/files/__component@dasherize__-__name@dasherize__-example.ts
- libs/workspace/src/schematics/dt-component-example/fixtures/index.ts.fixture
- libs/workspace/src/schematics/dt-component-example/fixtures/test-component-examples.module.ts.fixture
- libs/workspace/src/schematics/dt-component-example/index.spec.ts
- libs/workspace/src/schematics/dt-component-example/index.ts
- libs/workspace/src/schematics/dt-component-example/schema.json
- libs/workspace/src/schematics/dt-component-example/schema.ts
- libs/workspace/src/utils/common-utils.ts
- libs/workspace/webpack.config.js
This feature will allow the creation of barista example components, and the addition of new examples to already available components.
> feat(schematics): Add example component generation.

- .deployment/barista/Jenkinsfile
- .deployment/barista/nginx/sites-available/barista-internal.conf
> chore: Fixes nginx routing for the design-system app.

- libs/workspace/src/builders/affected-e2e/build.ts
> chore: Fixes an issue where tags were not defined for affected e2e.

- libs/barista-components/confirmation-dialog/src/confirmation-dialog-state/confirmation-dialog-state.scss
chore(confirmation-dialog) add top margin for .dt-confirmation-dialog-actions
Bugfix
- [x ] I have read the CONTRIBUTING doc and I follow the PR guidelines
> style(confirmation-dialog) add top margin for .dt-confirmation-dialog-actions

- .circleci/config.yml
Disabling windows test for now, as they use up a lot of credits.
Other
> chore: Disable windows tests.

- .deployment/barista/Jenkinsfile
- angular.json
- apps/next/src/app/app.module.ts
- libs/shared/data-access-strapi/src/lib/page.service.ts
Page service needs to be aware of the baseHref. 
Design-system
> ds: Fix baseHref for next apps

- package-lock.json
package-lock ran out of sync, this should fix it.
> chore: Fix package to lock file inconsistencies.

- libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
Sanitized missing custom properties in axis ticks
Removed extra spacing when bar mode and no label
> fix(stacked-series-chart): Sanitize axis ticks position

- apps/barista-design-system/src/styles/global/_base.scss
> ds: Fixes an issue with missing table styling.

- apps/dev/src/combobox/combobox-demo.component.html
- apps/dev/src/combobox/combobox-demo.component.ts
- libs/barista-components/experimental/combobox/index.ts
- libs/barista-components/experimental/combobox/src/combobox-module.ts
- libs/barista-components/experimental/combobox/src/combobox.html
- libs/barista-components/experimental/combobox/src/combobox.scss
- libs/barista-components/experimental/combobox/src/combobox.spec.ts
- libs/barista-components/experimental/combobox/src/combobox.ts
- libs/examples/src/combobox/combobox-examples.module.ts
- libs/examples/src/combobox/combobox-simple-example/combobox-simple-example.html
- libs/examples/src/combobox/combobox-simple-example/combobox-simple-example.ts
This reworks the combobox as an intermediate version. Fixes #1231
> Combobox issues

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/7.3.0

- .circleci/config.yml
- .deployment/workspace-bazel.Dockerfile
- package-lock.json
- tools/bazel_build_cache/setup_ci_build_cache.sh
> chore(ci): Parameterize Bazel version

- .dockerignore
- angular.json
- apps/next/src/app/app.module.ts
- apps/next/src/environments/environment.prod.ts
- apps/next/src/environments/environment.ts
Fixed up the deployment and sub routing. 
Documentation
> chore: Finally fix the routing for next

- libs/fluid-elements/checkbox/README.md
- libs/fluid-elements/checkbox/src/lib/checkbox.scss
- libs/fluid-elements/checkbox/src/lib/checkbox.ts
> chore(checkbox): Added custom property proxies.

- libs/barista-components/stacked-series-chart/barista.json
Small fix to prettify the title of the stacked series charts in the overview cards.
> docs: Prettify the title of the stacked series chart.

- angular.json
- apps/design-tokens-ui/src/app/app.component.html
- apps/design-tokens-ui/src/app/app.routing.module.ts
- apps/design-tokens-ui/src/app/components/nav/nav.component.scss
- apps/design-tokens-ui/src/pages/spacings/spacings.component.html
- apps/design-tokens-ui/src/pages/spacings/spacings.component.scss
- apps/design-tokens-ui/src/pages/spacings/spacings.component.ts
- apps/design-tokens-ui/src/pages/spacings/spacings.module.ts
- apps/design-tokens-ui/src/pages/themes/themes.module.ts
- apps/design-tokens-ui/src/services/palette/palette-source.service.ts
- apps/design-tokens-ui/src/services/spacing/index.ts
- apps/design-tokens-ui/src/services/spacing/spacing.service.ts
- apps/design-tokens-ui/src/services/stateful-service/index.ts
- apps/design-tokens-ui/src/services/stateful-service/stateful.service.ts
- apps/design-tokens-ui/src/utils/download.ts
- libs/shared/design-system/interfaces/src/lib/design-tokens-definitions.ts
- package-lock.json
Pull Request
Allows editing spacing in the design tokens UI. Since the spacing design tokens are compiled as constants in SCSS instead of custom properties, changes don't get applied to the UI itself in this version.
Depends on #1125.
Checklist
I have read the CONTRIBUTING doc and I follow the PR guidelines
Lint and unit tests pass locally with my changes
I have added tests that prove my fix is effective or that my feature works
I have added necessary documentation (if appropriate)
> chore(design-tokens-ui): Create section for spacings.

- angular.json
- apps/fluid-dev/src/app/app.component.html
- apps/fluid-dev/src/app/app.routing.module.ts
- apps/fluid-dev/src/pages/tab/tab-page.component.html
- apps/fluid-dev/src/pages/tab/tab-page.component.scss
- apps/fluid-dev/src/pages/tab/tab-page.component.ts
- apps/fluid-dev/src/pages/tab/tab-page.module.ts
- libs/fluid-elements/checkbox/src/lib/checkbox.spec.ts
- libs/fluid-elements/tab-group/.stylelintrc
- libs/fluid-elements/tab-group/BUILD.bazel
- libs/fluid-elements/tab-group/README.md
- libs/fluid-elements/tab-group/jest.config.js
- libs/fluid-elements/tab-group/src/index.ts
- libs/fluid-elements/tab-group/src/lib/tab-group.scss
- libs/fluid-elements/tab-group/src/lib/tab-group.spec.ts
- libs/fluid-elements/tab-group/src/lib/tab-group.ts
- libs/fluid-elements/tab-group/src/lib/tab/tab.scss
- libs/fluid-elements/tab-group/src/lib/tab/tab.spec.ts
- libs/fluid-elements/tab-group/src/lib/tab/tab.ts
- libs/fluid-elements/tab-group/src/utils/tab-events.ts
- libs/fluid-elements/tab-group/tsconfig.json
- libs/fluid-elements/tab-group/tsconfig.lib.json
- libs/fluid-elements/tab-group/tsconfig.spec.json
- libs/fluid-elements/tab-group/tslint.json
- nx.json
- package-lock.json
- tsconfig.json
Adds the fluid tab and tab-group components
_NOTE_: Some tests are missing concerning keyboard events/support. We need to add that in a later PR or maybe someone can help out.
> feat(tabs): Adds the tab and tab-group components as web components

- libs/barista-components/event-chart/src/event-chart.ts
It is already available in 7.x and will be fixed with the release of 7.4.0
> chore: Fixes an issue with the build, as the new formatter feature is not available yet

- libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts
> fix(sunburst-chart): Fixes an issue with missing types dependency.

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/7.4.0

- libs/barista-components/progress-bar/src/_progress-bar-theme.scss
- libs/barista-components/progress-bar/src/progress-bar.scss
- libs/barista-components/style/themes.scss
Additionally added a shared definition of the common colors.
Fixes #1056
Feature
> feat(progress-bar): Switched theming to custom properties.

- libs/barista-components/tile/src/_tile-theme.scss
- libs/barista-components/tile/src/tile.scss
<hr>
Changed the theming for the tile over to custom properties.
Part of #1076
> feat(tile): Switched theming to custom properties.

- apps/next/src/app/pages/error-page/error-page.module.ts
- apps/next/src/app/pages/index-page/index-page.module.ts
- nx.json
Cleans up unnecessary dependencies in the next and the fluid-dev apps.
Chore
> chore(next): Cleans up deps for next and fluid-dev

- angular.json
- apps/fluid-dev/src/app/app.component.html
- apps/fluid-dev/src/app/app.routing.module.ts
- apps/fluid-dev/src/pages/switch/switch-page.component.html
- apps/fluid-dev/src/pages/switch/switch-page.component.ts
- apps/fluid-dev/src/pages/switch/switch-page.module.ts
- libs/fluid-elements/switch/.stylelintrc
- libs/fluid-elements/switch/jest.config.js
- libs/fluid-elements/switch/src/index.ts
- libs/fluid-elements/switch/src/lib/switch-events.ts
- libs/fluid-elements/switch/src/lib/switch.scss
- libs/fluid-elements/switch/src/lib/switch.spec.ts
- libs/fluid-elements/switch/src/lib/switch.ts
- libs/fluid-elements/switch/tsconfig.json
- libs/fluid-elements/switch/tsconfig.lib.json
- libs/fluid-elements/switch/tsconfig.spec.json
- libs/fluid-elements/switch/tslint.json
- nx.json
- tsconfig.json
Co-authored-by: Rowa Audil <rowa.audil@dynatrace.com>
Fluid Switch Component.
Fixes #1222
> chore(switch): Implementation of the fluid switch component.

- libs/workspace/src/builders/affected-e2e/build.ts
Whoops, when no components are affected, the e2e tests failed... 
My bad.
Build fix
> build(e2e): Fixes an issue where the affected-e2e failed, when no components were affected.

- apps/next/src/app/components/nav/nav.ts
Fixes the page service import in the next apps nav component.
Slipped through ..
> fix(next): Fixes the page service import in the next apps nav component

- apps/next/src/app/pages/single-page/single-page.html
- apps/next/src/app/pages/single-page/single-page.module.ts
- apps/next/src/app/pages/single-page/single-page.scss
- apps/next/src/app/pages/single-page/single-page.ts
- apps/next/src/styles.scss
- apps/next/tsconfig.app.json
- nx.json
Adding some basic styling to the next app.
Renames the BaPageService to DsPageService.
Fixes: #1210
> Next(content): Mock Overview content

- libs/barista-components/indicator/BUILD.bazel
- libs/barista-components/style/BUILD.bazel
The theming file was deleted but due to the rebase strategy it broke the build now.
<hr>
guidelines.
> Fixes an issue that was introduced through rebase strategy

- WORKSPACE
- package-lock.json
- package.json
> chore(bazel): Update rules_nodejs to version 2.0.0

- libs/barista-components/experimental/quick-filter/src/quick-filter.spec.ts
- libs/barista-components/experimental/quick-filter/src/quick-filter.ts
Fixes an expression changed after checked error that was thrown in the filter field.
Thank you @areknow for pointing that out and helping us investigate.
Fixes #1305
Bugfix
> fix(quick-filter): Fixes an issue where an ECAC error was thrown.

- apps/dev/src/table/table-demo.component.html
- apps/dev/src/table/table-demo.component.ts
- libs/barista-components/checkbox/src/checkbox.ts
- libs/barista-components/table/README.md
- libs/barista-components/table/index.ts
- libs/barista-components/table/src/expandable/expandable-row.ts
- libs/barista-components/table/src/selection/index.ts
- libs/barista-components/table/src/selection/selection.ts
- libs/barista-components/table/src/selection/selector.spec.ts
- libs/barista-components/table/src/selection/selectors.scss
- libs/barista-components/table/src/selection/selectors.ts
- libs/barista-components/table/src/table-data-source.spec.ts
- libs/barista-components/table/src/table-data-source.ts
- libs/barista-components/table/src/table-module.ts
- libs/barista-components/table/src/table.ts
- libs/examples/src/index.ts
- libs/examples/src/table/index.ts
- libs/examples/src/table/table-examples.module.ts
- libs/examples/src/table/table-selection-example/table-selection-example.css
- libs/examples/src/table/table-selection-example/table-selection-example.html
- libs/examples/src/table/table-selection-example/table-selection-example.ts
<hr>
Early and rough draft for a checkbox column and respective selection handling in the table data source
> feat(checkbox-table): Add checkbox column and selection handling

- libs/barista-components/chart/src/heatfield/_chart-heatfield-theme.scss
- libs/barista-components/chart/src/heatfield/chart-heatfield.scss
Changed the theming of the chart heatfield to custom properties. Part of #1076 .
<hr>
> chart(theming): Changed chart heatfield theming to custom properties.

- libs/barista-components/progress-circle/src/_progress-circle-theme.scss
- libs/barista-components/progress-circle/src/progress-circle.scss
Switched theming to custom properties.
Feature
> feat(progress-circle): Switched theming to custom properties.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.5.0 w/ changelog

- libs/examples/src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts
The generator was not able to resolve the alias to testing fixtures, which broke the example.
Other
> chore(quick-filter): Fixes the example in stackblitz.

- libs/barista-components/style/themes.scss
> fix(theming): Fixes an issue where custom properties were not set to default.

- package-lock.json
- package.json
Remove unused dependency
Other
> chore: Remove extract loader dependency

- CHANGELOG.md
- package-lock.json
- package.json
Version bump and 7.5.1 release
> chore: Bump version to 7.5.1 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.6.0 w/ changelog

- .deployment/barista/Jenkinsfile
Send slack notification when build fails of barista outlet
Other
> chore: Send slack notification when barista build fails.

- .prettierignore
- documentation/linting.md
- libs/tools/linting/src/test/rules/dt-button-no-empty-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-card-direct-children-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-card-needs-title-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-card-no-empty-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-context-dialog-alt-text-rule/test.ts.lint
- libs/tools/linting/src/test/rules/dt-icon-button-alt-text-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-icon-button-needs-icon-rule/test.ts.lint
- libs/tools/linting/src/test/rules/dt-icon-button-needs-icon-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-inline-editor-alt-text-rule/test.ts.lint
- libs/tools/linting/src/test/rules/dt-nested-button-is-icon-button-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tab-content-no-empty-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tab-group-requires-tabs-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tab-label-no-empty-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tab-requires-content-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tab-requires-label-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tile-direct-children-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tile-icon-needs-icon-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tile-needs-icon-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tile-needs-title-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-tile-no-empty-rule/tslint.json
- libs/tools/linting/src/test/rules/dt-toggle-button-group-item-is-button-rule/test.ts.lint
- package.json
Since failing tslint rules appeared today, I had a look and had to fix some issues to make them testable again in our current lib setup. 
I've split up the work into multiple commits to properly group the changes. I can rebase and squash them once you've done your review.
> Chore linting fixes

- apps/next/src/app/pages/single-page/components/sidenav/sidenav.scss
- apps/next/src/app/styles/_page.scss
> chore: Fix scss import paths in next app temporarily.

- tsconfig.base.json
The affected arguments calculation needs a tsconfig.base.json on the base branch (master) to run on the v10 branch. This file is needed for the typescript solutions.
If this file is not in the base branch then it will fail with the following error.
**This file is a renamed copy of the `tsconfig.json`**
<hr>
guidelines.
- The commit message follows our …
> chore: This is a preparation commit for v10.

- libs/barista-components/filter-field/README.md
- libs/barista-components/filter-field/index.ts
- libs/barista-components/filter-field/src/filter-field-config.ts
- libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.spec.ts
- libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
- libs/barista-components/filter-field/src/filter-field-util.spec.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/types.ts
- libs/examples/src/filter-field/filter-field-custom-parser-example/filter-field-custom-parser-example.html
- libs/examples/src/filter-field/filter-field-custom-parser-example/filter-field-custom-parser-example.ts
- libs/examples/src/filter-field/filter-field-examples.module.ts
- libs/examples/src/filter-field/index.ts
- libs/examples/src/index.ts
This PR addresses issue https://github.com/dynatrace-oss/barista/issues/1113.
Feature
> feat(filter-field): Added config for user defined tag parser function

- .deployment/publish-next-packages/Jenkinsfile
- libs/workspace/src/builders/elements/package-all-elements/build.ts
- libs/workspace/src/builders/elements/package/build.ts
This fixes the packaging until the fluid elements will be bazelified as one of the next steps. 
Other
> chore: Fixes an issue where the package version was not propagated to the package.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 7.7.0 w/ changelog

- apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.spec.ts
- apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.ts
Fixes a test that expects to throw an error. It logged the error instead of actually testing if the error was thrown.
Fixes #1414
> fix(decision-graph): Fixes a test expecting an error.

- libs/barista-components/schematics/migrations.json
- libs/barista-components/schematics/src/interfaces/index.ts
- libs/barista-components/schematics/src/migrations/update-8-0-0/rules/index.ts
- libs/barista-components/schematics/src/migrations/update-8-0-0/rules/update-dependencies.rule.ts
- libs/barista-components/schematics/src/migrations/update-8-0-0/update-8-0-0.spec.ts
- libs/barista-components/schematics/src/migrations/update-8-0-0/update-8-0-0.ts
- libs/barista-components/schematics/src/utils/json/update-dependency.ts
Add migration script to automate the updating to version 8 of the barista components.
<hr>
guidelines.
> feat(schematics): Add ng-update schematics for version 8.

- libs/barista-components/sunburst-chart/src/sunburst-chart.ts
BREAKING CHANGE: Make constructor parameters required.
<hr>
guidelines.
> feat(sunburst-chart): Update deprecated constructor.

- libs/barista-components/checkbox/src/checkbox.ts
- libs/barista-components/form-field/src/form-field-control.ts
- libs/barista-components/form-field/src/form-field-module.ts
- libs/barista-components/radio/src/radio-group.ts
- libs/barista-components/switch/src/switch.ts
> Implement breaking changes for 8.0.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.0.0-rc.0 w/ changelog

- angular.json
- libs/shared/design-system/interfaces/src/lib/barista/barista-definitions.ts
- libs/tools/barista/src/fixtures/toc.ts
- libs/tools/barista/src/transform.spec.ts
- libs/tools/barista/src/transform.ts
- libs/tools/barista/tsconfig.json
- libs/tools/barista/tsconfig.lib.json
Fixes an issue where the barista content generation broke the barista build.
Fixes #1469
<hr>
guidelines.
> ds: Fix broken toc generation.

- libs/barista-components/expandable-text/BUILD.bazel
- package-lock.json
Added the dependencies that I missed during review of #1473 
<hr>
guidelines.
> build(expandable-text): Fix missing bazel dependencies on compile.

- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.scss
- libs/barista-components/filter-field/src/filter-field.ts
> fix(filter-field): Fixes an issue with overflowing suggestions.

- apps/fluid-dev/src/pages/tab/tab-page.component.html
- apps/fluid-dev/src/pages/tab/tab-page.component.ts
- libs/fluid-elements/tab-group/src/lib/tab-events.ts
- libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.spec.ts
- libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.ts
- libs/fluid-elements/tab-group/src/lib/tab/tab.spec.ts
- libs/fluid-elements/tab-group/src/lib/tab/tab.ts
Fixes a few bugs for the focus styling of the tabs. Specifically when clicking or removing a focused tab.
fixes: #1319 
> fix(tab): Focus bug fixes

- package-lock.json
- package.json
> chore: Bump @bazel/typescript to the matching version of the workspace.

- libs/fluid-elements/switch/src/lib/switch.spec.ts
- libs/fluid-elements/switch/src/lib/switch.ts
Adds aria support for the switch
fixes #1487
> chore: Adds aria support for the switch

- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
fix(filter-field): Fixes an issue where the user can interact while in loading state.
Fixes #1464
> fix(filter-field): Fixes an issue where the user can interact while in loading state.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.0.0-rc.1 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.0.0 w/ changelog

- libs/fluid-elements/tab-group/src/lib/tab-events.ts
- libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.spec.ts
- libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.ts
- libs/fluid-elements/tab-group/src/lib/tab/tab.spec.ts
- libs/fluid-elements/tab-group/src/lib/tab/tab.ts
Adds aria support for the tab and tab group
fixes #1486
> chore: Adds aria support for the tab and tab-group

- angular.json
- libs/fluid-elements/button/BUILD.bazel
- libs/fluid-elements/button/jest.config.js
- libs/fluid-elements/button/jest.config.json
- package-lock.json
- package.json
- tools/bazel_rules/jest/BUILD.bazel
- tools/bazel_rules/jest/babel.config.js
- tools/bazel_rules/jest/jest-resolver.js
- tools/bazel_rules/jest/jest-runner.js
- tools/bazel_rules/jest/jest_macro.bzl
Tests are now passing ✅
<hr>
guidelines.
> build(fluid-button): Add jest tests for fluid button

- angular.json
- libs/fluid-elements/checkbox/BUILD.bazel
- libs/shared/keycodes/BUILD.bazel
- libs/shared/keycodes/index.ts
- libs/workspace/src/builders/elements/package/build.ts
- tsconfig.base.json
Builds the fluid-checkbox with Bazel.
Build
> build(fluid-checkbox): Bazelify fluid-checkbox

- .deployment/barista/internal/Jenkinsfile
- .deployment/barista/public/Jenkinsfile
- environments/barista-environment.ts
> ds: Use installed instead of checked-out icons as icon-page source

- .bazelrc
> ci: Update bazelrc flags

- DEVELOPMENT.md
Add guide on what is needed to get started with developing on windows.
<hr>
guidelines.
> docs: Improve the local dev setup section.

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/8.0.1

- libs/barista-components/drawer/README.md
> docs(drawer): Added information about collapsing into overlay mode if the drawer is less than 1024 pixels wide.

- libs/barista-components/experimental/combobox/src/combobox.ts
Attempting to fix the combobox reset behavior, with controlling the initialization and programmatic value setting.
Special thanks to @heartdisease for helping to come up with this solution.
Fixes: #1427
> [combobox] Attempt to fix combobox

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.0.2 w/ changelog

- .deployment/design-tokens-ui/vercel.json
- .github/.bazelrc
- .github/workflows/design-tokens-ui.yml
Fixes #1429
The URL with the deployment is: https://design-tokens-ui.vercel.app/
<hr>
guidelines.
> ci(design-tokens-ui): Build and deploy Design Tokens UI with vercel.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.0.3 w/ changelog

- .buildkite/ami-setup.sh
- .buildkite/bazel.rc
- .buildkite/environment
- .buildkite/test.sh
- WORKSPACE
> Speedup build 

- apps/dev/src/alert/alert-demo.component.html
- apps/dev/src/alert/alert-demo.component.scss
- libs/barista-components/alert/README.md
- libs/barista-components/alert/src/_alert-theme.scss
- libs/barista-components/alert/src/alert.html
- libs/barista-components/alert/src/alert.ts
- libs/examples/src/alert/alert-interactive-example/alert-interactive-example.html
> feat(alert): Introduce `info` severity type.

- .circleci/config.yml
- angular.json
- apps/fluid-dev/src/app/app.component.html
- apps/fluid-dev/src/app/app.routing.module.ts
- apps/fluid-dev/src/pages/popover/popover-page.component.html
- apps/fluid-dev/src/pages/popover/popover-page.component.scss
- apps/fluid-dev/src/pages/popover/popover-page.component.ts
- apps/fluid-dev/src/pages/popover/popover-page.module.ts
- libs/fluid-elements/popover/BUILD.bazel
- libs/fluid-elements/popover/README.md
- libs/fluid-elements/popover/jest.config.json
- libs/fluid-elements/popover/package.json
- libs/fluid-elements/popover/src/index.ts
- libs/fluid-elements/popover/src/lib/popover.spec.ts
- libs/fluid-elements/popover/src/lib/popover.ts
- libs/fluid-elements/popover/tsconfig.json
- libs/fluid-elements/popover/tsconfig.lib.json
- libs/fluid-elements/popover/tsconfig.spec.json
- libs/fluid-elements/popover/tslint.json
- nx.json
- package-lock.json
- package.json
- tools/bazel_rules/jest/BUILD.bazel
- tools/bazel_rules/jest/jest-resolver.js
- tools/bazel_rules/jest/jest_macro.bzl
- tsconfig.base.json
Depends on #1565
More tests will follow...
> feat(fluid-popover): Introduce FluidPopover as WebComponent.

- apps/components-e2e/src/components/tree-table/tree-table.e2e.ts
- apps/components-e2e/src/components/tree-table/tree-table.po.ts
- apps/components-e2e/src/components/tree-table/tree-table.ts
- apps/dev/src/tree-table/tree-table-demo.component.ts
- libs/barista-components/tree-table/src/tree-table-row.scss
- libs/barista-components/tree-table/src/tree-table-toggle-cell.html
- libs/barista-components/tree-table/src/tree-table-toggle-cell.scss
Adds an e2e test for the tree-table overflow behavior from #1502
Took longer since I tried to fix it without hardcoding widths
see #1624 
fixes #1582 
> TreeTable e2e test

- libs/fluid-elements/popover/src/lib/popover.ts
> chore(fluid-popover): Remove max-height of fluid popover container.

- libs/fluid-elements/input/src/lib/input.styles.ts
> chore(fluid-input): Update fluid input padding and icon color.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.1.0 w/ changelog

- apps/dev/src/event-chart/big-time-test-data.ts
- apps/dev/src/event-chart/event-chart-demo.component.ts
- libs/barista-components/event-chart/src/event-chart.spec.ts
- libs/barista-components/event-chart/src/event-chart.ts
Show human readable time format if units are bigger than seconds
Closes #1674 
> fix(event-chart): Display human readable time

- angular.json
- apps/fluid-dev/src/app/app.component.html
- apps/fluid-dev/src/app/app.routing.module.ts
- apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.component.html
- apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.component.scss
- apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.component.ts
- apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.module.ts
- libs/fluid-elements/popover/src/lib/popover.ts
- libs/fluid-elements/virtual-scroll-container/BUILD.bazel
- libs/fluid-elements/virtual-scroll-container/README.md
- libs/fluid-elements/virtual-scroll-container/jest.config.json
- libs/fluid-elements/virtual-scroll-container/package.json
- libs/fluid-elements/virtual-scroll-container/src/index.ts
- libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-container.ts
- libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-events.ts
- libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-state.ts
- libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-utils.spec.ts
- libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-utils.ts
- libs/fluid-elements/virtual-scroll-container/tsconfig.json
- libs/fluid-elements/virtual-scroll-container/tsconfig.lib.json
- libs/fluid-elements/virtual-scroll-container/tsconfig.spec.json
- libs/fluid-elements/virtual-scroll-container/tslint.json
- nx.json
- tsconfig.base.json
Overall, the virtual scroll container is doing what it's supposed to do, although there are still a couple of issues left to tackle (fast scrolling, items with different height slightly jumping, more tests), but since the combo-box is relying on the virtual-scroll-container and we want to get a first version out, please take a look at the current state and let me know what you think.
> chore(fluid-virtual-scroll): Virtual scroll container as web-component.

- apps/components-e2e/src/components/chart/chart.module.ts
- apps/components-e2e/src/components/chart/heatfield/heatfield.e2e.ts
- apps/components-e2e/src/components/chart/heatfield/heatfield.html
- apps/components-e2e/src/components/chart/heatfield/heatfield.ts
- libs/barista-components/chart/src/chart.spec.ts
- libs/barista-components/chart/src/chart.ts
- libs/barista-components/chart/src/heatfield/chart-heatfield.ts
Fixes an issue where the heatfields could not be created dynamic.
Fixes #1580
<hr>
guidelines.
> fix(chart): Fix dynamic heatfield generation that was not possible.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.1.1 w/ changelog

- apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
- apps/components-e2e/src/components/quick-filter/quick-filter.module.ts
- apps/components-e2e/src/components/quick-filter/quick-filter.po.ts
- libs/barista-components/experimental/quick-filter/README.md
- libs/barista-components/experimental/quick-filter/src/quick-filter-default-data-source.ts
- libs/barista-components/experimental/quick-filter/src/quick-filter-group.html
- libs/barista-components/experimental/quick-filter/src/quick-filter-group.scss
- libs/barista-components/experimental/quick-filter/src/quick-filter-group.ts
- libs/barista-components/experimental/quick-filter/src/quick-filter.html
- libs/barista-components/experimental/quick-filter/src/quick-filter.module.ts
- libs/barista-components/experimental/quick-filter/src/quick-filter.scss
- libs/barista-components/experimental/quick-filter/src/quick-filter.ts
- libs/barista-components/experimental/quick-filter/src/state/actions.ts
- libs/barista-components/experimental/quick-filter/src/state/reducer.ts
- libs/barista-components/experimental/quick-filter/src/state/selectors.ts
- libs/barista-components/experimental/quick-filter/src/state/store.ts
- libs/examples/src/quick-filter/custom-show-more/custom-show-more.html
- libs/examples/src/quick-filter/custom-show-more/custom-show-more.ts
- libs/examples/src/quick-filter/index.ts
- libs/examples/src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts
- libs/examples/src/quick-filter/quick-filter-examples.module.ts
> feat(quick-filter): Add show more for options.

- README.md
> ci: Set build status for master branch

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.1.2 w/ changelog

- apps/components-e2e/src/components/radial-chart/radial-chart.e2e.ts
- apps/components-e2e/src/components/radial-chart/radial-chart.po.ts
- libs/barista-components/overlay/src/overlay-trigger.ts
- libs/barista-components/radial-chart/README.md
- libs/barista-components/radial-chart/src/radial-chart-path.html
- libs/barista-components/radial-chart/src/radial-chart-path.ts
- libs/barista-components/radial-chart/src/radial-chart-series.ts
- libs/barista-components/radial-chart/src/radial-chart.html
- libs/barista-components/radial-chart/src/radial-chart.scss
- libs/barista-components/radial-chart/src/radial-chart.ts
Bugfix
Closes #1478 
Add interaction to radial chart.
The legend now hides and shows the paths.
The selection is not affected. It could be in the future
> feat(radial-chart): Add interaction to legend

- .buildkite/baristaPipeline.yml
<hr>
This activates our windows build in CI. 
> ci: Build with bazel on windows

- libs/examples/src/tag/tag-removable-example/tag-removable-example.html
- libs/examples/src/tag/tag-removable-example/tag-removable-example.ts
Enhances the removable tag example with actual functionality to make the behaviour more understandable.
Documentation / other
> chore(tag): Adjust remove tag example to be more interactive.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.2.0 w/ changelog

- .deployment/barista/public/Jenkinsfile
- libs/tools/barista/src/main.ts
This fixes an issue that certain links were not properly removed.
> barista: Fix internal links not properly removed.

- libs/examples/src/tag/tag-interactive-example/tag-interactive-example.html
- libs/examples/src/tag/tag-interactive-example/tag-interactive-example.scss
- libs/examples/src/tag/tag-interactive-example/tag-interactive-example.ts
Make interactive example a bit more understandable (functional)
Fixes APM-266052
Documentation
> chore(tag): Make tag interactive example more understandable.

- .deployment/design-tokens-ui/vercel.json
- .github/workflows/design-tokens-ui.yml
Currently the deployment is working but it is failing on reporting the status. This change should fix the problem.
<hr>
guidelines. …
> build(design-tokens-ui): Fix design tokens UI reporting failing.

- Jenkinsfile
Trigger downstream examples build after release
Fixes #1586
Chore
> chore: Trigger examples build step after publishing.

- libs/examples/src/stepper/stepper-default-example/stepper-default-example.scss
- libs/examples/src/stepper/stepper-default-example/stepper-default-example.ts
Before: 
After: 
Documentation
> chore: Fix stepper example css.

- apps/components-e2e/src/components/filter-field/filter-field.po.ts
- apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
- apps/components-e2e/src/components/quick-filter/quick-filter.po.ts
- libs/barista-components/quick-filter/src/quick-filter.ts
- libs/barista-components/quick-filter/src/state/reducer.ts
> fix(quick-filter): Fixes an issue where free-text could not be set in a quick-filter environment.

- libs/barista-components/table/src/cell.ts
> fix(table): Fixes an issue with typescript 4 compatibility.

- libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result.ts
- libs/barista-components/formatters/src/duration/duration.spec.ts
- libs/examples/src/formatters/formatters-duration-example/formatters-duration-example.html
> fix(formatters): Fixes an issue with 0 edge-case in number format mode.

- BUILD.bazel
- angular.json
- environments/BUILD.bazel
- environments/barista-environment.ts
- libs/shared/data-access-strapi/BUILD.bazel
- libs/shared/data-access-strapi/index.ts
- libs/tools/barista/BUILD.bazel
- libs/tools/barista/README.md
- libs/tools/barista/jest.config.js
- libs/tools/barista/jest.config.json
- libs/tools/barista/src/builder/components.ts
- libs/tools/barista/src/generators/category-navigation.ts
- libs/tools/barista/src/generators/ds-navigation.ts
- libs/tools/barista/src/generators/ux-decision-graph.ts
- libs/tools/barista/src/main.ts
- libs/tools/barista/src/markdown-it-deflist.d.ts
- libs/tools/barista/src/utils/examples.ts
- tsconfig.base.json
> build(barista-tools): Build Barista Tools with Bazel

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.3.0 w/ changelog

- .deployment/barista/public/Jenkinsfile
> chore: Move to prod build for on demand.

- apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
- libs/barista-components/quick-filter/src/quick-filter.ts
- libs/testing/fixtures/src/lib/filter-field/test-data.ts
Similar fix to the one in #1788 
Fixes APM-267404
Bugfix
> fix(quick-filter): Fixes an issue where a range could not be set.

- apps/components-e2e/src/components/table/BUILD.bazel
- apps/components-e2e/src/components/table/table-simple/table-simple.html
- apps/components-e2e/src/components/table/table-simple/table-simple.ts
- apps/components-e2e/src/components/table/table.e2e.ts
- apps/components-e2e/src/components/table/table.module.ts
- apps/components-e2e/src/components/table/table.po.ts
- apps/dev/src/table/table-demo.component.html
- apps/dev/src/table/table-demo.component.ts
- libs/barista-components/table/src/table.html
Fixes APM-266048
<hr>
guidelines.
> feat(table): Don't show empty state while loading.

- apps/demos/src/app-routing.module.ts
- apps/demos/src/barista-examples.a11y.ts
- apps/demos/src/nav-items.ts
- libs/barista-components/select/README.md
- libs/barista-components/select/src/select-module.ts
- libs/barista-components/select/src/select-value-template.ts
- libs/barista-components/select/src/select.html
- libs/barista-components/select/src/select.spec.ts
- libs/barista-components/select/src/select.ts
- libs/examples/src/index.ts
- libs/examples/src/select/index.ts
- libs/examples/src/select/select-custom-value-template-example/select-custom-value-template-example.html
- libs/examples/src/select/select-custom-value-template-example/select-custom-value-template-example.ts
- libs/examples/src/select/select-examples.module.ts
<hr>
Closes [#1091](https://github.com/dynatrace-oss/barista/issues/1091)
- [ x ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ x ] Lint and unit tests pass locally with my changes
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added necessary documentation (if appropriate)
> feat(select): Allow custom template for selected value

- .deployment/barista/public/Jenkinsfile
- tools/scripts/internal-link-checker.js
Fixes APM-266099
Thank you @tomheller for the help on this issue!
> chore: Internal link check in jenkins pipeline

- apps/components-e2e/src/components/combobox/combobox.ts
Skip the flaky test for now, the combobox is still in experimental and we want to have a stable e2e pipeline right now. 
Other
> test(combobox): Skip flaky test in the combobox.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.4.0 w/ changelog

- .snyk
Adds exception since there is no upgrade or patch currently that we can easily apply. 
Non critical since we don't include this in our code and might be resolved with angular upgrade to version 11 which is planned for early december
> chore: Add snyk exception until upgrade to angular@^11

- .github/workflows/barista-preview.yml
Fixes preview deployments for barista branch previews
> barista: Fixes preview builds for branches.

- libs/barista-components/experimental/combobox/src/combobox.ts
When clicking another combobox dropdown arrow (which stopped the event propagation), the
autocomplete outside click was never triggered, preventing the blurred combobox from closing.
A similar solution as in the filter-field #849 was applied to this.
Fixes APM-269028
Bugfix
> fix(combobox): Fixes an issue where the combobox flap did not close.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.5.0 w/ changelog

- libs/barista-components/chart/README.md
- libs/barista-components/chart/index.ts
- libs/barista-components/chart/src/tooltip/chart-tooltip-position.ts
- libs/barista-components/chart/src/tooltip/chart-tooltip.ts
- libs/examples/src/chart/chart-bar-example/chart-bar-example.html
- libs/examples/src/chart/chart-bar-example/chart-bar-example.ts
Support for different scrolling behaviors in the dt chart tooltip.
proposal: APM-269634
Feature (non-breaking change which adds functionality
> feat(tooltip): support for custom positioner

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.6.0 w/ changelog

- .deployment/barista/public/Jenkinsfile
- libs/examples/src/event-chart/event-chart-overlapping-load-example/event-chart-overlapping-load-example.ts
- libs/examples/src/event-chart/event-chart-session-replay-example/event-chart-session-replay-example.ts
- tools/scripts/internal-link-checker.js
Fixed internal link checker
Documentation
> barista: Fix barista public publish.

- libs/barista-components/drawer/src/drawer.ts
- libs/barista-components/quick-filter/README.md
- libs/barista-components/quick-filter/src/quick-filter.html
- libs/barista-components/quick-filter/src/quick-filter.spec.ts
- libs/barista-components/quick-filter/src/quick-filter.ts
Expose APIs to interact with the drawer, see APM-270197
> feat(quick-filter): Expose APIs to interact with the drawer.

- apps/components-e2e/src/components/chart/heatfield/heatfield.e2e.ts
- libs/barista-components/chart/src/chart.ts
Heatfield no longer reacted to a resizing of the chart.
Bugfix
> fix(chart): Fixes an issue with the heatfield when resizing the chart.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.7.0 w/ changelog

- libs/barista-components/quick-filter/README.md
- libs/barista-components/quick-filter/src/quick-filter.html
- libs/barista-components/quick-filter/src/quick-filter.ts
> feat(quick-filter): Expose the filter-field loading through the quickfilter.

- libs/barista-components/checkbox/src/checkbox.scss
Added this as a standalone commit to avoid cherry-picking and still have it in the changelog.
Mentioned in #1852
> fix(checkbox): Removes outside spacing on the right of the label.

- libs/barista-components/table/src/table.ts
This one was a hard one. Thanks to @ffriedl89 and @thomaspink for all the help
APM-266086
Bugfix
> fix(table): Fixes an issue with a ViewContainer error on destroy.

- libs/barista-components/quick-filter/src/quick-filter.scss
Fixes two issues
* Adds truncation on labels for checkboxes and radios inside the quickfilter drawer
> Fix quickfilter overflowing

- apps/barista-design-system/src/app/app.module.ts
- apps/barista-design-system/src/app/components/search/index.ts
- apps/barista-design-system/src/app/components/search/search-result-item.html
- apps/barista-design-system/src/app/components/search/search-result-item.scss
- apps/barista-design-system/src/app/components/search/search-result-item.ts
- apps/barista-design-system/src/app/components/search/search.html
- apps/barista-design-system/src/app/components/search/search.scss
- apps/barista-design-system/src/app/components/search/search.ts
- apps/barista-design-system/src/shared/services/search.service.ts
- libs/shared/design-system/interfaces/src/lib/barista/barista-backend-api-definitions.ts
Adjusted to the new search backend. 
⚠️ Only merge after the search backend has been deployed!
Documentation
> barista: New search ui and adaption to new search endpoint.

- .vscode/extensions.json
Removed lit-plugin from vscode extension recommendations.
> chore: Removed lit-plugin from vscode extension recommendations.

- libs/barista-components/expandable-section/src/expandable-section.scss
- libs/barista-components/expandable-section/src/expandable-section.ts
> fix(expandable-section): Fixes an issue where nesting expandable sections resulted in wrong visual state.

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/8.8.0

- libs/barista-components/radial-chart/src/radial-chart-path.scss
Display a pointer cursor on radial chart hover, as we do in sunburst chart
> fix(radial-chart): Set cursor pointer on hover

- apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
- apps/dev/src/app.module.ts
- apps/dev/src/devapp-routing.module.ts
- apps/dev/src/devapp.component.ts
- apps/dev/src/dt-components.module.ts
- apps/dev/src/quick-filter/quick-filter-demo.component.html
- apps/dev/src/quick-filter/quick-filter-demo.component.scss
- apps/dev/src/quick-filter/quick-filter-demo.component.ts
- libs/barista-components/quick-filter/src/quick-filter-group.ts
…oupitems (APM-266050)
<hr>
guidelines.
> fix(quick filter): Selected option get lost if they are not within max items size

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.9.0 w/ changelog

- .snyk
> chore: Delay snyk yargs warning until angular 11 upgrade.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.10.0 w/ changelog

- tools/slack-release-notifier/package-lock.json
- tools/slack-release-notifier/package.json
Update slack webhook to fix axios security issue. 
Other
> chore: Fix dependency of slack webhook to mitigate axios security risk.

- libs/barista-components/chart/index.ts
- libs/barista-components/chart/src/heatfield/chart-heatfield.ts
- libs/barista-components/chart/src/tooltip/chart-tooltip-position.ts
- libs/barista-components/chart/src/tooltip/chart-tooltip.ts
- libs/barista-components/chart/src/utils.ts
- libs/examples/src/chart/chart-bar-example/chart-bar-example.ts
Fixes an issue where a required Interfaces was not exported from the chart, leading to weird / broken imports in the examples. 
Bugfix
> fix(chart): Added DtPlotBackgroundInfo to exported interfaces.

- libs/barista-components/tabs/src/tab-group.scss
> fix(tabs): Fixes an issue where theme custom properties were not applied correctly

- libs/barista-components/quick-filter/src/quick-filter-group.ts
List also needed to be updated when the active filters changed (incoming event from the filter field).
Bugfix
> fix(quick-filter): Fixes an issue with initial display of active items in the sidebar.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 8.11.0 w/ changelog

- libs/barista-components/package.json
I've changed the package.json versions for the json used in the released bundle.
> chore: Bump versions in release package.json.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.0.0-rc.0 w/ changelog

- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.html
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.ts
- apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.html
- apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.ts
- libs/barista-components/stacked-series-chart/README.md
- libs/barista-components/stacked-series-chart/barista.json
- libs/barista-components/stacked-series-chart/index.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.spec.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts
Details described on issue #1889 which is solved by this PR.
Formatting issue: In this PR some files were changed in format(Readme.md & stacked-series.chart.html" , it looks like the precommit is automatically doing it, tried with VSCode and IntelliJ nothing worked to maintain the format they had before, just after commiting my changes were back to the state we see in the changes of the PR.
> feat(stacked-series-chart): Add Input to be able to select the whole stack

- libs/barista-components/core/src/theming/theme-definitions/_blue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_purple-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_royalblue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_turquoise-theme.scss
Fixes mismatching colors in dt-palette
Fix
> fix(theming): Fixes an issue with mismatching colors in the warning palette.

- libs/barista-components/core/src/option/option.scss
Fixes a style regression in the dt-option
Chore
> chore(option): Fixes style regression in dt-option.

- libs/barista-components/core/src/theming/theme-definitions/_blue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_purple-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_royalblue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_turquoise-theme.scss
> fix(theming): Fixes an issue with mismatching colors in the error palette.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.0.0-rc.1 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.0.0-rc.2 w/ changelog

- apps/components-e2e/src/components/quick-filter/BUILD.bazel
- apps/components-e2e/src/components/quick-filter/quick-filter-show-more/quick-filter-show-more.html
- apps/components-e2e/src/components/quick-filter/quick-filter-show-more/quick-filter-show-more.ts
- apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
- apps/components-e2e/src/components/quick-filter/quick-filter.module.ts
- libs/barista-components/quick-filter/README.md
- libs/barista-components/quick-filter/src/quick-filter-group.html
- libs/barista-components/quick-filter/src/quick-filter-group.ts
- libs/barista-components/quick-filter/src/quick-filter.spec.ts
- libs/testing/fixtures/src/lib/filter-field/test-data.ts
> fix(quick-filter): Fix truncation.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.0.0-rc.3 w/ changelog

- libs/barista-components/chart/src/chart.ts
> fix(chart): Fixes an issue where tooltipDataChange event did not carry tooltip data.

- .bazelrc
- tools/bazel_rules/jest/jest-runner.js
Fixes an issue where breakpoints in tests would be triggered unreliably.
Other
> chore(workspace): Disable Jest concurrency in debug mode

- apps/dev/src/filter-field/filter-field-demo.component.html
- apps/dev/src/filter-field/filter-field-demo.component.ts
- apps/dev/src/filter-field/three-levels-nested-data.ts
- libs/barista-components/filter-field/README.md
- libs/barista-components/filter-field/src/filter-field-config.ts
- libs/barista-components/filter-field/src/filter-field-util.spec.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-data.ts
- libs/examples/src/filter-field/BUILD.bazel
- libs/examples/src/filter-field/filter-field-custom-placeholder/filter-field-custom-placeholder.example.html
- libs/examples/src/filter-field/filter-field-custom-placeholder/filter-field-custom-placeholder.example.ts
- libs/examples/src/filter-field/filter-field-examples.module.ts
- libs/examples/src/filter-field/index.ts
- libs/examples/src/index.ts
Add custom parser for filter-field component when input is incomplete. This implementation solves the issue [APM-270797](https://dev-jira.dynatrace.org/browse/APM-270797). Pending finish some test (I need more knowledge about how to debug them)
> feat(filter-field): Add custom parser for a incomplete input

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.0.0 w/ changelog

- libs/barista-components/core/src/util/compare-util.spec.ts
- libs/barista-components/core/src/util/compare-util.ts
- libs/barista-components/table/src/simple-columns/simple-column.spec.ts
Changes the sorting behavior for numbers in comparison with null values to nulls ASC first / DESC last. 
Feature
> feat(core,table): Introduces a new sorting behaviour which treats undefined/null values in number compares as ASC first/DESC last.

- apps/components-e2e/src/components/consumption/consumption.html
- apps/components-e2e/src/components/drawer/drawer.html
- apps/components-e2e/src/components/event-chart/event-chart.ts
- apps/components-e2e/src/components/filter-field/filter-field.ts
- apps/components-e2e/src/components/quick-filter/quick-filter-async/quick-filter-async.ts
- apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
- apps/components-e2e/src/components/quick-filter/quick-filter/quick-filter.ts
- apps/components-e2e/src/components/radial-chart/radial-chart.html
- apps/components-e2e/src/components/select/select.html
- apps/components-e2e/src/components/sunburst-chart/sunburst-chart.html
- apps/components-e2e/src/components/tree-table/tree-table.html
- apps/demos/src/app-routing.module.ts
- apps/demos/src/barista-examples.a11y.ts
- apps/demos/src/nav-items.ts
- apps/dev/src/filter-field/testdata.ts
- libs/barista-components/filter-field/README.md
- libs/barista-components/filter-field/src/filter-field-default-data-source.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts
- libs/barista-components/filter-field/src/types.ts
- libs/examples/src/filter-field/BUILD.bazel
- libs/examples/src/filter-field/filter-field-default-search-example/filter-field-default-search-example.html
- libs/examples/src/filter-field/filter-field-default-search-example/filter-field-default-search-example.ts
- libs/examples/src/filter-field/filter-field-examples.module.ts
- libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.ts
- libs/examples/src/filter-field/index.ts
- libs/examples/src/index.ts
Adds the quick input feature to the filter field. By using a freeText set to defaultSearch you can try it out.
README explains functionality
Thank you a lot @thomaspink for the guidance! Was a great learning experience.
- Feature (non-breaking change which adds functionality)
> feat(filter-field): Adds a quick input option (default search option)

- libs/barista-components/core/src/theming/theme-definitions/_blue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_purple-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_royalblue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_turquoise-theme.scss
Fixes an issue with out of sync recovered colors between custom properties and scss variables.
Bugfix
> fix(theming): Fixes an issue with out of sync recovered colors.

- libs/barista-components/table/src/expandable/expandable-row.ts
This was quite impossible to reproduce reliably and to be honest, we are not entirely sure if this will fix the problem.
Regarding to this issue in the angular components, this should help though and we were not seeing the error after this fix in our development environment.
https://github.com/angular/components/issues/13970
Fixes APM-276923
Bugfix
> fix(table): Fixes an issue with partial keyframes on expandable row.

- libs/barista-components/table/src/expandable/expandable-row.scss
> fix(table): Fixes an issue with the expandable row flashing when paginating a table.

- apps/dev/src/filter-field/filter-field-demo.component.ts
- apps/dev/src/filter-field/multi-select.ts
- apps/dev/src/filter-field/testdata.ts
- libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.html
- libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.scss
- libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/barista-components/filter-field/src/filter-field-with-multiselect.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/types.ts
Bugfix (non-breaking change which fixes an issue).
- Enabling async feature for multiselect fields
- Adding async example in demo
- UX enhancements 
- Adding test for current async implementation
> fix(filter-field): Handling asynchronous fetching for multiselect fields.

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/9.1.0

- libs/barista-components/expandable-panel/src/expandable-panel-trigger.ts
> fix(expandable-section): Fixes an issue where toggling the expandable section was triggering a form submission.

- apps/dev/src/quick-filter/quick-filter-demo.component.ts
- libs/barista-components/quick-filter/src/quick-filter-default-data-source.ts
<hr>
guidelines.
Bugfix (a non-breaking change that fixes an issue)
> fix(quick-filter): Fixes default search in the quick-filter

- DEVELOPMENT.md
It seems like the major pain point was the command list in the DEVELOPMENT.md.
Please take a look and give any feedback, suggestions or tell me what I could improve on.
> docs: Updated command list

- apps/dev/src/filter-field/filter-field-demo.component.html
- apps/dev/src/filter-field/filter-field-demo.component.ts
- libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
- libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-data.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts
Adds keyboard support to the filter-field
> feat(filter-field): Keyboard support

- libs/tools/shareable-examples/src/templates/angular.json.template
- libs/tools/shareable-examples/src/templates/package-shareable-example.json.template
- libs/tools/shareable-examples/src/templates/tsconfig.json.template
- libs/tools/shareable-examples/src/utils/get-boilerplate-files.ts
DevDependencies are not correctly picked up by stackblitz though. See https://github.com/stackblitz/core/issues/1389
Chore
> chore(examples): Updates examples for new angular stackblitz structure.

- apps/demos/src/app-routing.module.ts
- libs/barista-components/tile/README.md
- libs/barista-components/tile/src/_tile-theme.scss
- libs/barista-components/tile/src/tile.ts
- libs/examples/src/index.ts
- libs/examples/src/tile/BUILD.bazel
- libs/examples/src/tile/tile-examples.module.ts
- libs/examples/src/tile/tile-warning-example/tile-warning-example.html
- libs/examples/src/tile/tile-warning-example/tile-warning-example.ts
Added warning color option to tile component
> feat(tile): Added warning color to tile component

- .snyk
> chore(workspace): Adjust lodash transitive dependency snyk rule.

- libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/barista-components/filter-field/src/filter-field-with-multiselect.spec.ts
Bugfix (non-breaking change which fixes an issue).
- Keeping already selected values, on edit mode, for asynchronous values
- Adding test for current async implementation
> fix(filter-field): Improving isOptionSelected method for async values.

- libs/barista-components/table/src/simple-columns/simple-column-base.ts
- libs/barista-components/tag/src/tag.ts
Missed two instances for the strict checks.
Refactor
> refactor: Added input typings to fix strict coercion in tag and table.

- libs/barista-components/experimental/combobox/src/combobox.scss
Using the same styles as in the select.
Bugfix
> fix(combobox): Fixes an issue with the arrow positioning on safari.

- apps/dev/src/filter-field/filter-field-demo.component.html
- apps/dev/src/filter-field/filter-field-demo.component.ts
- libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
- libs/barista-components/filter-field/src/filter-field-range/filter-field-with-range.spec.ts
- libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
- libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.scss
- libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
> feat(filter-field): Adds seperate disabled member in tags

- libs/barista-components/indicator/src/indicator.ts
- libs/barista-components/table/src/cell.ts
> refactor: Fixed strict typing input rename in table and indicator.

- apps/dev/src/filter-field/testdata.ts
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-data.ts
> fix(filter-field): Fixes freeTexts set as defaultSearch and unique.

- apps/dev/src/filter-field/filter-field-demo.component.ts
- apps/dev/src/filter-field/multi-select.ts
- apps/dev/src/filter-field/testdata.ts
- libs/barista-components/filter-field/src/filter-field-default-data-source.ts
- libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/types.ts
- Enabling partial suggestions feature for asynchronous multiselect fields
- Updating test for current implementation
- Updating demo component
> feat(filter-field): Allow partial suggestions for async multiselect .

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/9.3.0

- libs/barista-components/tabs/README.md
Fixes wrong headline and missing input for the tabs.
Docs
> docs(tabs): Fixes a mistake on the tabs docs page.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.3.1 w/ changelog

- libs/barista-components/breadcrumbs/src/_breadcrumbs-theme.scss
- libs/barista-components/breadcrumbs/src/breadcrumbs.scss
Fixes weird zooming issues in the breadcrumbs by changing the implementation of the triangle. 
Diff in view. More or less the same and some aliasing diff.
Bugfix
> fix(breadcrumbs): Fixes an issue with breadcrumbs and browser zoom level

- libs/barista-components/table/src/expandable/expandable-row.ts
The expandable cell did not clean up the unique selection listeners after itself which lead to a bit of a leak. 
This has gone unnoticed for 2 years 😢 
Fixes APM-292781
Bugfix
> fix(table): Fixes an issue where the expandable row did not clean up after itself.

- libs/barista-components/overlay/src/overlay-ref.ts
Not only is my fix in #2037 not working (maybe my branch wasn't up to date 😕 🤷‍♂️), but overlays are getting stuck open, because of it. More info in internal ticket.
Fixes APM-294266
Bugfix
> fix(overlay): Overlays get stuck open due to #2037.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.4.0 w/ changelog

- apps/barista-design-system/src/pages/single-page/single-page.html
- apps/barista-design-system/src/pages/single-page/single-page.ts
> fix(barista): Fixes routing in barista for the 2nd time.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.4.1 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/9.4.2

- libs/examples/src/select/select-default-example/select-default-example.html
- libs/examples/src/select/select-default-example/select-default-example.ts
> chore(select): Revert default select example.

- libs/barista-components/formatters/README.md
- libs/barista-components/indicator/README.md
- libs/barista-components/overlay/README.md
- libs/barista-components/tile/README.md
- libs/barista-components/toggle-button-group/README.md
- libs/barista-components/top-bar-navigation/README.md
- libs/barista-components/tree-table/README.md
A couple of doc fixes.
Documentation
> docs(components): Fixes all api-table escape problems and removes time-formatter documentation.

- libs/barista-components/pagination/src/pagination.html
- libs/barista-components/pagination/src/pagination.ts
Improve rerender performance by adding a trackby to the pagination.
FYI @bartoszbobin 
Performance improvement
> perf(pagination): Loops in the pagination are now trackedBy.

- libs/barista-components/filter-field/src/filter-field-default-data-source.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/types.ts
Component: filter-field
Feature: added possibility to disable autocomplete option
> feat(filter-field): Added possibility to disable autocomplete option.

- libs/barista-components/stepper/src/step-header.scss
Oddly shaped active stepper circles are fixed by enforcing border-box 
Bugfix
> fix(stepper): Fixes an issue where active stepper icon was oddly shaped.

- apps/demos/src/app-routing.module.ts
- apps/demos/src/nav-items.ts
- apps/dev/src/event-chart/big-time-test-data.ts
- apps/dev/src/event-chart/easy-travel-test-data.ts
- apps/dev/src/event-chart/event-chart-demo-data.ts
- apps/dev/src/event-chart/event-chart-demo.component.html
- apps/dev/src/event-chart/event-chart-demo.component.ts
- apps/dev/src/event-chart/mobile-actions-test-data.ts
- apps/dev/src/event-chart/session-replay-test-data.ts
- libs/barista-components/event-chart/README.md
- libs/barista-components/event-chart/src/event-chart-directives.ts
- libs/barista-components/event-chart/src/event-chart-module.ts
- libs/barista-components/event-chart/src/event-chart.html
- libs/barista-components/event-chart/src/event-chart.scss
- libs/barista-components/event-chart/src/event-chart.spec.ts
- libs/barista-components/event-chart/src/event-chart.ts
- libs/barista-components/event-chart/src/merge-and-path/merge-events.ts
- libs/barista-components/event-chart/src/render-event.interface.ts
- libs/examples/src/event-chart/BUILD.bazel
- libs/examples/src/event-chart/event-chart-examples.module.ts
- libs/examples/src/event-chart/event-chart-heatfield-example/event-chart-heatfield-example.html
- libs/examples/src/event-chart/event-chart-heatfield-example/event-chart-heatfield-example.ts
- libs/examples/src/event-chart/index.ts
- libs/examples/src/index.ts
> feat(event-chart): APM-295388 Implemented "heatfield" into event-chart

- libs/barista-components/sunburst-chart/src/sunburst-chart-segment.ts
- libs/barista-components/sunburst-chart/src/sunburst-chart.mock.ts
- libs/barista-components/sunburst-chart/src/sunburst-chart.spec.ts
- libs/barista-components/sunburst-chart/src/sunburst-chart.util.spec.ts
- Feature (non-breaking change which adds functionality)
- Exposing sunburst's node data in order to be used in the tooltip.
- Updating tests
> feat(sunburst-chart): Exposing sunburst node data in tooltip config.

- .snyk
> chore(workspace): Ignore transitive dependency vulnerability.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.5.0 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.6.0 w/ changelog

- apps/dev/src/event-chart/easy-travel-test-data.ts
- libs/barista-components/event-chart/src/event-chart.html
- libs/barista-components/event-chart/src/event-chart.ts
- libs/barista-components/event-chart/src/merge-and-path/create-event-path.ts
- libs/barista-components/event-chart/src/merge-and-path/merge-events.ts
> fix(event-chart): Fixes various issues with the legend and heatfields.

- libs/barista-components/filter-field/src/filter-field-config.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.scss
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts
Fixes #APM-277597
https://user-images.githubusercontent.com/6016950/118957572-ee3e6e80-b960-11eb-9dff-50b62d9a77e8.mp4
> feat(filter-field): Display a hint when partial options are loaded.

- libs/barista-components/overlay/README.md
- libs/barista-components/overlay/src/overlay-ref.ts
- libs/barista-components/overlay/src/overlay-trigger.spec.ts
- libs/barista-components/overlay/src/overlay-trigger.ts
- libs/examples/src/overlay/overlay-default-example/overlay-default-example.html
- libs/examples/src/overlay/overlay-default-example/overlay-default-example.ts
Updates README,
Adds isOverlayPinned getter
Adds pinnedChanged EventEmitter
> feat(overlay): Adds pinnedChanged output and isOverlayPinned property.

- apps/dev/src/icon/icon-demo.component.html
- apps/dev/src/indicator/indicator-demo.component.ts
- libs/barista-components/core/src/common-behaviours/color.ts
- libs/barista-components/core/src/theming/_theming-core.scss
- libs/barista-components/core/src/theming/theme-definitions/_blue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_purple-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_royalblue-theme.scss
- libs/barista-components/core/src/theming/theme-definitions/_turquoise-theme.scss
- libs/barista-components/icon/src/icon.scss
- libs/barista-components/icon/src/icon.spec.ts
- libs/barista-components/icon/src/icon.ts
- libs/barista-components/indicator/README.md
- libs/barista-components/indicator/src/indicator.scss
- libs/barista-components/indicator/src/indicator.spec.ts
- libs/barista-components/indicator/src/indicator.ts
- libs/barista-components/style/main.scss
- libs/barista-components/style/themes.scss
- libs/barista-components/table/src/cell.ts
- libs/barista-components/table/src/expandable/expandable-row.scss
- libs/barista-components/table/src/row.scss
- libs/barista-components/table/src/row.ts
- libs/barista-components/tree-table/src/tree-table-row.scss
- libs/examples/src/indicator/indicator-default-example/indicator-default-example.html
- libs/examples/src/indicator/indicator-default-example/indicator-default-example.ts
- libs/examples/src/table/table-problem-example/table-problem-example.ts
> feat(theming): Add critical color to theme.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.8.0 w/ changelog

- libs/barista-components/context-dialog/src/context-dialog.html
- libs/barista-components/context-dialog/src/context-dialog.scss
- libs/barista-components/context-dialog/src/context-dialog.spec.ts
- libs/barista-components/context-dialog/src/context-dialog.ts
This now handles cases where the overlay cannot fit at all into any given position correctly as well.
<hr>
guidelines.
Please choose the type appropriate for the changes below: …
> fix(context-dialog): Fixes flexible dimensions being applied correctly.

- package-lock.json
> chore(deps): Fixes vulnerability in path-parse by bumping to 1.0.7

- CHANGELOG.md
- libs/barista-components/context-dialog/src/context-dialog.html
- libs/barista-components/context-dialog/src/context-dialog.scss
- libs/barista-components/context-dialog/src/context-dialog.spec.ts
- libs/barista-components/context-dialog/src/context-dialog.ts
- package-lock.json
- package.json
> chore: Bump version to 9.8.1 w/ changelog

- libs/barista-components/filter-field/src/filter-field-default-data-source.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.scss
- libs/barista-components/filter-field/src/types.ts
> feat(filter-field): Added partial hint message flexible configuration

- libs/examples/src/filter-field/filter-field-async-example/filter-field-async-example.ts
> fix(filter-field): Fixes the async example when using freeText

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/9.9.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.10.0 w/ changelog

- .snyk
- package-lock.json
- package.json
Update security policies. 
Skipping d3 as it will be updated in barista version 10
> chore(workspace): Update snyk policy for security checks.

- libs/barista-components/filter-field/src/filter-field-edit-mode.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-data.ts
> feat(filter-field): Prefills text of first level freeText node on edit

- .github/CODEOWNERS
> fix(workspace): Remove codeowner.

- apps/dev/src/filter-field/testdata.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.spec.ts
> feat(filter-field): Add disable state to the option without group

- libs/barista-components/chart/src/chart.interface.ts
Due to Heatmaps chart in development the DtChartSeries type should be extended with SeriesHeatmapOptions.
<hr>
guidelines.
Please choose the type appropriate for the changes …
> feat(chart): Added series heatmaps options to dt chart series type

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/9.11.0

- libs/barista-components/filter-field/index.ts
Export DtFilterFieldValidator in index for custom data sources.
<hr>
guidelines.
Bugfix (non-breaking change which …
> fix(filter-field): Export validator type.

- libs/barista-components/filter-field/src/filter-field-validation.ts
- libs/barista-components/filter-field/src/filter-field.scss
- libs/examples/src/quick-filter/BUILD.bazel
- libs/examples/src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts
> fix(quickfilter): Fixes z-index issues with the error message.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.11.1 w/ changelog

- .snyk
> chore(workspace): Fix snyk config.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.11.2 w/ changelog

- apps/dev/src/filter-field/multi-select.ts
- libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
- libs/examples/src/filter-field/filter-field-multi-select-example/filter-field-multi-select-example.ts
Enabling multiselect feature for complex/nested filter types.
- Checking if one of the filter level has a multiselect field in order to get the proper values
- Adding unit tests for the new functionality
> feat(filter-field): Adding multiselect capabilities to complex filter type.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 9.12.0 w/ changelog

- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.e2e.ts
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.html
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.mocks.ts
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.po.ts
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.ts
- apps/demos/src/app-routing.module.ts
- apps/demos/src/nav-items.ts
- libs/barista-components/stacked-series-chart/README.md
- libs/barista-components/stacked-series-chart/index.ts
- libs/barista-components/stacked-series-chart/src/_stacked-series-chart-shared.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.module.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts
- libs/examples/src/index.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-date-example/stacked-series-chart-date-example.html
- libs/examples/src/stacked-series-chart/stacked-series-chart-date-example/stacked-series-chart-date-example.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-examples.module.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-linear-example/stacked-series-chart-linear-example.html
- libs/examples/src/stacked-series-chart/stacked-series-chart-linear-example/stacked-series-chart-linear-example.ts
<hr>
- New features
- Continuous axis calculated by d3 depending on the type (none, linear, date (time)). Ticks will be automatically rendered depending on chart size.
- Tick format and mapping, for flexibility and scalability purposes
- Time interval for date type (per min, every 4 hours...)
- Improvements
- Scrollability: ticks hidden when scrolling under the y axis
- Auto-width for ticks, whether is bar or column
- Component now detects page resize properly
- Tests in place
> feat(stacked-series-chart): Adding continuous axis and improve scrollability

- libs/barista-components/formatters/src/date/date-range.ts
fixes APM-331190
<hr>
guidelines.
> fix(formatters): Fixes range-selection date formatting.

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/10.1.0

- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.e2e.ts
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.html
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.mocks.ts
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.po.ts
- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.ts
- apps/demos/src/app-routing.module.ts
- apps/demos/src/nav-items.ts
- libs/barista-components/event-chart/src/event-chart.html
- libs/barista-components/overlay/src/overlay-trigger.ts
- libs/barista-components/stacked-series-chart/README.md
- libs/barista-components/stacked-series-chart/index.ts
- libs/barista-components/stacked-series-chart/src/_stacked-series-chart-shared.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-overlay.directive.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.module.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts
- libs/examples/src/index.ts
- libs/examples/src/stacked-series-chart/index.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-demo-data.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-examples.module.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-heat-field-example/stacked-series-chart-heat-field-example.html
- libs/examples/src/stacked-series-chart/stacked-series-chart-heat-field-example/stacked-series-chart-heat-field-example.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-linear-example/stacked-series-chart-linear-example.ts
- Heat Fields overlap supported
- Light overlay rendering (removing unnecessary code)
- HeatField example and e2e
- Overlay fix to avoid tooltip to close when unpinned
<hr>
guidelines.
- Docs have been added / updated (for bug fixes / …
> feat(stacked-series-chart): Adding heat fields

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.2.0 w/ changelog

- apps/demos/src/app-routing.module.ts
- apps/demos/src/nav-items.ts
- libs/barista-components/experimental/drawer-table/src/drawer-table.spec.ts
- libs/barista-components/table/README.md
- libs/barista-components/table/src/table-data-source.ts
- libs/barista-components/table/src/table-module.ts
- libs/barista-components/table/src/table.html
- libs/barista-components/table/src/table.scss
- libs/barista-components/table/src/table.ts
- libs/examples/src/index.ts
- libs/examples/src/table/index.ts
- libs/examples/src/table/table-examples.module.ts
- libs/examples/src/table/table-export-example/table-export-example.html
- libs/examples/src/table/table-export-example/table-export-example.scss
- libs/examples/src/table/table-export-example/table-export-example.ts
- libs/examples/src/table/table-export-selection-example/table-export-selection-example.html
- libs/examples/src/table/table-export-selection-example/table-export-selection-example.scss
- libs/examples/src/table/table-export-selection-example/table-export-selection-example.ts
- package-lock.json
<hr>
guidelines.
Feature: added a context dialogue with an "Export CSV" button
- [n/a] I have added tests that …
> Add exportCSV to dt-table

- .snyk
> chore(workspace): Adjust snyk config.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.3.0 w/ changelog

- apps/dev/src/form-field/form-field-demo.component.html
- libs/barista-components/experimental/combobox/src/combobox.scss
> fix(combobox): Fixes the border inside a form-field

- .circleci/config.yml
Disabled e2e and a11y tests for now.
> chore(workspace): Disable e2e and a11y tests for now.

- libs/barista-components/experimental/datepicker/src/datepicker.spec.ts
- libs/barista-components/experimental/datepicker/src/datepicker.ts
> fix(datepicker): Fix button label initialization.

- .snyk
- libs/barista-components/select/src/select.scss
> fix(select): Fixes outline position within formfield.

- angular.json
- apps/barista-design-system/src/environments/production/index.html
Added tag manager to public barista. :crying_cat_face:
> chore(barista): Added GTM to barista-design-system.

- .snyk
- libs/barista-components/autocomplete/src/autocomplete-trigger.ts
Fixed alignment for autocomplete-overlay if not enough space is available on the right.
> fix(autocomplete): Fixed alignment for autocomplete-overlay if not enough space is available on the right.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.5.0 w/ changelog

- libs/barista-components/select/src/select.scss
> fix(select): Updated outline width when inside a form field

- libs/barista-components/expandable-section/src/expandable-section.scss
Before:
After:
<hr>
guidelines.
> fix(expandable-section): Fix issue where input focus was truncated

- libs/barista-components/filter-field/src/filter-field.scss
fix(filter-field): Fixes an issue where the displayed label in edit mode might overflow in certain cases.
> 10.x fix(filter-field): Fixes an issue where the displayed label in edit mode might overflow in certain cases.

- libs/barista-components/table/README.md
- libs/barista-components/table/src/header/header-cell.ts
- libs/barista-components/table/src/table.html
- libs/barista-components/table/src/table.spec.ts
- libs/barista-components/table/src/table.ts
- libs/examples/src/table/table-export-example/table-export-example.html
- libs/examples/src/table/table-export-example/table-export-example.ts
- libs/examples/src/table/table-export-selection-example/table-export-selection-example.html
- Add tests
- Handle gettings labels from complex columns
- Handle case where data is inserted directly in table instead of data source
- Handle up to 5 levels of object recusion for complex data
- Allow devs to pick only visible or only table data
<hr>
guidelines.
- Tests for the changes have been added …
> Further updates to Table export

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.7.2 w/ changelog

- libs/barista-components/table/src/table.ts
- libs/examples/src/table/table-export-example/table-export-example.html
- libs/examples/src/table/table-export-example/table-export-example.ts
- libs/examples/src/table/table-export-selection-example/table-export-selection-example.html
<hr>
guidelines.
Bugfix (non-breaking change which fixes an issue) 
- [ X] I have read the CONTRIBUTING doc and I …
> fix(table): Export handles newlines & expand rows.

- libs/barista-components/style/_link.scss
> fix(link): External link icon is scaled correctly in Safari.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.7.4 w/ changelog

- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.mocks.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-demo-data.ts
- No data support (only designated axis will be shown)
- Avoid undefined values
- HeatField - support any kind of data
<hr>
guidelines.
Please choose the type appropriate for …
> fix(stacked-series-chart): No data support and heat fields fix

- apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.mocks.ts
- libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
- libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
- libs/examples/src/stacked-series-chart/stacked-series-chart-demo-data.ts
- No data support (only designated axis will be shown)
- Avoid undefined values
- HeatField - support any kind of data
<hr>
guidelines.
Please choose the type appropriate for …
> fix(stacked-series-chart): No data support and heat fields fix [Backport 10.x] 

- .snyk
> chore(workspace): Update snyk policy.

- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/filter-field.spec.ts
- libs/barista-components/filter-field/src/filter-field.ts
- libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts
> fix(filter-field): Hide clear-all button when no filters are applied.

- apps/dev/src/card/card-demo.component.html
- libs/barista-components/card/src/card.scss
> fix(card): Prevent heading from being cut off on Safari on iOS.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.7.6 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.7.7 w/ changelog

- apps/dev/src/tag/tag-demo.component.html
- libs/barista-components/tag/src/tag.html
- libs/barista-components/tag/src/tag.ts
- Added aria-label to remove button in dt-tag
- Added example for setting aria-label to remove button in dev app example
> feat(tag): Add aria-label to remove button in dt-tag.

- .github/CODEOWNERS
Added Sherif-Elhefnawy & removed @rowaudil as codeowner
> chore: Added Sherif-Elhefnawy & removed @rowaudil as codeowner

- libs/barista-components/quick-filter/src/quick-filter.html
- libs/barista-components/quick-filter/src/quick-filter.scss
- libs/barista-components/quick-filter/src/quick-filter.ts
- libs/barista-components/quick-filter/src/state/actions.ts
- libs/barista-components/quick-filter/src/state/reducer.ts
> fix(quick-filter): Move focus to correct element after View more is clicked

- libs/barista-components/table/README.md
- libs/barista-components/table/src/table.spec.ts
- libs/barista-components/table/src/table.ts
- libs/examples/src/table/table-export-example/table-export-example.html
- libs/examples/src/table/table-export-example/table-export-example.ts
ie if new data is added in DS, now included in table export. (APM-384237)
<hr>
guidelines.
Bugfix (non-breaking …
> fix(table): Table export prefers data in DS.

- libs/barista-components/table/README.md
- libs/barista-components/table/src/header/header-cell.ts
- libs/barista-components/table/src/table.html
- libs/barista-components/table/src/table.spec.ts
- libs/barista-components/table/src/table.ts
- libs/examples/src/table/table-export-example/table-export-example.html
- libs/examples/src/table/table-export-example/table-export-example.ts
- libs/examples/src/table/table-export-selection-example/table-export-selection-example.html
<hr>
guidelines.
Other (if none of the above apply) 
- [X ] I have read the CONTRIBUTING doc and I follow the PR …
> Cherry-pick table export updates

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.8.0 w/ changelog

- libs/barista-components/chart/src/chart.html
- libs/barista-components/chart/src/chart.ts
- libs/barista-components/chart/src/selection-area/selection-area.ts
- libs/barista-components/chart/src/utils.spec.ts
- libs/barista-components/chart/src/utils.ts
* Add default aria-label which describes the series in the chart.
* Add the ability to override the default aria-label via an @input.
ADES-138
> feat(chart): Add default aria-label and ability to override it.

- libs/barista-components/filter-field/src/filter-field.ts
> chore(filter-field): Add presentation role to dt-filter-field.

- libs/barista-components/formatters/src/chaining.spec.ts
- libs/barista-components/formatters/src/count/count.spec.ts
- libs/barista-components/formatters/src/number-formatter.spec.ts
- libs/barista-components/formatters/src/number-formatter.ts
> feat(formatters): Aligned number formatters with defined patterns

- libs/barista-components/formatters/src/chaining.spec.ts
- libs/barista-components/formatters/src/count/count.spec.ts
- libs/barista-components/formatters/src/number-formatter.spec.ts
- libs/barista-components/formatters/src/number-formatter.ts
> feat(formatters): Aligned number formatters with defined patterns Barista 11

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.9.1 w/ changelog

- libs/barista-components/filter-field/src/filter-field-util.spec.ts
- libs/barista-components/filter-field/src/filter-field-util.ts
> feat(filter-field): Tokenize search term before filtering.

- libs/barista-components/core/src/date/date-adapter.ts
Improve date adapter createDate() error log by providing more information - details in APM-391293
Other
> refactor(date-adapter): Add more information to error thrown in createDate()

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.10.0 w/ changelog

- libs/barista-components/table/src/table.spec.ts
- libs/barista-components/table/src/table.ts
- libs/examples/src/table/table-export-example/table-export-example.html
> Table export cherry picked issues

- libs/barista-components/table/src/selection/selectors.scss
> fix(table): Select all in table headers now aligns correctly in multi-lines

- libs/barista-components/tag/src/tag-list/tag-list.html
- libs/barista-components/tag/src/tag-list/tag-list.scss
- libs/barista-components/tag/src/tag-list/tag-list.spec.ts
- libs/barista-components/tag/src/tag-list/tag-list.ts
Cherry picked from b54645aa74a71790cc930ad7ae62e8dd9151d509
> feat(tag-list): Added show less button.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.11.0 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 10.11.1 w/ changelog

- libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.html
- libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.spec.ts
- libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.ts
> feat(copy-to-clipboard): Made it possible to disable the copy button

- libs/barista-components/chart/src/heatfield/chart-heatfield.scss
Before and after
- [V] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [V] Lint and unit tests pass locally with my changes
- [V] I have added tests that prove my fix is effective or that my feature works
- [V] I have added necessary documentation (if appropriate)
> fix(chart-heatfield): Set min-width for marker heatfield.

- libs/barista-components/filter-field/src/filter-field-default-data-source.spec.ts
- libs/barista-components/filter-field/src/filter-field-default-data-source.ts
- libs/barista-components/filter-field/src/filter-field-range/filter-field-range.html
- libs/barista-components/filter-field/src/filter-field-range/filter-field-range.ts
- libs/barista-components/filter-field/src/filter-field.html
- libs/barista-components/filter-field/src/types.ts
- libs/examples/src/filter-field/filter-field-programmatic-filters-example/filter-field-programmatic-filters-example.ts
If `pattern` is not defined, default one will be use
<hr>
guidelines.
Feature (non-breaking change which adds …
> feat(filter-field): Allow to define custom 'pattern' for `range` inputs.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 11.0.0 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 11.0.1 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 11.0.3 w/ changelog

- libs/barista-components/core/src/date/date-adapter.spec.ts
- libs/barista-components/core/src/date/date-adapter.ts
- libs/barista-components/core/src/date/index.ts
Fixing PS-9497, improves PS-9178
> Date adapter fixes

- libs/barista-components/table/src/cell.ts
- libs/barista-components/table/src/header/header-cell.ts
- libs/barista-components/table/src/order/order-cell.ts
- libs/barista-components/table/src/selection/selectors.ts
- libs/barista-components/table/src/sort/sort.ts
- libs/barista-components/table/src/table.ts
> fix(table): Fixes an issue with ngDestroy timings.

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 16.0.1 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 16.0.2 w/ changelog

- CHANGELOG.md
- package-lock.json
- package.json
> Release stage/16.0.3

- CHANGELOG.md
- package-lock.json
- package.json
> chore: Bump version to 16.0.4 w/ changelog
