dynatrace-oss/barista

components/micro-chart/src/micro-chart-module.ts

fix(micro-chart): Fixes an issue when using the chart-tooltip in a micro-chart without importing the chart-module causes an error.

Fixes missing export for using chart-tooltips in micro charts

---

components/progress-bar/src/progress-bar-module.ts

fix(progress-bar): Fixes an issue when using the indicator without importing the core indicator-module causes an error.

Fixes missing export for using indicators in progress-bars

---

.vscode/extensions.json

It seems like the shinnn.stylelint plugin for vscode is no longer available. To prevent constant warnings in vscode, we removed the extension for now
<hr>
guidelines. …

chore: Remove shinnn.stylelint from recommendations.

---

.circleci/config.yml

Calculate correct commit hashes so that affected knows always against which target it should compare. Currently, we were always running against master.
- `4.x` against latest commit between the changes and previous commits
- `4.14.x` against latest commit between the changes and previous commits
- `master` against latest commit between the changes and previous commits
- PRs check for the target hash
- commits without PR against origin/master

ci: Run affected targets correctly on master and on PR as on 4.x and 1.15x

---

.circleci/config.yml

Fixes the cache key generation that was currently skipped:
```
Skipping cache generation, cache already exists for key: last-master-sha
Found one created at 2019-12-06 08:07:18 +0000 UTC
````
now with the unix epoch timestamp, it is a unique cache and does not need to be overridden.

ci: Use the unix epoch to have always a unique cache key

---

components/filter-field/src/filter-field-range/filter-field-range-trigger.ts

The range overlay was positioned too far right and had no alternative positions
in the FlexibleCOnnectedPositionStrategy, which caused it to not reposition
when the range was rendered too close to the screen border.
Fixes #301 
<hr>
guidelines.
- Tests for the changes have been added (for bug fixes / …

fix(filter-field): Fixes an issue where the range was cut off.

---

commitlint.config.js

chore(commitlint): Removed references-empty rule so issue references are possible in commit message bodies.

chore(commitlint): Removed references-empty rule so issue references are possible in commit message bodies.

---

components/core/src/animations/error-animations.ts
components/expandable-panel/src/expandable-panel.ts
components/expandable-text/src/expandable-text.ts
components/secondary-nav/src/section/secondary-nav-section.ts
components/table/src/expandable/expandable-row.ts

I have added explicit type annotations where they were missing and breaking the build. For details see issue #343

Fix build on Windows by adding explicit type annotations

---

tools/pull-request-labeler/src/utils/process-commit-messages.ts

ci(pull-request-labeler): Fixes incorrect applied labels for non fix/feat commits.

ci(pull-request-labeler): Fixes incorrect applied labels for non fix/feat commits.

---

components/overlay/src/overlay-trigger.ts

When hovering a SVGElement in firefox the MouseEvent delivered a wrong
value for the placement offset. Added a special code branch that
deals with that issue.
Closes #339
<hr>
guidelines.
- Docs have been added / updated (for bug fixes / …

fix(overlay): Fixes an issue with overlay placement in firefox.

---

.circleci/config.yml

The built components library artefacts are needed to be downloadable for releasing a new version of the Library.

ci: Store build artefacts for components.

---

.circleci/config.yml

All resource intense tasks like building e2e testing and code checking should use the xlarge resource class.

ci: Use xlarge resource classes.

---

components/filter-field/src/filter-field-default-data-source.ts
components/filter-field/src/filter-field-tag/filter-field-tag.spec.ts
components/filter-field/src/filter-field-tag/filter-field-tag.ts
components/filter-field/src/filter-field-util.spec.ts
components/filter-field/src/filter-field-util.ts
components/filter-field/src/filter-field.spec.ts
components/filter-field/src/filter-field.ts
components/filter-field/src/index.ts
components/filter-field/src/types.ts

filter-field: Changes param ordering on definition creation functions.
BREAKING CHANGE: Changed param ordering on definition creation functions and removed deprecated overrides for better extendibility when adding new params.
Breaking change (fix or change that would cause existing functionality to not work as expected)

filter-field: Changes param ordering on definition creation functions and other breaking changes

---

components/filter-field/src/filter-field-util.spec.ts
components/filter-field/src/filter-field-util.ts

**filter-field:**
Fixes an issue where the filtering of groups did not work properly because of a wrong param ordering.

fix(filter-field): Fixes an issue where the filtering of groups did not work properly because of a wrong param ordering.

---

components/chart/src/chart.ts
components/chart/src/tooltip/chart-tooltip.spec.ts

We previously had a isInViewport check for the chart to determine if we
should show the tooltip on hover. Since this caused multiple problems
with threshold limits, we have removed the inViewport check again.
Fixes #295
<hr>
guidelines.
- …

fix(chart): Fixes an issue with not appearing tooltips.

---

libs/examples/src/chart/chart-min-max-example/chart-min-max-example.ts

Fixed an issue where the lineWidth was set in the wrong options set
which resulted in a highcharts error.
Fixes #409
<hr>
guidelines. …

chore(chart): Fixed an configuration issue with the min/max example.

---

.circleci/config.yml

Currently, the build fails when the build stage doesn't build the components library. In case there is no dist folder with components that can be packed.
So we have to pack it only when the folder exists.
Fixes #420

ci: Check if components folder exists befor trying to tar it

---

angular.json
apps/components-e2e/src/components/key-value-list/key-value-list.e2e.ts

As the default value for browserstack always targets the latest version
of a browser, we needed to lock the version and operating system to edge
version 18 on windows. Browserstack would have defaulted to newer edge
versions based on chromium, which would not provide any benefit.
<hr>
guidelines.
- Tests …

chore: Lock remote edge e2e test version to 18 on windows.

---

.circleci/config.yml
angular.json
apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
apps/components-e2e/src/components/chart/selection-area/selection-area.po.ts
apps/components-e2e/src/components/drawer/drawer.e2e.ts

Closes #244 Fixes the failing selection area tests by using the chaining that is provided by testcafe and throttling the drag speed from 1 to 0.01.
As performance benefit, we are now running 5 tests in parallel on BrowserStack to get the maximum speed.
<hr>
guidelines.
- Tests for the changes have been …

Fixes flaky chart selection area e2e tests.

---

.circleci/config.yml

Currently, the cherrypicker creates temporary branches where the cherrypick is performed. Those branches should not be built by circle. Furthermore, they are failing in case they are getting deleted afterwards.

ci: Ignore temporary cherrypick branches.

---

.github/CODEOWNERS
angular.json
nx.json
tools/pull-request-labeler/jest.config.js
tools/pull-request-labeler/src/main.ts
tools/pull-request-labeler/src/test-setup.ts
tools/pull-request-labeler/src/utils/process-commit-messages.spec.ts
tools/pull-request-labeler/src/utils/process-commit-messages.ts
tools/pull-request-labeler/src/utils/split-message-into-components.spec.ts
tools/pull-request-labeler/src/utils/split-message-into-components.ts
tools/pull-request-labeler/tsconfig.spec.json

The autolabeler had a small bug, where it did not correclty parse the
commit messages and their features, which led the labeler to always add
minor and patch labels as a fallback.
Fixes #478
CI fix

ci: Fixes an issue with the autolabeler applying wrong labels.

---

apps/components-e2e/src/components/drawer/drawer.e2e.ts
apps/components-e2e/src/utils/wait-for-angular.ts

Fixed flaky drawer tests by using the chaing of testcafe and reducing the click and hovering speed to a human-like level. Furthermore, increase the initial retry timeout for the ng probe check of the `waitForAngular` function.
<hr>
guidelines.
- Tests for the changes have been added (for bug fixes / …

test(drawer): Fixes flaky drawer e2e tests.

---

apps/components-e2e/src/components/drawer/drawer.e2e.ts

Removes a missed `.only` in the drawer e2e

chore(drawer): Removes only

---

apps/barista/src/components/live-example/live-example.html
apps/barista/src/components/live-example/live-example.ts
libs/shared/barista-definitions/src/lib/example-definitions.ts
tools/barista/src/transform.ts
tools/examples/src/generate-examples-lib-metadata.ts
tools/examples/src/metadata.ts

Added the SCSS content to the examples metadata if it is present.
Extended the metadata generation and the ba-live-example component to be
able to deal with extra SCSS added to the example.
Fixes #285
Documentation update

baritsa(live-examples): Added SCSS to live examples.

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
apps/components-e2e/src/components/filter-field/filter-field.po.ts
apps/components-e2e/src/components/filter-field/filter-field.ts
components/filter-field/src/filter-field.html
components/filter-field/src/filter-field.spec.ts
components/filter-field/src/filter-field.ts

When selecting a freetext node from the autocomplete with the keyboard
the the different eventHandlers of the autocomplete and the filterfield
raced to a broken state. To prevent the instant submission of an empty
free-text when selecting it with the keyboard, we are now checking for a
value in the free-text submission.
Fixes #294
<hr>
guidelines.
- The …

fix(filter-field): Fixes an issue with instant submission of free-text.

---

components/button/src/button.scss
components/filter-field/src/filter-field.scss

The filter-field buttons where styled by a side-effect in the
button.scss, which does not make sense. The button module ships code,
that it potentially does not need. Additionally, the side effect led to
misalignment in the tag-value, remove tag and clear all button styles.
Before: 
After: 
visual fix.

fix(filter-field): Fixes an issue with button alignments in the filter field.

---

apps/components-e2e/src/app/app.routing.module.ts
apps/components-e2e/src/components/chart/selection-area/selection-area.ts
apps/components-e2e/src/components/drawer/drawer.ts
apps/components-e2e/src/components/tree-table/tree-table.e2e.ts
apps/components-e2e/src/components/tree-table/tree-table.html
apps/components-e2e/src/components/tree-table/tree-table.module.ts
apps/components-e2e/src/components/tree-table/tree-table.po.ts
apps/components-e2e/src/components/tree-table/tree-table.ts
components/tree-table/README.md
components/tree-table/src/tree-table-toggle-cell.html
components/tree-table/src/tree-table-toggle-cell.ts
components/tree-table/src/tree-table.spec.ts

for DtTreeTableToggleCell.
Previously there was no way to figure out, if a tree has expanded or collapsed.
So `expandChanged(bool)`, `expanded()`, `collapsed()` events where introduced.
Expanded can also be bound with two way binding to set the initial state.
Fixes #415
Finalizes external contribution #458 
Thx @gselltho for the contribution! 🎉

feat(tree-table): Added events for expansion state changes 

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
apps/components-e2e/src/components/filter-field/filter-field.po.ts
components/filter-field/src/filter-field-module.ts
components/filter-field/src/filter-field-tag/filter-field-tag.html
components/filter-field/src/filter-field-tag/filter-field-tag.scss
components/filter-field/src/filter-field-tag/filter-field-tag.spec.ts
components/filter-field/src/filter-field-tag/filter-field-tag.ts
libs/testing/src/mock/mock-get-computed-style.ts

To provide the full value on an ellipsed filter field tag, we have added
a DtOverlay to the element, if it is being ellipsed. The overlay should
not show up if the value is not ellipsed.
Fixes #392
Feature

feat(filter-field): Added an overlay if the tag value is being ellipsed.

---

tools/pull-request-labeler/src/main.ts
tools/pull-request-labeler/src/utils/has-merge-ready-label.ts

Adjusts labeler to run on `pr: merge-ready` instead of `pr: lgtm` as part of our change in the pr workflow (See #494).

ci: Change labeler to run on merge-ready instead of lgtm.

---

libs/shared/barista-definitions/src/lib/barista-definitions.ts
tools/barista/src/builder/components.ts
tools/barista/src/transform.ts
tools/barista/src/utils/fetch-strapi-content.ts

Added a Strapi snippet transformer that looks for `<ba-ux-snippet>` tags on content pages and replaces it with the snippet content coming from the CMS.

barista: Get UX snippet content from Strapi.

---

.github/workflows/pull-request-labeler.yml

If we add two types to the actions trigger, like [synchronize, labeled],
github will list it as two actions. One of them fires a little too
early when adding the LGTM label, so the check for its existence fails
and there will be always one failing action on the PR. Only running this
on label, should fix that problem.

ci: Run the labeler on labeled step only.

---

apps/components-e2e/src/components/drawer/drawer.e2e.ts

Fixes #445
As suggested by @lukasholzer in #445 we have slowed down the click in the flaky drawer end to end test.
Apperently the speed at which testcafe and browserstack evaluate these test expressions is faster than any angular change detection cycles can keep up with. 
Test

test(drawer): Slow down e2e test to make it more stable.

---

tools/release/src/publish-release/publish-release.spec.ts
tools/release/src/utils/publish-package.spec.ts

Path expectations were not compatible with windows root path definitions. Provided a  OS agnostic expectation.
Fixes #467
Tests fixed for windows.

test(release): Fixes testing issues on windows with wrong root path expectations

---

components/table/src/table-data-source.ts

In order to give programmatic access to the data that is currently being rendered in the table, we should expose the renderedData BehaviourSubject.
Fixes #497
The question is if we want to expose the renderedData BehaviourSubject directly, or if we shoud introduce an additional member subject. I'm afraid that if we expose the Subject directly used in the table data source, that this could lead to consumers nexting the data in there themselves and therefore removing control from the DtTableDataSource.
Feature

feat(table): Expose currently rendered data from the datasource.

---

components/timeline-chart/src/timeline-chart.html
components/timeline-chart/src/timeline-chart.scss

If a key timing marker was rendered too far to the right end of the
chart, the label associated with it was cut off by the container.
We introduced a threshold of 85%, at which point the label would be
rendered on the left hand side of the marker.
Fixes #495
Bugfix

fix(timeline-chart): Fixes an issue where the label of a key timing marker was cut off.

---

components/copy-to-clipboard/README.md
components/copy-to-clipboard/src/copy-to-clipboard.html
components/copy-to-clipboard/src/copy-to-clipboard.ts
libs/examples/src/copy-to-clipboard/copy-to-clipboard-examples.module.ts
libs/examples/src/copy-to-clipboard/copy-to-clipboard-secondary-button-example/copy-to-clipboard-secondary-button-example.html
libs/examples/src/copy-to-clipboard/copy-to-clipboard-secondary-button-example/copy-to-clipboard-secondary-button-example.ts

We have added an input to the copy-to-clipboard component that is passed
through to the button, which is being used in the copy to clipboard
template. The newly created input controls the variant of the embedded
button.
Fixes #76
Feature

feat(copy-to-clipboard): Added `variant` input to control embedded button variant.

---

components/tag/src/tag-add/tag-add.scss

Fixes https://github.com/dynatrace-oss/barista/issues/509

fix(tag-add): Fixes tag add label when zoom is lower that 100%

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
apps/components-e2e/src/components/filter-field/filter-field.html
apps/components-e2e/src/components/filter-field/filter-field.po.ts
apps/components-e2e/src/components/filter-field/filter-field.ts
components/filter-field/src/filter-field.html
components/filter-field/src/filter-field.scss
components/filter-field/src/filter-field.spec.ts

The clearAll button rendering depended on the filterfield not being
focussed. When the clearAll button was rendered and was clicked, the
cdkFocusMonitor kicked in, set the focus and removed the clearAll button
again. As a result the clearAll button lost its focus, the document
focus was set back to the body and the clearAll was rendered again. The
click event on the clearAll was never fired.
We no longer remove the clearAll from the DOM, but hide it via css
classes. This makes it not lose focus, and results in a more consistent
behavior.
Fixes #435
<hr>
- A feature proposal has been provided, …

fix(filter-field): Fixes an issue with inconsistent clearAll functionality

---

.github/workflows/stale.yml

We have a lot of issues that seem to be lying around for a while without activity. I want to have a bot do the housekeeping and mark stale issues for us. After 30 days without activity, an issue will be marked as stale and after 5 more days without activity or removal of the label the issue gets closed automatically.

ci: Add stale issue workflow

---

apps/components-e2e/src/components/chart/selection-area/selection-area.module.ts
apps/components-e2e/src/components/chart/selection-area/selection-area.po.ts
apps/components-e2e/src/components/chart/selection-area/timestamp/timestamp.e2e.ts
apps/components-e2e/src/components/chart/selection-area/timestamp/timestamp.html
apps/components-e2e/src/components/chart/selection-area/timestamp/timestamp.ts
components/chart/src/selection-area/selection-area.ts

Fixed a regression that was introduced in version 5.1.0 where range could not be
re-opened in a range only mode after it was closed once.
<hr>
guidelines.
Please choose the type …

Fixes an issue where the range could not be re-opened after closing.

---

tools/release/src/stage-release/stage-release.ts

As it is rather complicated to get the local git credentials reliably to
make an authenticated API request to open the PR, we decided to simply
open the compare view on Github in the browser.
Fixes #447
Tooling chore

chore(release): Open pull request after stage release.

---

tools/release/src/stage-release/stage-release.ts
tools/shared/src/interfaces/package-lock-json.ts

When starting a stage release, we can also update the version in the
package-lock.json file.
Fixes #533

chore(release): On stage release, bump package lock version as well.

---

libs/examples/src/loading-distractor/loading-distractor-examples.module.ts

Fixes the broken `DtInputModule` import in the loading-distractor examples module.

chore(examples): Fixes broken loading-distractor module import.

---

components/table/src/simple-columns/favorite-column.scss

After consulting UX, the color of the favorite star on the table should be torquise-800.

fix(table): Fixed invalid fill color for favorite-column icon

---

components/chart/src/chart.ts

Fire the tooltipClose event when the chart is destroyed, so any open
tooltip will close when the parent chart component is destroyed.
Fixes #579
Bugfix

fix(chart): Fixes an issue where the tooltip stayed open when the chart was destroyed.

---

components/filter-field/src/filter-field-tag/filter-field-tag.scss
components/filter-field/src/filter-field.scss

Wrongfully assumed font-smoothing optimization and box-sizing
definitions. Line heights have changed again.
Fixes #573
Bugfix

fix(filter-field): Fixes alignment of filter field tags.

---

components/empty-state/README.md
components/empty-state/src/empty-state-module.ts
components/empty-state/src/empty-state.ts
components/table/README.md
components/table/src/table.html
components/table/src/table.spec.ts
libs/examples/src/empty-state/empty-state-custom-empty-state-table-example/empty-state-custom-empty-state-table-example.html
libs/examples/src/empty-state/empty-state-custom-empty-state-table-example/empty-state-custom-empty-state-table-example.ts
libs/examples/src/empty-state/empty-state-examples.module.ts

Enables the usage of custom empty states. This in turn makes empty states reusable.
Closes #528
Feature

feat(empty-state): Allow custom empty-states

---

libs/examples/src/empty-state/empty-state-custom-empty-state-table-example/empty-state-custom-empty-state-table-example.ts
libs/examples/src/empty-state/empty-state-examples.module.ts
tools/shareable-examples/src/utils/get-classname-from-file.spec.ts
tools/shareable-examples/src/utils/get-classname-from-source-file.ts
tools/shareable-examples/src/utils/get-component-selector-from-source-file.ts
tools/shareable-examples/src/utils/get-example-module.ts

Also changes the generation mechanism for the shareable examples, when
it comes to multiple classes in an example. There is no error thrown any
more, when an example file contains multiple classes. The algorithm
assumes that the last class in the file is the main entry example.
Documentation

chore: Fixes an issue with the custom empty state example.

---

components/table/README.md

Move the "general" snippet for expandable rows up to the example and created a new one for the content limitations.

docs(table): reorganized UX snippets for expandable row.

---

apps/dev/src/tree-table/tree-table-demo.component.html
apps/dev/src/tree-table/tree-table-demo.component.ts
components/tag/src/tag-list/tag-list.ts

When running inside of a tree table, the table row does only get updated
when the differ of the tree table triggers a repaint. As the tag-list
itself marks itself dirty, but change detection never runs for it
because no differ detectable changes happened.
Fixes #603
Bugfix

fix(tag-list): Fixes an issue where the taglist did not get updated within a tree table.

---

components/drawer/src/drawer-container.scss

Increased the z-index of the backdrop from 1 to 3.
Fixes #91
Bugfix

fix(drawer): Fixes an issue where the drawer backdrop did not overlay breadcrumbs elements.

---

components/table/src/simple-columns/simple-column-base.ts
components/table/src/table.ts

Fixed the circular dependency between the table and the simple columns
be removing the QueryList of Simplecolumns on the table to get their
accessorFunctions. Rather than having the SimpleColumns be queried by
the table, the simpleColumns now register their accessor functions at
the table.
Refactor

refactor(table): Refactored dependencies between the table and the simple columns.

---

components/table/src/sort/sort.spec.ts
components/table/src/sort/sort.ts

When the active input for the `[dtSort]` was bound to a member, and this
member was updated, the table did not react to the sorting.
Fixes #619
Bugfix

fix(table): Fixes an issue where the sorting did not update when active binding was updated.

---

components/event-chart/src/event-chart.spec.ts

Event chart tested for path equality and had mismatches in 10<sup>-8</sup> area. Changed the expectation to be less restrictive.
Testcase fixed

test(event-chart): Adjusted a path equality test to be less restrictive.

---

apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
components/chart/src/selection-area/selection-area.ts

fix: Timestamp/range being re-opened on window resize.

---

apps/barista/src/layout/contributors/contributors.html
libs/shared/barista-definitions/src/lib/barista-definitions.ts
tools/barista/src/builder/strapi.ts

Currently github handles are not fetched from Strapi and therefore `undefined`, because we have a naming-mismatch here: `gitHubUser` vs. `githubuser`.
As the property is called `githubuser` (all lowercase) in Strapi, we have to rename it as I don't want to change this field in Strapi. (I crashed the database once when I removed and added a field again and the only difference were lower/uppercase characters...)
Barista bugfix

barista: Fix links to contributors github pages on strapi pages.

---

components/chart/index.ts
components/chart/src/chart-colors.ts

A regression was introduced where we removed the `DT_CHART_COLOR_PALETTE_ORDERED` and the `getDtChartColorPalette` from the public api of the chart. Now they are added again.
<hr>
guidelines.
- Docs have been added / updated (for bug …

fix(chart): Fixes a regression that was introduced with 5.3.0.

---

angular.json

Fixes an issue that the asset folder was not there anymore in our bundle, instead the fonts & favicons where added to the root of the bundle

build(bundle): Fixes asset folder not being there

---

libs/tools/linting/tsconfig.json

Adds the linting rules back to the bundle. 
Any ideas how to validate this constantly? Maybe we should have checks after building the library to verify the built output even on PRs. Since the checks on the release scripts might be too late or insufficient

chore(bundle): Add linting back to the bundle

---

libs/barista-components/schematics/src/ng-add/ng-add.spec.ts
libs/barista-components/schematics/src/ng-add/rules/update-workspace-rule.ts
libs/barista-components/schematics/src/ng-add/schema.json

Fixes an issue where the ng-add schematic was not modifying the angular.json when no defaultProject was present.
Now it will throw an error if no project or defaultProject is provided.
<hr>
guidelines.
- Docs have been added / updated …

fix(schematics): Fixes an issue in the ng-add schematic.

---

libs/tools/barista/src/main.ts

We don't want deployments to pass if the page builder fails somewhere. So we have to exit with 1 here.
Barista

barista: Update exit code when page builder is failing somewhere.

---

libs/barista-components/tag/src/tag-add/tag-add.scss

The tag-add button relied on the user-agent styling of the button. When
inserting a normalize.css or reset.css into your project, the padding on
the button element was changed, which resulted in a broken visual on the
tag-add.
Fixes #640
Other

fix(tag): Fixed an issue with the tag-add button being influenced by UA styles.

---

libs/barista-components/key-value-list/src/key-value-list-item.scss

fix(key-value-list): Change CSS to fix overflow issues fixes #690

---

libs/barista-components/checkbox/src/_checkbox-theme.scss
libs/barista-components/checkbox/src/checkbox.scss
libs/barista-components/radio/src/_radio-theme.scss
libs/barista-components/radio/src/radio.scss
libs/barista-components/switch/src/_switch-theme.scss
libs/barista-components/switch/src/switch.scss

Due to low contrast ratios on between disabled labels on the radio, checkbox and switch we decided in #684 to use the default text color for the labels. This results in a higher contrast ratio between the label and the background, which improves readability.
Fixes #684
Bugfix

fix(radio, checkbox, switch): Disabled labels have have a higher contrast color now

---

angular.json
libs/examples/.stylelintrc

This loosens the constraints a little and eases the process for contributors. There is no real need for this rule to be enforced in the examples

chore(stylelint): Remove selector class matching in examples

---

.github/workflows/slack-barista-production-promotion.yml

Added an action that triggers a webhook to post a message on slack after a release.
Since we don't want to promote barista instantly to production - this action is a reminder to do this after a release is done

ci: Added a release promotion reminder

---

libs/barista-components/drawer/src/sidenav.ts

Corrects the exportAs property in the decorator for the sidenav header

fix(sidenav): Fixes wrong exportAs property for the sidenav-header

---

apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.ts
libs/barista-components/core/src/style/_colors.scss
libs/barista-components/theming/src/colors.ts

The newly introduced color-value `FLAT_WHITE` broke the layout of our icons color wheel in Barista. This filter should fix it.
Barista bugfix

barista: Remove flat white from the icon color wheel.

---

libs/barista-components/drawer/src/sidenav.scss

Changes SideNav Height property from 100% to 100vh

Fixes SideNav height bug when its content is smaller than view

---

libs/tools/barista/src/transform.spec.ts
libs/tools/barista/src/transform.ts

Now content is re-inserted when `innerHtml` is "just" a string without wrapping HTML tags (because otherwise Cheerio can't handle the replacement).
And: added tests.
Barista tools

barista: Insert internal content when not wrapped in tags and add tests.

---

.snyk

Ignore yargs vulerability for now, as we depend on angular/localize to update their dependency because they have a fixed locked version in their dependency tree.

chore: Ignore yargs snyk

---

.github/workflows/barista-preview.yml
apps/barista-design-system/src/components/live-example/live-example.ts
now-preview.json

…side dynamical in ahead of time compilation.
There was an issue with AOT compilation and the way the live-examples were being loaded and initialized. A change in the LoadModuleFactory was required to get this off the ground.
Documentation

Fixes an issue where the live examples where not rendered in AOT

---

apps/barista-design-system/src/shared/services/recently-ordered.service.ts

We only need to store the pathname and no query parameters or hashes for the links to recently visited pages.
Closes #764 
Barista

barista: Fix links to recently visited pages.

---

apps/barista-design-system/src/components/live-example/live-example.ts

This PR fixes an issue where the table example was not displayed in barista. This was due to the function `getNgModuleFromEs6Module` that identifies our modules by its className.

barista: Fixes an issue where the tables example was missing.

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
libs/barista-components/filter-field/src/filter-field.ts

Quickly input free text submissions were ignored if the user was submitting the filter under the
defined debounceTime as we were only updating the value after the debounceTime.
We are now updating the value immediately, but we are handling the submission and necessary updates
to the component after the debounceTime expired.
Fixes #726
Bugfix

fix(filter-field): Fixes an issue with the free-text submission.

---

libs/barista-components/copy-to-clipboard/src/copy-to-clipboard-module.ts
libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.html
libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.ts

Moves copy to clipboard component to Angular's CDK.
Closes. #77

Copy to clipboard: move to CDK instead of current API

---

apps/barista-design-system/src/app/app.ts

In the current implementation of the Barista breadcrumbs the label can change during navigation when pages are not in the cache in the first place and the title and URL part are different. So I would suggest to only use the URL part for the breadcrumbs labels to ensure consistency during navigation.

barista: Simplify breadcrumbs creation.

---

libs/tools/barista/src/builder/icons.ts

the previous logic did only work for root level fills and it's direct children elements. 
The fix provides a deep removal of all fills that are set within the svg code to ensure color-ability.
Other / Documentation

barista: Fixes an issue where not all fills were removed from icon strings.

---

libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.ts

The copied text was undefined when an `input` element was provided.
Fixed by getting the `value` out of the element instead of `textContent`.

fix(copy-to-clipboard): Fixes an issue where copied text is undefined

---

CHANGELOG.md
package-lock.json
package.json

Release for the copy to clipboard regression

chore: Bump version to 6.1.1 w/ changelog

---

apps/dev/src/chart/chart-demo.component.html
libs/barista-components/chart/src/heatfield/chart-heatfield-config.ts
libs/barista-components/chart/src/heatfield/chart-heatfield.html
libs/barista-components/chart/src/heatfield/chart-heatfield.scss
libs/barista-components/chart/src/heatfield/chart-heatfield.spec.ts
libs/barista-components/chart/src/heatfield/chart-heatfield.ts
libs/barista-components/core/src/animations/fade-animation.ts
libs/barista-components/core/src/animations/index.ts

Part of #476
Fade in heatfield overlay
Animate scale of heatfield marker and heatfield backdrop
Changed the start value of the second heatfield in the demo
component to be able to see both heatfields, else they would overlap
<hr>
guidelines.
- Tests for the changes have been added (for bug fixes / …

feat(chart): Add animation for chart heatfield.

---

libs/barista-components/expandable-text/src/expandable-text.scss

Fixes an issue that the default background for the trigger was not set and firefox painted it in a nice gray :D

Expandable-text: Set default background

---

libs/barista-components/overlay/src/mouse-follow-position-strategy.ts
libs/barista-components/overlay/src/overlay-ref.ts
libs/barista-components/overlay/src/overlay-trigger.ts
libs/barista-components/overlay/src/overlay.ts

This PR fixes some long standing issues that keep popping up.
Fixes #772
Fixes #220
The discussion on what to do with the overlay is already quite long. This is the intermediate step of fixing what we have right now the best way I could. 
Plan for the future: Provide default config that can be used with the cdk overlay service and directives. 
And create a "tooltip" (working title) component that would cover 95% percent of the use cases in the template. More will follow in the #86

Overlay: Fix mousemove

---

.circleci/config.yml
.github/workflows/barista-preview.yml
angular.json

Changes the default `build` target of the barista-design-system to the generating of the static pages to be part of the `nx affected:build` command that is running on the circle ci.
This should prevent us of merging code that is not compatible with the universal rendering.
<hr>
guidelines.
- Tests for the …

Change build target of barista to the server side rendering

---

.github/workflows/stale.yml

I think the time of 30 days was too short especially if issues should be taken by contributors outside the team. I've extended the period to 90 days. Let's see how we cope with this change and watch our issue count over time

ci: Increase the time for stale issues

---

.circleci/config.yml

Somehow the docker layer caching is messing up between the two steps while persisting the image for publishing. Lets put them together in a separate workflow to avoid side effects and publishing old dangling images.
<hr>
guidelines.
- …

ci: Build and Publish docker image in a separate workflow.

---

.deployment/barista/Jenkinsfile
angular.json

On the jenkins use the "public-internal" target to build barista with the internal configuration.
Added the string replacement for internal urls inside the configuration.
<hr>
guidelines.
- Docs have been added / updated (for bug fixes / …

barista: Build barista with the internal configuration file.

---

apps/barista-design-system/src/app/components/search/search.ts
apps/barista-design-system/src/pages/overview-page/overview-page.ts
apps/barista-design-system/src/shared/services/search.service.ts

The focuspulling of keyInputs on overview pages, which should help you find things faster on
overview pages, was interfering with the input in the search.
To prevent this, we have moved them to the same keyboardEvent (keyup instead of input), and added a
propagation blocker to the search.
Also added an error handler for the rest call to the search, which was breaking the subscription.
Documentation

barista(search): Fixes an issue with search on overview pages.

---

libs/barista-components/overlay/README.md
libs/barista-components/overlay/src/overlay-module.ts
libs/examples/src/overlay/index.ts
libs/examples/src/overlay/overlay-examples.module.ts
libs/examples/src/overlay/overlay-fullscreen-example/overlay-fullscreen-example.html
libs/examples/src/overlay/overlay-fullscreen-example/overlay-fullscreen-example.scss
libs/examples/src/overlay/overlay-fullscreen-example/overlay-fullscreen-example.ts

In order to use overlays in pages using native fullscreen API its necessary to use `FullscreenOverlayContainer`, this class extends the `OverlayContainer` but listen for fullscreen changes in order to append the overlay to the current element in fullscreen mode.
<hr>
guidelines.
- Tests for the changes …

feat(overlay): use full screen overlay container

---

libs/barista-components/core/src/common-behaviours/id.spec.ts
libs/barista-components/core/src/common-behaviours/id.ts
libs/barista-components/expandable-panel/README.md
libs/barista-components/expandable-panel/src/expandable-panel-trigger.ts
libs/barista-components/expandable-panel/src/expandable-panel.spec.ts
libs/barista-components/expandable-panel/src/expandable-panel.ts
libs/barista-components/expandable-section/README.md
libs/barista-components/expandable-section/src/expandable-section.html
libs/barista-components/expandable-section/src/expandable-section.spec.ts
libs/barista-components/expandable-section/src/expandable-section.ts
libs/barista-components/expandable-text/README.md
libs/barista-components/expandable-text/src/expandable-text.html
libs/barista-components/expandable-text/src/expandable-text.spec.ts
libs/barista-components/expandable-text/src/expandable-text.ts

Fixed an issue where the correct aria attributes where not present on accordion like elements like
expandable-section, expandable-text and expandable-panel.
Fixes #788
Bugfix

Expandables Added aria-controls and aria-expanded

---

.deployment/entrypoint.sh
.github/workflows/barista-preview.yml

If the sha1sum that is stored in the docker image is not matching the local
package-lock.json sha1sum then perform an npm ci.
<hr>
guidelines.
Please choose the type appropriate …

ci(barista-preview): Update node_modules if the sha1sum does not match.

---

.deployment/barista/Jenkinsfile

The internal icons were not found in the assets of the internal design system due to the wrong installed icon pack. Now it replaces the internal icons only with the public ones if the build parameter is set. 
Furthermore, I added the sha1sum check for the package-lock and added an npm ci to run always with the same dependencies as on the branch.
<hr> …

Fixes an issue where the internal icon pack was not displayed in barista

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
apps/components-e2e/src/components/filter-field/filter-field.po.ts
libs/barista-components/filter-field/src/filter-field.ts

Fixes a bug where the range overlay was not closed when an autocomplete should have been shown.
When the autocomplete should be shown, we have added a check if a range is open, and if one is open
we close the range.
Fixes #178
Bugfix

fix(filter-field): Fixes a bug where the range overlay was not closed.

---

libs/examples/src/table/table-observable-example/table-observable-example.html
libs/examples/src/table/table-observable-example/table-observable-example.ts
libs/examples/src/table/table-responsive-example/table-responsive-example.html
libs/examples/src/table/table-responsive-example/table-responsive-example.ts

Introduces little improvements in table documentation.
This example uses an expandable row. Since the expandable-cell was switched to be shown at the left of the table, this example was showing wrongly the columns, and the example code needed to be adapted
- Changed Details column alignment to the left (text alignment)
- Changed header columns creation, to put Details column first, in case of expandable rows
This example allows to dynamically add rows from a source. But as the user doesn't know when it was going to finish (in fact in generates a row every second, during 5 seconds), it feels confusing to not be able to stop that subscription.
- Added a button to cancel the subscription, that gets switched when starting a subscription
- Moved buttons to the top, as otherwise the buttons are …

docs(table): Improved observable and responsive examples

---

.deployment/k8s-barista-builder/Dockerfile
.deployment/k8s-barista-builder/Jenkinsfile

Due to the update of the angular version ngcc is creating a json file in the node_modules,
that gets loaded when no package.json is available in the repo. Because npm is searching for something
similar to the package.json. But the due to the fact that it is no package json the npm install
of the fonts and icons will fail.
Adding a package.json does the trick.

ci: Fix broken barista builder due to update of angular ngcc.

---

apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.html
apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.ts

Since the `symbol` Element inside an `SVG` element doesn't support setting innerHTML dynamically, I had to check if the context is the browser and if not then I don't render that Element
Fixes: #798

Barista icon color wheel bug

---

tsconfig.json

Due to the error warnings when building typescript:
```
WARNING in The basePath "/__w/barista/barista/libs/barista-components/selection-area/index.ts" computed from baseUrl "/__w/barista/barista" and path mapping "libs/barista-components/selection-area/index.ts" does not exist in the file-system.
It will not be scanned for entry-points.
WARNING in The basePath "/__w/barista/barista/libs/tools/environments/src/index.ts" computed from baseUrl "/__w/barista/barista" and path mapping "libs/tools/environments/src/index.ts" does not exist in the file-system.
It will not be scanned for entry-points.
```
The paths are not existing anymore.
<hr> …

build: Cleanup old missing tsconfig paths.

---

DEVELOPMENT.md

The repo structure documentations was outdated and didn't reflect
the actual repo structure any more. With this change the
documentation and actual repo structure are aligned again.
Closes #881

docs: Updates repo structure documentation in guide for developers.

---

apps/barista-design-system/src/components/components.module.ts
libs/examples/src/stepper/stepper-examples.module.ts

Fixes #913
The reactive forms module needs to be provided in the live-examples module because it did not get compiled through the runtime `compileModuleAsync`.
<hr>
guidelines. …

barista(live-examples): Fixes an issue with the stepper examples.

---

libs/barista-components/table/README.md

Removed `Table in use` headline from the table component readme and moved it into database

Removed Table in use headline

---

libs/barista-components/event-chart/src/event-chart-module.ts
libs/barista-components/event-chart/src/event-chart.spec.ts
libs/barista-components/event-chart/src/event-chart.ts

Add duration pipe to x-axis in Event chart. Make number of ticks dynamic based on width
#940 

feat(event-chart): Use duration pipe in axis

---

libs/barista-components/autocomplete/src/autocomplete-trigger.ts

The autocomplete ha been using the scrollstrategy block up until now, but this has prroven to be not
working, when used in scroll containers.
Fixes #926
Bugfix

fix(autocomplete): Fixes an issue with the positioning of the overlay.

---

libs/barista-components/core/src/style/_variables.scss

Updated the disabled color to be $grey-600 based on @ursula-wieshofer recommendation.
Closes #880

style: Darkened disabled color to ensure better contrast.

---

apps/components-e2e/src/components/filter-field/filter-field.html
apps/components-e2e/src/components/filter-field/filter-field.ts
libs/barista-components/filter-field/src/filter-field.html
libs/barista-components/filter-field/src/filter-field.ts

This fixes an issue where the keyboard interaction with the filter field submitted a wrapping form,
breaking the filter field behavior, as the native-form tried to submit. The filter field contains a
single input, which the native form picked up.
The same thing happened with the clear-all button, which triggered the native form submission when
clicked.
Bugfix

fix(filter-field): Fixes an issue with filter field usage in forms.

---

libs/workspace/src/scripts/run-parallel.ts
libs/workspace/src/scripts/util/split-array-into-chunks.spec.ts

When only a few projects are affected then the chunks array could be smaller than the current Node index, in this case, perform an early exit and don't run anything on this node.
Should fix failing build for #920.
<hr>
guidelines.
- Docs …

CI: Fixes an issue where nothing was available to run on this node

---

libs/barista-components/autocomplete/src/autocomplete.scss
libs/barista-components/core/src/style/_form-control.scss
libs/barista-components/core/src/style/_variables.scss
libs/barista-components/filter-field/src/filter-field-range/filter-field-range.scss
libs/barista-components/filter-field/src/filter-field.scss
libs/barista-components/form-field/src/form-field.scss

Reverted the disabledColor to gray-300, as this caused more sideeffects.
There are only browser-default stylings applied to the placeholder texts in our
form and input fields that support them. We should investigate to enhance this in the future.
Fixes #998

style: Adjust styling to respect disabled semantics.

---

angular.json

Ng build had a missing production internal configuration.
Jenkins fails with:
```
12:21:43  node --max_old_space_size=8192 ./node_modules/.bin/ng run barista-design-system:build:production-internal
12:21:43  An unhandled exception occurred: Configuration 'production-internal' is not set in the workspace.
12:21:43  See "/tmp/ng-WcVc4X/angular-errors.log" for further details.
```
<hr>
- If the PR introduces breaking-changes or …

Fixes an issue where the production internal configuration was missing

---

.github/workflows/barista-preview.yml

Added project-id and org-id secrets that are now required for zeit deployments - see project linking in their documentation.

build(preview): Fixed barista preview deployments.

---

libs/barista-components/core/src/util/platform-util.ts
libs/barista-components/core/src/util/type-util.spec.ts
libs/barista-components/core/src/util/type-util.ts
libs/barista-components/formatters/src/bits/bits.ts
libs/barista-components/formatters/src/bytes/bytes.ts
libs/barista-components/formatters/src/bytes/kilobytes.ts
libs/barista-components/formatters/src/bytes/megabytes.ts
libs/barista-components/formatters/src/count/count.ts
libs/barista-components/formatters/src/duration/duration.ts
libs/barista-components/formatters/src/percent/percent.ts
libs/barista-components/formatters/src/rate/rate.ts
libs/barista-components/pagination/src/pagination.ts
libs/barista-components/table/src/simple-columns/simple-number-column.ts

Fixes issue where the `isNumber` util function also returns true if it is a number-string. Added `isNumberLike` function for these number-string cases.
BREAKING CHANGE: `isNumber` now returns false for number strings like `"12"` as expected. Added `isNumberLike` function for these number-string cases.
Breaking change (fix or change that would cause existing functionality to not work as expected)

fix(core): Fixes issue with the `isNumber` util function

---

libs/barista-components/chart/src/chart.ts
libs/examples/src/chart/chart-loading-example/chart-loading-example.ts
libs/examples/src/chart/chart-stream-example/chart-stream-example.ts

This helps us have proper typing in other apps. Some other types that are derived from SeriesOptions don't have a data property which makes another check mandatory. Since all our consumers only have, column, bar, pie, area and area range this scopes it well enough

chore(chart): Change DtChartSeries types to match supported chart types

---

libs/barista-components/table/src/cell.ts
libs/barista-components/table/src/table-data-source.ts
libs/barista-components/table/src/table.ts

After adding the simple columns and adding the ngOnDestroy to the table,
we missed to add the super call the the cdkTable that handled the disconnecting from
the dataSource.
This has now been added again and the datasource is correctly disconnected.
Fixes #1046
Bugfix

fix(table): Fixes an issue where the table tried to render after it was destroyed

---

apps/components-e2e/src/components/filter-field/filter-field.ts
apps/dev/src/filter-field/filter-field-demo.component.ts
libs/barista-components/experimental/quick-filter/src/quick-filter-data-source.ts
libs/barista-components/experimental/quick-filter/src/state/actions.ts
libs/barista-components/experimental/quick-filter/src/state/effects.ts
libs/barista-components/experimental/quick-filter/src/state/selectors.ts
libs/barista-components/filter-field/src/filter-field-data-source.ts
libs/barista-components/filter-field/src/filter-field-default-data-source.ts
libs/barista-components/filter-field/src/filter-field-util.spec.ts
libs/barista-components/filter-field/src/filter-field-util.ts
libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/filter-field/src/filter-field.ts
libs/barista-components/filter-field/src/types.ts
libs/examples/src/filter-field/filter-field-async-example/filter-field-async-example.ts
libs/examples/src/filter-field/filter-field-clearall-example/filter-field-clearall-example.ts
libs/examples/src/filter-field/filter-field-default-example/filter-field-default-example.ts
libs/examples/src/filter-field/filter-field-disabled-example/filter-field-disabled-example.ts
libs/examples/src/filter-field/filter-field-distinct-example/filter-field-distinct-example.ts
libs/examples/src/filter-field/filter-field-programmatic-filters-example/filter-field-programmatic-filters-example.ts
libs/examples/src/filter-field/filter-field-readonly-non-editable-tags-example/filter-field-readonly-non-editable-tags-example.ts
libs/examples/src/filter-field/filter-field-unique-example/filter-field-unique-example.ts

feat(filter-field, quick-filter): Improved typing across the filter-field, it's node definitions, data-sources and the quick-filter component.
BREAKING CHANGE: 
- The filter-field data source as well as the quick-filter data source and their transform methods have Generics in place to define the structure of the passed in data. 
- The filter-fields default data-source no longer takes a generic, as the structure of the data is already defined there. 
- The Node definitions now take optional generics for the consumer to specify the structure of the data.

feat(filter-field): Types

---

CHANGELOG.md
package-lock.json
package.json

This rc includes the change to initialize a DtFilterFieldDefaultDatasource without data.

chore: Bump version to 7.0.0-rc.5 w/ changelog

---

.github/workflows/barista-preview.yml

Based on this answer from the github community, this if should do the trick in identifying if the
pull request is coming from a fork or not. As we still cannot share vercel credentials to forks
we need to limit the preview deployments for internal pull requests.
https://github.community/t5/GitHub-Actions/How-to-detect-a-pull-request-from-a-fork/td-p/57393
Fixes #717
Run from a fork pull request results in a skipped action:

chore: Run previews only on pull requests within the repo.

---

documentation/migration-guide.json
documentation/migration-guide.md

Adds a migration guide page to the components section in barista outlining common changes i encountered in a big app.

docs(migration): Add migration guide for 6 to 7

---

libs/barista-components/style/font-styles.scss

Bugfix: Missing style definition for  h3 (see #1081) has been restored.

fix: Missing styles definition for h3 #1081.

---

.editorconfig
.gitignore

The 4 spaces indent in bazel files is the bazel styleguide that the buildifier is using.
<hr>
guidelines.

build: Update editorconfig to reflect the bazel styleguide.

---

libs/barista-components/filter-field/src/filter-field-range/filter-field-range-trigger.ts

The range/filter-field was already destroyed when the filter-field state-advance was calling
closePanel, which led to an error on the client side.
Fixed by moving it into the check that was already there to prevent the same issue.
Bugfix

fix(filter-field): Fixes an issue where the range caused an error after its destruction.

---

libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
libs/barista-components/filter-field/src/filter-field.html
libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/filter-field/src/filter-field.ts

There was an issue, when setting the filters programatically, that the disabled state of the
filter-field was not applied correctly to all tags.
The solution here was to add an additional input to the tag and logically combine the filter-field
disabled state and the tags own disabled state to reflect this one correctly.
Fixes #1097
Bugfix

fix(filter-field): Fixes an issue where tags where not disabled when the filter-field was.

---

apps/dev/src/checkbox/checkbox-demo.component.html
apps/dev/src/switch/switch-demo.component.html
libs/barista-components/checkbox/src/checkbox.html
libs/barista-components/checkbox/src/checkbox.ts
libs/barista-components/form-field/src/form-field-control.ts
libs/barista-components/form-field/src/form-field.scss
libs/barista-components/form-field/src/form-field.ts
libs/barista-components/switch/src/switch.html
libs/barista-components/switch/src/switch.ts
libs/examples/src/index.ts

Added support for checkbox/switch as a form-field-control.
Fixes #1120

Added support for checkbox/switch as a form-field-control.

---

.bazelrc

To enable personsal bazel configuration add a try-import to the user configuration.
<hr>
guidelines.

ci: Try to import bazelrc.user if exists.

---

tslint.json

Fixes an issue where it was not possible to import from `type:library |  type:shared` in `type:library`.
Other

chore: Fix module boundaries rules for library dependencies and restrict shared imports

---

libs/barista-components/table/src/order/order-cell.scss

Closes #1132
When the table column gets too narrow, the input is still being cut off, but at some point there's just no way around it...

fix(table): Reorder input being cut off in Firefox.

---

.deployment/k8s-barista-builder/Dockerfile

Fixes #1170
Failed to fetch the amd64 binary for node 10 so trying to upgrade to the
latest version as we install the specific node version with `n`. It does
not matter which version we use to download `n`.
Building the image locally worked out great. Let's check if it is working on the ci after we merge this to master.
<hr>
guidelines.
- The commit …

chore: Use later node source to download nodejs.

---

tools/pull-request-labeler/src/main.ts
tools/pull-request-labeler/src/utils/get-approval-count.ts
tools/pull-request-labeler/src/utils/get-pull-request-reviews.ts

When a pull request is already labeld with merge ready and changes are pushed (effectively discarding the reviews) the labeler should run and remove the merge ready and target labels. 
Fixes #1161
Build / Workflow

build: Remove stale labels when approvals are dismissed due to update.

---

.github/workflows/pull-request-labeler.yml

Skipping the pull request labeler on fork prs, as it will not work there due to access restrictions
Build

build: Skip labeler on fork pull requests.

---

apps/dev/src/table-order/table-order-demo.component.html
libs/barista-components/table/README.md
libs/barista-components/table/src/simple-columns/simple-order-column.ts
libs/examples/src/table/table-order-column-example/table-order-column-example.html
libs/examples/src/table/table-order-expandable-example/table-order-expandable-example.html
libs/examples/src/table/table-order-observable-example/table-order-observable-example.html

Deleted leftover `_getIndex` method (`simple-order-column.ts`) and updated all the examples of the reorder tables.

fix(table): Update table reorder examples due to api change.

---

.circleci/config.yml

Changes e2e tests to run on circle instead of browserstack until we have a more stable solution in place. Currently the queue fills up and the issues don't outweigh the benefits anymore
Also added filters to the bazel-ci and win jobs to filter out release branches

ci(e2e): Change e2e tests to run on circle for now

---

apps/dev/src/table-order/table-order-demo.component.html
libs/barista-components/table/README.md
libs/barista-components/table/src/simple-columns/simple-order-column.ts
libs/examples/src/table/table-order-column-example/table-order-column-example.html
libs/examples/src/table/table-order-expandable-example/table-order-expandable-example.html
libs/examples/src/table/table-order-observable-example/table-order-observable-example.html

Fixes #1166 
We went away from simple columns since they cause more problems than they solve. We even had a CD issue after upgrading a patch Angular version. In this case after upgrading from 9.1.6 to 9.1.9. This works the same way and there are no real downsides to this changed approach.

Fix changedetection issue simple order column

---

libs/barista-components/button/src/_button-theme.scss

Visited anchor tags that were represented as buttons were not styled correctly in dark mode.
The necessary selectors have been added to mitigate this problem.
Fixes #1202
Other

fix(button): Fixes an issue where visited a[dt-button] components had the wrong style.

---

.snyk

Since the lodash dep is inside a babel package we cannot really do something here - extending so we can recheck in September.
Moreover this does not affect our bundle at all.

chore(snyk): Remove outdated snyk ignores and extend lodash ignore

---

apps/barista-design-system/src/shared/services/scroll-spy.service.ts
libs/tools/barista/src/builder/strapi.ts

The TOC transformer was not called on strapi only pages.
Additionally a platform check in the spyOn scrollspy was added to fix an issue with window access in
server side rendering.
Fixes #1219
Other

barista: Fixes an issue with the TOC not being generated on strapi-only pages.

---

angular.json
libs/workspace/builders.json
libs/workspace/src/builders/affected-e2e/build.ts
libs/workspace/src/builders/affected-e2e/index.ts
libs/workspace/src/builders/affected-e2e/schema.json
libs/workspace/src/builders/affected-e2e/schema.ts
libs/workspace/src/builders/affected-e2e/utils/find-modules-using-affected-components.ts
libs/workspace/src/builders/affected-e2e/utils/transform-module-path-to-glob.ts
libs/workspace/webpack.config.js

Using the nx affected projects methods to figure out, which componenten modules are affected
and looking for these component modules within the imports of the e2e-testapp-modules
to determine which e2e tests need to be run.
Relates to #601 
Other

build(e2e): Create a custom builder that only passes affected sources into the e2e test environment.

---

package-lock.json
package.json

Update the barista icons dependency to ^7 to have all currently supported icons show up on the overview pages. 
Other

chore: Update dependency to barista icons to ^7.3

---

package.json

After changing the default e2e target to the affected one, the one in the package.json should work without a CIRCLE_CI token.
Other

chore: Correct e2e test command to be runnable without CIRCLECI token

---

libs/design-tokens-ui/input/BUILD.bazel
libs/design-tokens-ui/style/BUILD.bazel
package-lock.json

This originates out of a not rebased pull-request that was merged and where the stylelint targets where not run. so our CI is currently failing.
<hr>
guidelines.
Please choose …

ci: Fix failing stylelint and workspace lint 

---

libs/barista-components/filter-field/src/filter-field-validation.ts
libs/barista-components/filter-field/src/filter-field.ts

Fixes the issue by initializing the hidden FormControl with an empty value instead of null. This in combination with a check for difference when writing the control value fixed the dirty checks of the validator and therefor the flickering. 
I also quickly tried to add an e2e test to this one, but the flickering made it really unstable. I opted to not add an e2e test for this one. 
Fixes #1180
Bugfix

fix(filter-field): Fixes an issue with validation flickering on free text.

---

libs/barista-components/radio/src/radio-group.ts
libs/barista-components/radio/src/radio.spec.ts
libs/barista-components/radio/src/radio.ts

<hr>Fixes an issue where the fallback for the name of the radio group was undefined, resulting in all
radio groups getting the same name. As the radio-groups pass their name down to the individual
radios, a selection in one group interfered with the selection of all groups with the same name.
Fixes #1270
Bugfix

fix(radio): Fixes an issue where the radio-group interfered with other groups.

---

libs/barista-components/table/src/expandable/_expandable-row-theme.scss
libs/barista-components/table/src/expandable/expandable-row.scss

Fixes issue where active indicator on expandable-row is inherited by nested table(s)  expandable-row(s) with indicator
rows where indicator is visible but text have standard color shouldn't be marked with indicator
- [-] I have added tests that prove my fix is effective or that my feature works
- [-] I have added necessary documentation (if appropriate)

[table] limit dtIndicator styles inheritance

---

libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/filter-field/src/filter-field.ts

When deleting an already set filter with the mouse, while the filter field is in the middle of
adding a new filter, the prefix was deleted.
There was a reset of the prefix, when a filter was deleted that is not the current filter, which is
removed in this commit. I could not find where this would have caused trouble.
I added a test for the current behaviour and have all other tests passing.
Fixes #1264
Bugfix

fix(filter-field): Fixes an issue with the infix when deleting a filter while in flight.

---

apps/fluid-dev/src/pages/checkbox/checkbox-page.component.html
libs/fluid-elements/checkbox/src/lib/checkbox.spec.ts
libs/fluid-elements/checkbox/src/lib/checkbox.ts

Co-authored-by: Rowa Audil <rowa.audil@dynatrace.com>
Preventing the scroll behavior on the fluid checkbox keyboard action.

Fluid checkbox prevent scroll

---

libs/barista-components/select/src/select.scss

Can be reproduce here:
https://barista.dynatrace.com/components/select#form-field
Problem is more visible on Firefox

style(select): Fixes border issue when select is used inside form-field

---

libs/barista-components/core/src/style/_form-control.scss
libs/barista-components/core/src/style/_variables.scss
libs/barista-components/experimental/combobox/src/combobox.scss
libs/barista-components/input/src/input.scss
libs/barista-components/select/src/select.scss

style: Unifying placeholder color for input, select and combobox

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
libs/barista-components/filter-field/src/filter-field.ts

Doe to the check that marked the control as dirty only if the value has changed, the validator never ran, when nothing was typed into the control field and only `Enter` was pressed to submit the filter. 
Fixes #1299
Bugfix

fix(filter-field): Fixes an issue with the error validation when trying to submit an empty value.

---

apps/dev/src/form-field/form-field-demo.component.html
apps/dev/src/form-field/form-field-demo.component.scss
apps/dev/src/input/input-demo.component.html
apps/dev/src/select/select-demo.component.html
libs/barista-components/core/src/style/_interactive-common.scss
libs/barista-components/form-field/src/form-field.scss

Fixes #999
Before fix:
https://barista.dynatrace.com/components/form-field#prefix-and-suffix
After fix:

style(input): Fixes extra outlines when places inside form-field

---

libs/barista-components/filter-field/src/filter-field.ts

When the data is newly set, the currentDef of the filter field is reset. But because the range
overlay was open, it held the focus which meant that the stateChanges iteration was not executed,
as this only executes its logic when the filterfield has focus.
Relates to #1256
Bugfix

fix(filter-field): Fixes an issue where the range stayed open when datasource updated.

---

libs/tools/barista/src/builder/strapi.ts
libs/tools/barista/src/transform.spec.ts
libs/tools/barista/src/transform.ts

Adds a transformer that adds headline classes to headline elements
E.g.: `<h1>headline 1</h1>  =>  <h1 class="h1">headline 1</h1>`
P.S: The transformer is only transforming next pages!
Fixes: #1314 
Feature (non-breaking change which adds functionality

chore(transformer): Adds transformation step adding classes to headlines

---

apps/components-e2e/src/components/sunburst-chart/sunburst-chart.e2e.ts
apps/components-e2e/src/components/sunburst-chart/sunburst-chart.html
apps/components-e2e/src/components/sunburst-chart/sunburst-chart.po.ts

A fix was added by making the sunburst chart smaller than the window, which does no longer force
testcafe to scroll the page when clicking / hovering certain items.
Click speed has been reduced to 0.6 to match the hover speed.
Since the chart is no longer filling the whole screen, the click on the body has been replaced with
a click on the root of the chart, which yields the same results.
Fixes #1335
Test

test(sunburst-chart): Fixes an issue with flaky tests on hover.

---

apps/next/src/app/components/nav/nav.html
apps/next/src/app/components/nav/nav.ts
libs/shared/data-access-strapi/src/lib/page.service.ts
libs/tools/barista/src/builder/strapi.ts
libs/tools/barista/src/main.ts
libs/tools/barista/src/types.ts

This PR removes the hardcoded top nav sections and adds a generator to the barista-tools, which creates a file containing the corresponding categories and saves them as a string array.
The top nav then displays that array.
Fixes: #1250

Next(top-nav): Section generator

---

tools/bazel_build_cache/setup_ci_build_cache.sh

The setup ci build cache script had a problem on evaluating the branch pattern as it needs two brackets on a regex equal.
```
➜ shellcheck ./tools/bazel_build_cache/setup_ci_build_cache.sh
In ./tools/bazel_build_cache/setup_ci_build_cache.sh line 7:
if [ "${CIRCLE_BRANCH}" =~ pull\/[0-9]+ ]; then
^-- SC2074: Can't use =~ in [ ]. Use [[..]] instead.
For more information:
https://www.shellcheck.net/wiki/SC2074 -- Can't use =~ in [ ]. Use [[..]] i...
```
<hr>
- There is a meaningful description of the issue in GitHub …

ci(bazel): Fixes an issue on forked pull requrests.

---

tools/bazel_build_cache/setup_ci_build_cache.sh

Writing bash is hard :D the regex has to be in a variable and the variable has to be referenced without double quotes :D
Tried it directly on circleci via ssh on the failing branch
```bash
thebarista@74a305b5ce06:~/barista/tools/bazel_build_cache$ REGEX="^pull\/[0-9]+$"
thebarista@74a305b5ce06:~/barista/tools/bazel_build_cache$ if [[ "${CIRCLE_BRANCH}" =~ $REGEX ]]; then echo "hello world"; fi
hello world
```
<hr>
- If the PR …

ci(bazel): Fix build cache regex on ci.

---

apps/demos/src/side-nav.component.html
apps/demos/src/side-nav.component.ts

- filtered value is saved in session storage, to keep it alive during reloading
- filter now checks example names instead of component group names
- expandable sections are automatically expanded when filtered.
Other

chore: Extend demos sidebar filter to example-names and recovery of filtered key.

---

libs/tools/barista/src/builder/strapi.ts

If public was passed as true, the public query parameter was attached. As the categories model does
not have a public field, the request failed for public builds.
Other

ds: Fixes an issue with fetching categories.

---

.circleci/config.yml

Since we are currently consuming more and more credits we need to switch to a smaller container. 
Not 100% certain large is sufficient for build though

ci: Switch to large instead of x-large containers

---

apps/fluid-dev/src/pages/checkbox/checkbox-page.component.html
apps/fluid-dev/src/pages/switch/switch-page.component.html
libs/fluid-elements/checkbox/README.md
libs/fluid-elements/checkbox/src/lib/checkbox.spec.ts
libs/fluid-elements/checkbox/src/lib/checkbox.ts
libs/fluid-elements/switch/README.md
libs/fluid-elements/switch/src/lib/switch.spec.ts
libs/fluid-elements/switch/src/lib/switch.ts

The native checkbox support a attribute value.
This PR adds that to both the fluid-checkbox and -switch.
Also adds the missing README to the Switch

Adds the value property to the checkboxes and a README to the switch webcomponent

---

libs/barista-components/sunburst-chart/src/sunburst-chart.mock.ts
libs/barista-components/sunburst-chart/src/sunburst-chart.util.spec.ts
libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts

Fixes #1245
The current sunburst uses IDs as a representation for each node. You can easy see the parent of every child by the base of their ID.
e.g.: node with ID `1.3.1` is the child of the node with `1.3`.
The current issue is that the application returns `true` when you ask if `1.12.1` is the child of `1.1`

barista: Modifying isChild condition for avoiding opening wrong nodes

---

libs/barista-components/table/src/expandable/expandable-row.html
libs/barista-components/table/src/expandable/expandable-row.ts

The internal recycling of nodes within a table did not get picked up by the angular animation used
to expand and collapse the rows. We needed to recreate the animation programmatically with the help
of the AnimationBuilder and trigger the animation by hand, each time recreating the player.
Fixes #1353
Bugfix

fix(table): Fixes an issue where an expandable-row had a broken style after table-sorting.

---

libs/barista-components/formatters/src/number-formatter.spec.ts
libs/barista-components/formatters/src/number-formatter.ts

Fixes a bug in the adjustNumber function causing an error when maxprecision is set to a negative number and the input is >= 1

fix(formatters): Fix setting maxPrecision to negative number and input >= 1

---

angular.json
libs/barista-components/tsconfig.lib.json

This was a sideeffect cause by the change in the tsconfig setup for the packagr target in the PR #1143 
Specifically https://github.com/dynatrace-oss/barista/commit/c9eb0041a3f1c0115ba093c539902dfe7fff92f0#diff-ee53cb3a87df9084ed8e74685887582b.

fix(bundle): Fixes imports between submodules in the compiled bundle.

---

libs/tools/shareable-examples/src/utils/get-boilerplate-files.ts

Shareable examples generation on win had some wrong paths.
Fixes #1408

chore: Shareable examples win compatibility.

---

libs/barista-components/experimental/combobox/barista.json

The page on barista does not show the avatars correctly. This should fix it :)

ds: Change to correct githubuser key in json

---

libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.scss

Fixes an issue where long free-text values exceed the border of the overlay.
Fixes #1439

fix(filter-field): Fixes an issue where long free-text values exceed the border of the overlay.

---

libs/barista-components/chart/src/chart.spec.ts
libs/barista-components/chart/src/chart.ts
libs/barista-components/chart/src/utils.ts

When new seriesdata was set into the chart, the visibility settings for each series were not carried
over, as the chart is completely destroyed and reinstantiated every time new data is set.
To mitigate this issue, whenever a new data is set, we now look in the old series dataset for a
series with the same name and carry over the `visible` setting from the previous source.
Fixes #1412
Bugfix

fix(chart): Fixes an issue where series visibility was not retained over new data set.

---

libs/barista-components/empty-state/src/empty-state.ts
libs/barista-components/table/src/table.spec.ts
libs/examples/src/empty-state/empty-state-custom-empty-state-table-example/empty-state-custom-empty-state-table-example.ts

BREAKING CHANGE: Remove ViewportResize and let the resize observer handle the layout changes. Therfore the custom empty state base class is not used anymore and is deleted now.
<hr>
guidelines.
- Docs have been added / updated (for bug …

feat(empty-state): Remove deprecated CustomEmptyStateBase class.

---

libs/barista-components/experimental/combobox/src/combobox.ts

fix(combobox): Fixes an issue where the value was reset.

---

apps/dev/src/formatters/formatters-demo.component.html
libs/barista-components/formatters/src/duration/duration-formatter-constants.ts
libs/barista-components/formatters/src/duration/duration-formatter-utils/convert-to-unit.ts
libs/barista-components/formatters/src/duration/duration-formatter-utils/index.ts
libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result-precise.ts
libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result.ts
libs/barista-components/formatters/src/duration/duration-functions-tests/convert-to-unit.spec.ts
libs/barista-components/formatters/src/duration/duration-functions-tests/transform-result-precise.spec.ts
libs/barista-components/formatters/src/duration/duration-functions-tests/transform-result.spec.ts
libs/barista-components/formatters/src/duration/duration.spec.ts

The duration formatter previously used millisecond as the base unit which resulted in many workarounds due to buggy float number calculations.
Fixes #1395

fix(duration-formatter): Fixes the calculation

---

libs/barista-components/highlight/src/highlight.ts
libs/examples/src/autocomplete/autocomplete-default-example/autocomplete-default-example.ts
libs/examples/src/filter-field/filter-field-default-example/filter-field-default-example.ts

When the highlight was wrapped in an option in the filter field and out of view, it was not
initially rendered, but broke the layout of the autocomplete overlay by being too small.
When running and forcing highlight after the init a first time, the value will be mirrored into the
visible span, therefor giving it the size it should eventually have.
Fixes #1420
Bugfix

fix(highlight): Fixes an issue where the highlight would break layouts.

---

jest.config.js
libs/barista-components/expandable-section/src/expandable-section.html
libs/barista-components/expandable-section/src/expandable-section.spec.ts
libs/barista-components/expandable-section/src/expandable-section.ts
tools/bazel_rules/jest/jest-runner.js

fix(expandable-section): Fixes an issue where the inital state set via dom attribute for `disabled` and `expandable` is not applied correctly.
Fixes #1489
Fixes #1472

fix(expandable-section): Fixes an issue where the inital state set via dom attribute for disabled and expandable is not applied correctly.

---

libs/barista-components/button/src/_button-theme.scss

According to the UX guidelines hover/active states should not enforce strict background colors, but just some opacity.
- [*] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [*] Lint and unit tests pass locally with my changes
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] I have added necessary documentation (if appropriate)
@ffriedl89 @lukasholzer FYI

fix(button): Fixes an issue with secondary theme hover and active state

---

libs/barista-components/experimental/combobox/src/combobox.ts
libs/barista-components/select/src/select.spec.ts
libs/barista-components/select/src/select.ts

<hr>
Removed deprecated function `getDtSelectNonFunctionValueError()` in select component and replaced it with an error log.
> I also do not understand why this was deprecated in the first place. Because these changes can lead to a broken component, if the user provides something other than a function. (In my opinion it should rather be changed in the combobox to the solution we have here in the select).
@lukasholzer Any input on this? I haven't touched the select component before, so I cannot answer this question.

feat(select): Remove deprecated function in select component

---

apps/components-e2e/src/components/autocomplete/autocomplete.e2e.ts
apps/components-e2e/src/components/autocomplete/autocomplete.po.ts
apps/components-e2e/src/components/select/select.e2e.ts
apps/components-e2e/src/components/select/select.po.ts
apps/dev/src/select/select-demo.component.html
libs/barista-components/autocomplete/src/autocomplete.ts
libs/barista-components/core/src/option/option.scss
libs/barista-components/core/src/option/option.ts
libs/barista-components/select/src/select.ts

@ffriedl89 @thomaspink 
Tom and I have come up with this sollution for the filter field selection "bug" we have.
The DtOption has a subject containing the item that is hovered on mousemove which the autocomplete subscribes to setting the active item.
Any thoughts?
Fixes #1070

fix(option): Fixes multiple selected bug when using keyboard and mouse

---

WORKSPACE
rules_nodejs-npm-install+2.0.3.patch

Currently `npm_install` cannot access npm binaries in postinstall script on windows. With this small patch the postinstall script is using the global npm executable that is set via nodejs. 
Patch for https://github.com/bazelbuild/rules_nodejs/issues/2144.

build(bazel): Fix npm install on windows.

---

apps/dev/src/tree-table/tree-table-demo.component.ts
libs/barista-components/tree-table/README.md
libs/barista-components/tree-table/src/tree-table-row.scss
libs/examples/src/tree-table/tree-table-default-example/tree-table-default-example.ts

This fixes the overflow issue when putting long texts into the info-group part of the tree-table by setting a width and showing the whole text when hovering over the text/cell.
fixes #1502

fix(tree-table): Fixes overflow when info-group contains long texts

---

libs/barista-components/button-group/src/button-group.ts
libs/barista-components/core/src/common-behaviours/color.ts

Typescript can now differentiate between properties a get Accessors in the type declarations of the mixins so it broke with the new update
Fixes #1577
<hr>
guidelines.
Please …

Fix a regression that was introduced with the update to the new typescript version.

---

libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/filter-field/src/filter-field.ts

fix(filter-field): Fixed UX problem where text that wasn't applied to the filter would remain after losing focus.

---

apps/dev/src/filter-field/filter-field-demo.component.html
apps/dev/src/filter-field/filter-field-demo.component.ts
libs/barista-components/filter-field/src/filter-field.ts

fix(filter-field): Fixes an issue where custom tag parsers are not applied on filters set initially.
Fixes #1591

fix(filter-field): Fixes an issue where custom tag parsers are not applied on filters set initially.

---

tools/design-tokens/build/src/utils/find-common-root-path.ts

Pull Request
Fix bazel build on windows. Specified path contains only /. So splitting / is ok.
Type of PR

build(design-tokens): Fix bazel build on windows

---

libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/highlight/src/highlight.ts

When not using Ivy but View Engine, MS Edge did not display any suggestions.
Closes #1558
Maybe running UI tests with `"angularCompilerOptions": { "enableIvy": false }` could prevent problems with the old engine in the future.

fix(filter-field): Fixes an issue where suggestions are not displayed in MS Edge

---

libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/filter-field/src/filter-field.ts

Reverts dynatrace-oss/barista#1585
Fixes dynatrace-oss/barista#1632
---
The code caused the filter field to not properly select suggestion values when typing in filter text any more.
This seems to be caused by the fact, that the filter field does not only loose focus when the user clicks outside of the filter field but also when the user selects a prefiltered value from the suggestion dropdown.
IMHO clearing the text input when the filter field looses focus is an ux improvement and should not be seen as a bug, thus not being included in any patch version.
I would propose to re-open #1572 and postpone this change to `8.1.x`, keeping this regression in mind when re-implementing.

Revert "fix(filter-field): Fixed UX problem where text that wasn't applied to the filter would remain after losing focus."

---

apps/fluid-dev/src/pages/button-group/button-group-page.component.html
libs/fluid-elements/button-group/README.md
libs/fluid-elements/button-group/src/lib/button-group-item/button-group-item.ts
libs/fluid-elements/button-group/src/lib/button-group/button-group.spec.ts
libs/fluid-elements/button-group/src/lib/button-group/button-group.ts
libs/fluid-elements/checkbox/src/lib/checkbox.ts
libs/fluid-elements/switch/src/lib/switch.ts
libs/fluid-elements/tab-group/src/lib/tab/tab.ts

Adds PropertyValue instead of a Map and fixes the disabled state of the button-group removing comments in the CSS

WebComponents: Adds PropertyValue to aria labeling and fixes disabled in button-group

---

libs/barista-components/micro-chart/README.md
libs/examples/src/micro-chart/micro-chart-columns-example/micro-chart-columns-example.html
libs/examples/src/micro-chart/micro-chart-columns-interpolated-example/micro-chart-columns-interpolated-example.html
libs/examples/src/micro-chart/micro-chart-default-example/micro-chart-default-example.html
libs/examples/src/micro-chart/micro-chart-interpolated-example/micro-chart-interpolated-example.html
libs/examples/src/micro-chart/micro-chart-stream-example/micro-chart-stream-example.html

Remove the customizable tooltip references from the micro-chart documentation. It will not be possible in the future to have customizable tooltip for the micro chart, only the default one. The references to hat approach has to be removed from the documentation.

chore: Remove the customizable tooltip references from the micro-chart doc

---

.bazelrc
.circleci/config.yml
WORKSPACE
package-lock.json
package.json
patches/jest-haste-map+26.1.0.patch
patches/stylelint+13.2.1.patch
postinstall.js
rules_nodejs-launcher+2.0.3.patch
tools/bazel_rules/jest/jest-resolver.js
tools/bazel_rules/jest/jest-runner.js
tools/bazel_rules/stylelint/junit-formatter/parse-suite.ts
tools/bazel_rules/stylelint/run-stylelint.ts
tools/bazel_rules/stylelint/stylelint_macro.bzl
tools/scripts/README.md
tools/scripts/stylelint.js
tools/scripts/utils/execute-bazel.js

This issue is due to some legacy run files linking where a manifest file was expected where it was not on windows.
It constantly failed with:
```
ERROR: Manifest file c:\Users\ADMINI~1\_BAZEL~1\rgyky3dz\execroot\EXAMPL~1\bazel-out\x64_windows-fastbuild\bin\test.bat.runfiles\examples_jest\test.bat.runfiles_manifest does not exist.
```
Issue described here: https://github.com/bazelbuild/rules_nodejs/issues/1454
The only thing that might be needed under windows is a `.bazelrc.user` where the output path is set as there might be some issues with the max path length on windows.
https://docs.bazel.build/versions/3.5.0/windows.html#avoid-long-path-issues
```
startup --output_user_root=C:/tmp
```
<hr>
To ensure a fast process …

Fixes an issue where bazel could not create runfiles on windows.

---

apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.ts

Fixes an issue where the PNG conversion when downloading icons failed on Firefox, causing an empty PNG to be downloaded (see #1633).
Bugfix

chore(barista): Add workaround for PNG icon downloads on Firefox

---

libs/barista-components/breadcrumbs/barista.json

Breadcrumbs are still marked _work in progress_. Is this still the case?
Documentation

barista: Breadcrumbs are no longer work in progress.

---

libs/barista-components/tree-table/README.md
libs/barista-components/tree-table/src/tree-table-row.scss
libs/barista-components/tree-table/src/tree-table-toggle-cell.html
libs/barista-components/tree-table/src/tree-table-toggle-cell.scss

Reverts the changes made in the PR's #1564 and #1626 from issue #1502  back to the original behavior of hiding the overflow and setting `text-overflow: ellipsis`
fixes: #1681

fix(tree-table): Reverts changes causing unwanted behaviour expanding text on hover

---

libs/barista-components/autocomplete/src/autocomplete.scss
libs/barista-components/core/src/option/option.html
libs/barista-components/core/src/option/option.scss
libs/barista-components/core/src/option/option.ts

The autocomplete was behaving weirdly in firefox (fixes #1651)
The text in the option was cut off because the scrollbar is rendered identical to the scrollbar on mac maschines. It overlaps the content beneath it so it shrinks the option element. To accomadate, we added a firefox only selector adding 20px to the width of the autocomplete.
This will result in a wider autocomplete than before when there is no scrolling but solves the truncation of the options.
Thank you @bardosmisi for the support on this issue.

fix(option): Fixes truncate issue in firefox

---

apps/components-e2e/src/components/button-group/button-group.e2e.ts
apps/components-e2e/src/components/button-group/button-group.po.ts
libs/barista-components/button-group/README.md
libs/barista-components/button-group/src/_button-group-item-theme.scss
libs/barista-components/button-group/src/button-group.ts
package-lock.json
package.json

I've updated axe-core to v4.0.2 and then let the a11y tests run locally and on the CI a few times without errors thrown.
This resulted in the ButtonGroupItem component to fail due to the a11y rule 
`Elements must only use allowed ARIA attributes`, so I changed the attribute from `aria-selected` to `aria-checked`.
Fixes: #1680 

fix(a11y): Fixes flaky combobox a11y test and changes aria attribute in button-group-item

---

libs/barista-components/stepper/src/stepper.ts
package-lock.json
package.json

There has been a change in the @angular/cdk that breaks our table and tree-table examples.
Mistakenly not annotated they introduced a breaking change into the @angular/cdk version 10.2
See here for further details on what the breaking change is and that it got solved with a patch version (10.2.4) https://github.com/angular/components/pull/20425
fixes #1628 

fix(table, tree-table, stepper): Fixes breaking changes from @angular/cdk

---

.buildkite/baristaPipeline.yml

(this prevents 'Permission denied' errors in next build)
<hr>

ci: Shutdown bazel server after build on windows 

---

apps/components-e2e/src/components/quick-filter/quick-filter/quick-filter.html
libs/barista-components/drawer/src/drawer.html
libs/barista-components/drawer/src/drawer.ts

With a lot of content in the drawer-content, the drawer-body was changing size due to the flex container around it.
Keeping track of the width when closing and setting it as a min and max width boundary, keeps the drawer-body from relayouting and prevents the drift.
Fixes APM-266068
Bugfix

fix(drawer): Fixes an issue of width-drift when closing the drawer.

---

apps/demos/src/app-routing.module.ts
apps/demos/src/barista-examples.a11y.ts
apps/demos/src/nav-items.ts
libs/barista-components/filter-field/README.md
libs/examples/src/filter-field/filter-field-examples.module.ts
libs/examples/src/filter-field/filter-field-infinite-data-depth-example/filter-field-infinite-data-depth-example.html
libs/examples/src/filter-field/filter-field-infinite-data-depth-example/filter-field-infinite-data-depth-example.ts
libs/examples/src/filter-field/index.ts
libs/examples/src/index.ts

Some users didn't know that data sources in the filter field could be nested.
This PR provides an example that outlines this use case

docs(filter-field): Adds docs explaining nesting nodes

---

libs/barista-components/context-dialog/README.md
libs/barista-components/context-dialog/src/context-dialog.scss
libs/barista-components/context-dialog/src/context-dialog.ts

You can now set the maxWidth as part of the DT_CONTEXT_DIALOG_CONFIG token and it will properly be reflected on the overlay.
<hr>
guidelines.

feat(context-dialog): Simplifies overriding the maxWidth of the overlay.

---

libs/tools/barista/src/generators/category-navigation.ts

Creating sub pages for components in the cms broke the generation of the navigation. The added filter checks to only iterate files in the respective section folders, to not break the generation of the navigation. 
This is a prerequisite for APM-266090
Documentation

barista: Allow subpages to be created in strapi without breaking the navigation.

---

apps/components-e2e/src/components/combobox/BUILD.bazel
apps/components-e2e/src/components/combobox/combobox.e2e.ts
apps/components-e2e/src/components/combobox/combobox.html
apps/components-e2e/src/components/combobox/combobox.po.ts
apps/components-e2e/src/components/combobox/combobox.ts
apps/demos/src/barista-examples.a11y.ts
libs/barista-components/experimental/combobox/src/combobox.ts

Fixes an expression changed after checked error when writing the initial selection into the combobox (and also when encapsulated within a ChangeDetectionStrategy.Default.
Fixes APM-266666
Bugfix

fix(combobox): Fixes an issue with the combobox where the initial value caused a change detection error.

---

apps/components-e2e/src/components/filter-field/filter-field.po.ts
apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
libs/barista-components/filter-field/src/filter-field-util.ts

When setting the filters programmatically, as the quickfilter does when a filter is set, the
retreival of set filters breaks.
The programmatic setting of the filters runs a function called `tryApplyFilters`, which looks in the
datasource and async dataset for the correct filters.
For some reason, the root of the async def was pushed twice, resulting in a wrong path and a wrong
id.
@thomaspink do you remember the reasoning on why the `def` and `asyncDef` where pushed to the array in the partial async case.
Event with the change in this PR, the partial async example behaves the same and all tests are passing.
Fixes APM-267380
Bugfix

fix(filter-field): Fixes an issue with async data and programmatically set filters.

---

apps/dev/src/indicator/indicator-demo.component.ts
libs/barista-components/indicator/README.md
libs/barista-components/indicator/src/indicator.scss
libs/barista-components/indicator/src/indicator.spec.ts
libs/barista-components/indicator/src/indicator.ts
libs/barista-components/table/src/_row-theme.scss
libs/barista-components/table/src/cell.ts
libs/barista-components/table/src/row.ts
libs/barista-components/tree-table/src/_tree-table-row-theme.scss
libs/examples/src/indicator/indicator-default-example/indicator-default-example.html
libs/examples/src/indicator/indicator-default-example/indicator-default-example.ts
libs/examples/src/table/table-problem-example/table-problem-example.ts

This PR adds a _recovered_ state  to the indicator.  
_recovered_ is indicated using the same green color theme already used in the bar indicator.

feat(indicator): add indicator theme 'recovered' (green indicator)

---

libs/barista-components/filter-field/src/filter-field-edit-mode.spec.ts
libs/barista-components/filter-field/src/filter-field.ts

When starting to edit a single tag within the filter-field and then deleting the filter with the
keyboard [backspace,delete], the filterChanges event was not dispatched. At this stage, the filter
did not count as actually applied, because it was elevated into the currently edited filter.
Fixes APM-268757
Bugfix

fix(filter-field): Fixes an issue where the filterChanges event was not triggered.

---

libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.scss
libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
libs/barista-components/filter-field/src/filter-field.spec.ts
libs/examples/src/filter-field/filter-field-readonly-non-editable-tags-example/filter-field-readonly-non-editable-tags-example.ts

Fixes APM-269127
Improves the contrast ratio and differentiation of the various states of a tag. Here is the comparison table what is set for the example. Free text examples are added additionally, as the styling of the quotes is sometimes different.
| Tag | Editable | Deletable |
| --- |:---:|:---:| 
| AUT: Linz | false | false |
| AUT: Vienna | true | false |
| AUT: Graz | false | true |
| AUT: Bregenz | true | true |
| USA: Miami |false |false |
| USA: Austin | true| false|
| USA: San Diego |false |true  |
| USA: Bend |true | true|
Two major things that have changed. If a tag is whether deletable and editable, it is considered as disabled. The `X` button on the disabled tag was removed completely. 
Colors of key and value elements have been adjusted to gray / turquoise depending on the …

fix(filter-field): Fixes an issue with confusing disabled styles.

---

libs/barista-components/drawer/src/drawer-container.scss
libs/barista-components/quick-filter/src/quick-filter.scss

Prevents the quickfilter sidebar from growing and shrinking randomly based on the content of the `quick-filter content section`. 
Detailed in APM-270014
Bugfix

fix(quick-filter): Fixes an issue with varying width of the quick-filter sidebar.

---

libs/barista-components/drawer/src/drawer.html
libs/barista-components/drawer/src/drawer.ts

Fixes two drawer issues. 
One where there was an initial padding when initializing the drawer as closed. (When fixing the drift issue a couple of weeks back, I applied the min/max width setting to the wrong container #1791 )
Second was a complete breakdown of the render when initilalising the drawer `open="false"` without binding the value. 
Apm 270469 
Bugfix

Drawer: Fix padding issue in drawer

---

libs/barista-components/table/src/table.ts

When setting the data to an empty array within a setTimeout, the table did not show the empty state without a changeDetection being triggered (click somewhere). 
Bugfix

fix(table): Fixes an issue with the empty state not showing up without change detection.

---

libs/barista-components/drawer/src/drawer.ts

When toggling the drawer programmatically, it could happen that changeDetection was not run on the drawer (setTimeout / defer). The mark for check is necessary in these cases.
Bugfix

fix(drawer): Fixes an issue where changeDetection was not triggered.

---

apps/components-e2e/src/components/combobox/combobox.e2e.ts
apps/components-e2e/src/components/combobox/combobox.html
apps/components-e2e/src/components/combobox/combobox.po.ts
apps/components-e2e/src/components/combobox/combobox.ts
libs/barista-components/experimental/combobox/src/combobox.ts

The combobox was not able to handle a value reset over programmatic input setting. 
Fixes APM-272145
Bugfix

fix(combobox): Fixes an issue with programmatic setting of the value to null.

---

apps/dev/src/filter-field/filter-field-demo.component.ts
libs/barista-components/filter-field/README.md
libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/filter-field/src/filter-field.ts
libs/examples/src/filter-field/BUILD.bazel
libs/examples/src/filter-field/filter-field-unique-example/filter-field-unique-example.ts

The interaction state represents whether the user currently is interacting with the filter-field or not.
_Adds a Member `interactionState` and an Output `interactionStateChange`_
- Feel free to give feedback on the naming!

feat(filter-field): Interaction-state

---

libs/barista-components/autocomplete/src/autocomplete-trigger.ts
libs/barista-components/autocomplete/src/autocomplete.ts

Fixes APM-275314
Adds paged scrolling behavior to the autocomplete listbox. This is not in the listbox aria keyboard specs, but nevertheless could be quite helpful to navigate long ists. 
PageUp / PageDown only change the scroll position of the listbox and not the actually highlighted selection (actual selection is handled in the keymanager). 
Feature

feat(autocomplete): Added paged keyboard scrolling for autocomplete.

---

apps/dev/src/sunburst-chart/sunburst-chart-demo.component.scss
apps/dev/src/sunburst-chart/sunburst-chart-demo.component.ts
libs/barista-components/sunburst-chart/src/sunburst-chart-segment.ts
libs/barista-components/sunburst-chart/src/sunburst-chart.html
libs/barista-components/sunburst-chart/src/sunburst-chart.spec.ts
libs/barista-components/sunburst-chart/src/sunburst-chart.ts

Currently tooltip gets repositioned on segment click and before any other mouse move.
Now the overlay has been moved to the segment without manual handling.
Also, to preserve the possibility of opening the overlay from the outside I've kept the functionality in the main component

fix(sunburst-chart): Fix tooltip flicker on click

---

apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.e2e.ts
apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.html
apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.po.ts
apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.ts
apps/dev/src/stacked-series-chart/stacked-series-chart-demo-data.ts
apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.html
apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.ts
libs/barista-components/stacked-series-chart/README.md
libs/barista-components/stacked-series-chart/index.ts
libs/barista-components/stacked-series-chart/src/_stacked-series-chart-shared.scss
libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
libs/barista-components/stacked-series-chart/src/stacked-series-chart.scss
libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts

Feature request for **APM-275897**
**Current behaviour**
The labels right now are parallel to the X axis on the `column` mode, which makes impossible to keep the chart in a more compact view since the labels would overlap or the words would get cut from a break line
[![Image from Gyazo](https://i.gyazo.com/79da0b6d698b1b1de5527dc63b9a82a5.gif)](https://gyazo.com/79da0b6d698b1b1de5527dc63b9a82a5)
**Expected behaviour**
Rotate the labels 45 degrees so more can fit and we can make the chart more compact, useful when there are a lot of labels and the size is limited, avoiding the overflow until a certain point (greater than it was before).
[![Image from Gyazo](https://i.gyazo.com/826bf05c03a372a6ebaed22949f61371.gif)](https://gyazo.com/826bf05c03a372a6ebaed22949f61371)
**UPDATE** …

feat(stacked-series-chart): Add compact mode.

---

libs/barista-components/slider/src/slider.ts

change event was bleeding through from the wrapped input to the root component of the slider.
Bugfix

fix(slider): Fixes an issue with the change event of the input bleeding to the root component.

---

libs/barista-components/radial-chart/README.md
libs/barista-components/radial-chart/src/radial-chart.html
libs/barista-components/radial-chart/src/radial-chart.ts
libs/barista-components/radial-chart/src/utils/radial-chart-interfaces.ts
libs/barista-components/radial-chart/src/utils/radial-chart-utils.spec.ts
libs/barista-components/radial-chart/src/utils/radial-chart-utils.ts

This PR fixes the issues with the **radial-chart** legend percentages described in #1959 .

fix(radial-chart): Display of rounded percentage with precision

---

apps/demos/src/app-routing.module.ts
apps/demos/src/barista-examples.a11y.ts
apps/demos/src/nav-items.ts
libs/barista-components/experimental/combobox/README.md
libs/barista-components/experimental/combobox/src/combobox.ts
libs/examples/src/combobox/BUILD.bazel
libs/examples/src/combobox/combobox-examples.module.ts
libs/examples/src/combobox/combobox-form-control-example/combobox-form-control-example.html
libs/examples/src/combobox/combobox-form-control-example/combobox-form-control-example.ts
libs/examples/src/combobox/index.ts
libs/examples/src/index.ts

<hr>
Add an example to show how the combobox can be bound to a form control. 
The DefaultValueAccessor
directive as an alternative for now, in order to prevent value accessor errors. 
Fixes https://dev-jira.dynatrace.org/browse/APM-283084. <br>

chore(combobox): Add example for form control usage.

---

apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.html
libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts

**In this PR**
[APM-282124] Clearing selection from the outside was not working on the new stack mode. Issue fixed and a button to check it on dev environment added**
You can close https://github.com/dynatrace-oss/barista/pull/1971 and merge this one

fix(stacked-series-chart): Clear when using stack mode.

---

CHANGELOG.md
package-lock.json
package.json

- **combobox:** Fixes an issue with the arrow positioning on safari.
([a3f2535](https://github.com/dynatrace-oss/barista/commit/a3f25352e67c48b124a6999ec8dd299820216bf4))
- **expandable-section:** Fixes an issue where toggling the expandable section
was triggering a form submission.
([8388bd0](https://github.com/dynatrace-oss/barista/commit/8388bd02875e436bbe8ab26c006edada49a4a5cb))
- **filter-field:** Improving isOptionSelected method for async values.
([8e352fa](https://github.com/dynatrace-oss/barista/commit/8e352fa61173307a56b42c1646ee33c18e17cc73))
- **filter-field:** Fixes jumping of filters when the edit state changes.
([54dff6e](https://github.com/dynatrace-oss/barista/commit/54dff6e11eff75001c30bc44f8c42f5de77d1d3d))
- **quick-filter:** Fixes default search in the quick-filter …

chore: Bump version to 9.2.0 w/ changelog

---

libs/barista-components/filter-field/src/filter-field-util.ts

Fixes the defaultSearch not being displayed anymore after regression by version 9.3.0

fix(filter-field): Fixes the defaultSearch not being displayed anymore

---

libs/barista-components/overlay/src/overlay.ts

Somehow the clientLeft and clientTop values where constantly reported as 0. Falling back to boundingClientRect should do the trick.
Fixes APM-291653
Bugfix

fix(overlay): Fixes an issue with the overlay origin positioning.

---

libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts

- Replacing Angular's `SelectionModel` object by a custom Map in order to have a better handling for object comparison, therefore functionalities like `toggle` values are correctly handled.
- Improve async object comparison.
- Updating test for current implementation

fix(filter-field): Avoid duplicity for multiselect edit mode.

---

libs/barista-components/key-value-list/src/key-value-list-item.html
libs/barista-components/key-value-list/src/key-value-list.spec.ts

In chrome, when double clicking the last word of the value, it selected the first part of the value as well. Because the value is set to display: inline; which chrome interprets as a continuous word.
With the inserted 0-width white space, this forces chrome to separate the words.
Bugfix

fix(key-value-list): Adds a zero-width white space to split the key from the value.

---

libs/barista-components/overlay/src/overlay-ref.ts

If a pinned tooltip is closed automatically by scrolling then it cannot be reopend.
Can be reproduced [here](https://barista.dynatrace.com/components/overlay) by:
1 - clicking on the first overlay trigger
2 - Scrolling down to close the overlay
3 - Trying to open the overlay again
Fixes APM-291840
Bugfix

fix(overlay): Overlay never reopens if closed via scrolling.

---

apps/dev/src/sunburst-chart/sunburst-chart-demo.component.ts
libs/barista-components/sunburst-chart/BUILD.bazel
libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts

- Replacing JavaScript's strict equality (`===`) by Lodash's `isEqual` which works properly for object comparison.

fix(sunburst-chart): Solving object comparison for initial selection.

---

libs/barista-components/context-dialog/src/context-dialog.scss

At some point the dt-context-dialog-content was the last element if there was no footer and the css selector corrected against the overflow situation with the close button.
After a html structure change, the content was never the last child, as the button was rendered unconditionally afterwards.
Bugfix

fix(context-dialog): Fixes an overflow issue with long content when positioning moved to bottom.

---

libs/barista-components/confirmation-dialog/src/confirmation-dialog.scss

Changes the padding to margin and drops the top spacing
Bugfix

fix(confirmation-dialog): Fixes an issue with blocking space above the confirmation dialog.

---

libs/barista-components/table/src/order/order-directive.ts

fix(table): Fixes an issue with rapid unsubscription if the dtOrder is immediately destroyed.

---

libs/barista-components/filter-field/README.md
libs/barista-components/filter-field/index.ts

Export members to customize EditionParserFunction:
- functiont type, token, default function.
- otherwise the approach currently described in the doc cannot work.
Correct filter-field docs:
- add omitted customTagParser to inputs section.
- correct wrong types/tokens mentioned for customEditionParser.
Bugfix (non-breaking change which fixes an issue) 

fix(filter-field): EditionParser not exported.

---

libs/barista-components/overlay/src/overlay-module.ts

When using the overlay in two or more modules that are being loaded lazily, there are multiple overlay containers created, which mess with the z-index order of the created overlays within.
Thanks @bartoszbobin  @piotrl for figuring this out.
Fixes APM-275769
Bugfix

fix(overlay): Fixes an issue where multiple overlay container were created when lazyloading the module.

---

apps/components-e2e/src/components/sunburst-chart/BUILD.bazel
apps/components-e2e/src/components/sunburst-chart/sunburst-chart.module.ts
libs/barista-components/filter-field/src/filter-field.ts
libs/examples/src/sunburst-chart/BUILD.bazel
libs/examples/src/sunburst-chart/sunburst-chart-examples.module.ts

- Fixing method for generating multiselect filter type uid, for avoid creating a non-existent hierarchy.
- Clearing the list of selected options in multiselect when the field is deleted
- Adding **DtOverlay as sunburst dependency**

Fix Filter-field multiselect id generation; Clearing multiselect on delete

---

libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts

This PR includes functionality to enable the tracking of hover events on the stacked series chart. This component now presents two output events, **hoverStart** and **hoverEnd**, which emit the data of the series the user has hovered over, and wether the hover event took place on the graph itself or on the legend. When the event takes place over the graph, the outputs will include data on both the series and the stack.

Add hover events to stacked series graph

---

libs/barista-components/radial-chart/src/radial-chart.html
libs/barista-components/radial-chart/src/radial-chart.spec.ts
libs/barista-components/radial-chart/src/radial-chart.ts

This PR includes functionality to enable the tracking of hover events on the Radial (pie chart). This component now presents two output events, **hoverStart** and **hoverEnd**, which emit the data of the series the user has hovered over, and wether the hover event took place on the graph itself or on the legend.

Add hover events to radial graph

---

libs/barista-components/sunburst-chart/src/sunburst-chart.html
libs/barista-components/sunburst-chart/src/sunburst-chart.spec.ts
libs/barista-components/sunburst-chart/src/sunburst-chart.ts
libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts

This PR includes functionality to enable the tracking of hover events on the sunburst chart. This component now presents two output events, **hoverStart** and **hoverEnd**, which emit the data of the series the user has hovered over.

feat(sunburst-chart): Added hover output for slices.

---

libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts

The Y axis in a stacked series chart is not correctly rendered when the chart is loaded with `[visibleValueAxis]="true"`
The rendering of this Y axis is done based on a `Subject` that is triggered on `set` functions. However, the subscription to the `Subject` is done after setting all parameters, so the rendering is not performed.
This PR consists on changing the type to `ReplaySubject`, so that all events happening before the subscription will be also considered and the Y axis will be correctly displayed.

fix(stacked-series-chart): Fixes the initial display of the Y axis.

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
apps/components-e2e/src/components/filter-field/filter-field.html
apps/components-e2e/src/components/filter-field/filter-field.po.ts
apps/components-e2e/src/components/filter-field/filter-field.ts
libs/barista-components/filter-field/src/filter-field-util.ts
libs/barista-components/filter-field/src/filter-field.ts

Bugfix (non-breaking change which fixes an issue) 
Keep default filtered options checked once the user opens the multiselect panel
https://user-images.githubusercontent.com/20814335/119834909-a55a5d00-bf00-11eb-9203-04b280505cee.mov
https://user-images.githubusercontent.com/20814335/119834848-9a9fc800-bf00-11eb-99d2-185702c89d20.mov
- Set `uid` value for multiselect options in order to properly check if this one is selected
- Updating e2e for checking fixed behaviour

fix(filter-field): Fixing default checked options in multiselect.

---

CHANGELOG.md
package-lock.json
package.json

* **event-chart:** Fixes various issues with the legend and heatfields. ([c617d0a](https://github.com/dynatrace-oss/barista/commit/c617d0a1daa0b90c6e657da42b135702be22ff73))
* **filter-field:** Fixing default checked options in multiselect dropdown. ([ec5b53e](https://github.com/dynatrace-oss/barista/commit/ec5b53e3b4e4b8b1181e68ae4b57f3e085730023))
* **stacked-series-chart:** Fixes the initial display of the Y axis. ([a3ed931](https://github.com/dynatrace-oss/barista/commit/a3ed931ed14f0e47a33dd7e26eab73109513e8bc))
* **filter-field:** Adding 'disabled' handling for multiselect options. ([c8d61aa](https://github.com/dynatrace-oss/barista/commit/c8d61aa5d5f255877db5d2c055e15749ca49ab07))
* **filter-field:** Display a hint when partial options are loaded. …

Release stage/9.7.0

---

apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.e2e.ts
apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.html
apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.po.ts
libs/barista-components/stacked-series-chart/BUILD.bazel
libs/barista-components/stacked-series-chart/src/_stacked-series-chart-theme.scss
libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
libs/barista-components/stacked-series-chart/src/stacked-series-chart.scss

This PR implements two changes in stacked series chart, as described in APM-295657.
Before: https://gyazo.com/7afc817ff23c1493b606b102ec691b46
After: https://gyazo.com/9eb53ddc9a57402b4e94d1b81b2fb4ac
CSS is also adapted for having a correct display on dark mode (and dark mode with the series placed on a Card element).
Before: https://gyazo.com/0aa5573a4b64eeff56c4afe83506b4d9
After: https://gyazo.com/235b64e421660bb072fb7d0f81033d29
e2e for testing the correct behavior depending on the `selectionMode`.

feat(stacked-series-chart): Adding auto scrolling on horizontal overflow

---

libs/barista-components/chart/src/chart.ts
libs/barista-components/core/src/viewport/viewport-resizer.ts
libs/barista-components/quick-filter/src/quick-filter.html
libs/barista-components/quick-filter/src/quick-filter.module.ts
libs/barista-components/quick-filter/src/quick-filter.spec.ts
libs/barista-components/quick-filter/src/quick-filter.ts
tslint.json

Provide a triggerable viewport resizer and use it in the quick filter (triggered on 'openChange' event). This means the content child of quick filter (e.g. chart) can receive the resize event.
Fixes APM-256772.
<hr>
guidelines.
- Docs …

fix(quick-filter): Trigger resize event when sidebar open state changes.

---

libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.spec.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts

Implementation of the APM-295667for the stacked series chart.
**1. Displaying a higher value in the Y axis close to the highest series value. Moreover, adjust the Y axis for the visible nodes when the user clicks on an element of the legend in order to hide it**
Before
After
https://gyazo.com/8c703c68b5915e40a8aefffa8c080d32
**2, Fixing the Y axis display when `displayMode = 'percent'`**
Before
After

feat(stacked-series-chart): Show highest value in Y axis.

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select-trigger.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
libs/barista-components/filter-field/src/filter-field.ts

This PR consist on fixing the keyboard interaction for the filter of type multiselect, described in APM-307773. To sumarize, it fixes the 4 following issues when interacting with multiselect:
1. The filter input adds an space when the user is selecting an option by using the space bar
Before: https://gyazo.com/d20a0570729b61498c736040ac345a70
After: https://gyazo.com/0386b9104c5cc92879bf0e445e35227c
2. The filter keeps the focus on the first element, even if it is disabled, and making selectable when the user presses space
Before: https://gyazo.com/ab2287e2e91e859bf038d1d83a412a65
After: https://gyazo.com/d73b8e37410663cb299e6d8c08b63de9
3. The user can select a disabled option if he/she moves the pointer to the option and presses space bar
Before: …

fix(filter-field): Multiselect keyboard interaction not working correctly

---

libs/examples/src/filter-field/index.ts

Example was missing from the barrel export, which made it hard for barista to  instantiate it at runtime.

chore(filter-field): Fixes an issue with the multi-select example within barista app.

---

libs/barista-components/icon/src/icon-registry.ts
libs/barista-components/icon/src/icon.spec.ts

- internal issue: APM-310496 APM-282779
- nowadays CDNs are distributed systems that does not guarantees your request to reach right place. It started happening few hounders times per day for us that some icon couldn't be loaded
- CloudFront explicitly marks that requests *needs* to be retried
- mechanism is fairly simple, we retry any error from the server side (AWS throws 500 / 504 / 503 / 403)
- 3 retries is enough for other resources we already handle, it should be fine here too
- docs: https://www.learnrxjs.io/learn-rxjs/operators/error_handling/retry
- [*] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [*] Lint and unit tests pass locally with my changes
- [ *] I have added tests that prove my fix is effective …

feat(icon): Retry loading hiccup resources.

---

.snyk

d3-color has a regExp vulnerability. Ignoring it for now and updating it with angular 12, as it is a transitive dependency of d3-scale and potentially a breaking change.

chore(workspace): Update snyk policy for security checks.

---

apps/dev/src/tag/tag-demo.component.html
apps/dev/src/tag/tag-demo.component.ts
libs/barista-components/tag/README.md
libs/barista-components/tag/src/tag-add/tag-add.html
libs/barista-components/tag/src/tag-add/tag-add.scss
libs/barista-components/tag/src/tag-add/tag-add.spec.ts
libs/barista-components/tag/src/tag-add/tag-add.ts

Allows the user to pass a custom value instead of 'Add Tag' (which is still the default value if no custom title is given).
<!-- Feature (non-breaking change which adds functionality)

feat(dt-tag-add): Added custom button and form title

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
apps/components-e2e/src/components/filter-field/filter-field.ts
libs/barista-components/filter-field/src/filter-field-util.ts

This PR fixes the bug in the filter field described in [APM-317632](https://dev-jira.dynatrace.org/browse/APM-317632). For a multiselect filter with grouped suggestions, the definition of pre-selected values programmatically was not working properly.
For example, given the following filter with groupings:
The user should be able to define pre-selected values:
```
filters = [
[
{ name: 'Months', multiOptions: MULTI_SELECT_DATA.autocomplete[1].multiOptions },
{ name: 'All' },
{ name: 'Winter', options: [ { name: 'January' }, { name: 'February' } ] },
{ name: 'Spring', options: [ { name: 'April' } ] },
]
];
```
Before the fix the component was not selecting the values inside the groups: https://gyazo.com/c64f8ac1f60426608e51865842f63822
After the fix, those values are correctly selected: …

fix(filter-field): Multiselect with programmatically defined filters is not stable

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts

This PR fixes the bug described in APM-311774. For a multiselect filter, when trying to modify the values of the filter, as long as there are any values already checked, the "Apply" button is disabled if the user doesn't make any change (select or unselect items).
The fix consist on enabling the button when editing, even if the user doesn't make any change. The button will be disabled only in the case there are no items selected.
Before: https://gyazo.com/81520da20f273237f704f6c19fa24272
After: https://gyazo.com/bd69ee33b3f88fd4ba67c6b92cb764c0

fix(filter-field): Fix multiselect apply button disabled

---

libs/barista-components/icon/src/icon.ts

* Previous fix PR #2172 improved spam a lot, we have now instead 500 logs daily, only 1-2
* But still we have them daily, preferably we'd like to not see it again as a hiccup ;)
* Suggestion: Keep severity as INFO instead WARN

feat(icon): Remove log for missing loading resources.

---

libs/barista-components/inline-editor/src/inline-editor-module.ts
libs/barista-components/inline-editor/src/inline-editor.html
libs/barista-components/inline-editor/src/inline-editor.spec.ts
libs/barista-components/inline-editor/src/inline-editor.ts

Move the error validation flap to a cdk overlay, so it will escape  the overflow handling.
Fixes APM-327558
Bugfix

fix(inline-editor): Move the error-state hints to a cdk overlay to escape overflow handling.

---

libs/barista-components/chart/src/tooltip/chart-tooltip-position.ts

Position of heatmap's tooltip sometimes is not so close to selected bucket.
Should respect the distance to selected bucket
Space occupied by the axis label was not taken into account 
Bugfix
Before:
After:

fix(tooltip): Fixed positioning of heatmaps tooltip.

---

libs/barista-components/overlay/src/overlay-trigger.spec.ts
libs/barista-components/overlay/src/overlay-trigger.ts

Fixing overflow bug in overlay
- Now pinning overlay and unpinning (inside target) will properly reopen overlay
<hr>
guidelines. …

fix(overlay): Fixing overflow bug in overlay

---

libs/barista-components/experimental/datepicker/src/calendar.html
libs/barista-components/filter-field/src/filter-field-range/filter-field-range.html
libs/barista-components/quick-filter/src/quick-filter-group.html
libs/barista-components/quick-filter/src/quick-filter.html
libs/barista-components/tag/src/tag-add/tag-add-button.ts
libs/barista-components/tag/src/tag-list/tag-list.html

this PR increases coverage of i18n messages understood by Angular. Avoids "parts" of the product UI being untranslated.
* Since Angular 11 and Ivy i18n, Angular understands libraries when extracting and building messages
* catched all through tslint `template-i18n` rule, however I didn't enable it as we have same `tslint.json` and no `tslint.spec.json` that would disable this rule for `.spec.ts` (producing many false positives)

feat(components): Increase coverage of translatable messages.

---

libs/barista-components/table/README.md
libs/barista-components/table/src/table.html
libs/barista-components/table/src/table.ts
libs/examples/src/table/table-examples.module.ts
libs/examples/src/table/table-export-example/table-export-example.html

Fixes support for object array and observable data sources.
Adds `exportExcludeList` to allow developer to exclude columns from export.
<hr>
guidelines.
Please choose the type …

feat(table): Update experimental export as CSV functionality.

---

libs/barista-components/chart/src/chart.ts
libs/barista-components/core/src/util/sanitize.ts
libs/barista-components/micro-chart/src/micro-chart.ts
package-lock.json
package.json

Replaced domPurify with angular sanitizer for 10.x releases. 
Adjustment for 11.x will follow shortly. 
FYI @piotrl

fix(charts): Removed dependency of dompurify in favor of angular sanizer

---

libs/barista-components/filter-field/src/filter-field.html
libs/barista-components/filter-field/src/filter-field.spec.ts
libs/barista-components/filter-field/src/filter-field.ts
libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts

The "Clear all" button was always shown even if there were no filters selected in the filter-field. This has now been fixed and unit tests have been adapted.

fix(filter-field): Hide clear-all button when no filters are applied.

---

apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select-trigger.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
libs/barista-components/filter-field/src/filter-field.html
libs/barista-components/filter-field/src/filter-field.ts
libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts

<hr>
Breaking change (fix or change that would cause existing functionality to not work as expected) 
User now is able to navigate from the filter bar to the multiselect options and the other way around, due to that, the auto focus is not working anymore (autoActiveFirstOption) as the focus is set via arrow key navigation.
Cases to consider: 
***Acceptance Criteria 1***
HAVING the filter bar
THEN selecting a multiselect filter
AND start typing
THEN no option should be focused by default
THEN the user press the down arrow key
AND the first option should be focused
***Acceptance Criteria 2***
HAVING the filter bar
THEN selecting a multiselect filter
AND start typing
THEN no option should be focused by default
THEN the user press the up …

feat(filter-field): Adding keyboard functionality to multiselect dropbox

---

libs/barista-components/formatters/src/bits-bytes-formatter.ts
libs/barista-components/formatters/src/bytes/bytes-formatter.spec.ts

Negative values of same magnitude should have same auto-unit conversion as equivalent positive values.

fix(formatters): Ensure auto-unit conversion works also for negative values.

---

tsconfig.base.json

'*' works as replacement for a module, not as a glob pattern here.
Fixes the error:
File '*/barista/libs/examples/src/*/index.ts' not found.
The file is in the program because:
Root file specified for compilation
This is visible only within IDE, here VSCode. I assume types resolution/paths replacement skips the problem during cli based execution:
Thanks!

chore: Fix tsconfig path resolution.

---

libs/barista-components/confirmation-dialog/barista.json

The preview image for confirmation-dialog was incorrect (was using the one for quick filter).

docs(confirmation-dialog): Use correct preview image

---

libs/barista-components/tag/src/tag.scss

Fixes overflow of background for remove button on hover beyond tag element
Before:
After:

fix(tag): Fix remove button hover background overflow

---

libs/barista-components/tag/src/tag-list/tag-list.html
libs/barista-components/tag/src/tag-list/tag-list.scss
libs/barista-components/tag/src/tag-list/tag-list.spec.ts
libs/barista-components/tag/src/tag-list/tag-list.ts

<hr>
Following PR adds functionality to reset 'Show more' in tag list after clicking 'Show less...'.
<!-- Feature (non-breaking change which adds functionality)
- [V] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [V] Lint and unit tests pass locally with my changes
- [V] I have added tests that prove my fix is effective or that my feature works
- [V] I have added necessary documentation (if appropriate)

feat(tag-list): Added show less button

---

apps/dev/src/stacked-series-chart/stacked-series-chart-demo-data.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
libs/barista-components/stacked-series-chart/src/stacked-series-chart.mock.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts

New feature | Stacked series chart - disabled node
Single node of stacked series chart now cannot be set to 'disabled', meaning that it can be hovered over, but cannot be selected. Switch is optional and doesn't do anything unless it is set true.
Checklist
[V] I have read the CONTRIBUTING doc and I follow the PR guidelines
[V] Lint and unit tests pass locally with my changes
[V] I have added tests that prove my fix is effective or that my feature works
[V] I have added necessary documentation (if appropriate)

feat(stacked-series-chart): Disabled node.

---

libs/barista-components/chart/src/selection-area/position-utils.ts
libs/barista-components/checkbox/src/checkbox.ts
libs/barista-components/filter-field/src/types.ts
libs/barista-components/formatters/src/unit.ts
libs/barista-components/schematics/src/utils/ast/update-ng-module-decorator-properties.ts
libs/shared/design-system/interfaces/src/lib/barista/barista-definitions.ts

This PR proposes a change to replace all `const enums` with regular `enums`. The main reason for this change is to improve compatibility with TypeScript projects that have `isolatedModules` enabled.
When `isolatedModules` is turned on, TypeScript ensures that each file can be transpiled independently without requiring information from other files. However, `const enums` are incompatible with this setting as they require type information from other files to be transpiled. This results in a compilation error when `const enums` are used.
It's important to note that regular `enums` are slightly less performant than `const enums` because their usage isn't inlined at compile time. However, the performance difference is generally negligible and is often considered an acceptable trade-off for the …

Refactor 10.x Replace const enums with regular enums

---

libs/barista-components/chart/src/selection-area/position-utils.ts
libs/barista-components/checkbox/src/checkbox.ts
libs/barista-components/filter-field/src/types.ts
libs/barista-components/formatters/src/unit.ts
libs/barista-components/schematics/src/utils/ast/update-ng-module-decorator-properties.ts
libs/shared/design-system/interfaces/src/lib/barista/barista-definitions.ts

This PR proposes a change to replace all `const enums` with regular `enums`. The main reason for this change is to improve compatibility with TypeScript projects that have `isolatedModules` enabled.
When `isolatedModules` is turned on, TypeScript ensures that each file can be transpiled independently without requiring information from other files. However, `const enums` are incompatible with this setting as they require type information from other files to be transpiled. This results in a compilation error when `const enums` are used.
It's important to note that regular `enums` are slightly less performant than `const enums` because their usage isn't inlined at compile time. However, the performance difference is generally negligible and is often considered an acceptable trade-off for the …

refactor(enums): Replace const enums with regular enums

---

libs/barista-components/table/src/simple-columns/simple-column-base.ts

fix(table): Fixes an issue with cell access.
